### ISSUE TITLE
Displaying video with transparent status bar

### ISSUE THREAD

**Issue by Nominalista** [eneim/Toro#101]
I noticed bad behavior with setting transparent status bar. 

I created sample [here](https://github.com/Nominalista/VideosFeed) and [here](https://github.com/Nominalista/VideosFeed/blob/master/sample_video.mp4) is video with problem. 

Is it related to library or it's AppCompat bug?

**Comment by eneim** [comment]
@Nominalista Without checking out your repo, what I'm thinking is the elevation of UI group on the top, and your Video components. I will confirm it later.

**Comment by Nominalista** [comment]
Unfortunately changing elevations didn't helped.

**Comment by Nominalista** [comment]
This is not issue related to library.
