### ISSUE TITLE
How to cache video in local storage during playing video using toro library.

### ISSUE THREAD

**Issue by initfusion** [eneim/Toro#102]
i want cache video like instagram so how to achieve functionality using toro library.

**Comment by eneim** [comment]
@initfusion I don't control this. It relies on the Playback component, i.e MediaPlayer or ExoPlayer in this case. I suggest you to refer to them first.

**Comment by dharmeshmp** [comment]
Thanks eneim for suggestion.

**Comment by rafa0809** [comment]
@dharmeshmp ExoPlayer implements caching by itself! Just include the ExoPlayer-okhttp extension in your project: compile 'com.google.android.exoplayer:extension-okhttp:r2.0.1' 

Check the issue here: https://github.com/google/ExoPlayer/issues/1157

**Comment by RockyLin** [comment]
@dharmeshmp Before I use the extension, ToroVideoView was good to run. But it crashed when I use the extension saying:Cannot find ToroVideoView.

**Comment by eneim** [comment]
you need to update your dependencies and change the internal. ver 1 and ver 2 is not compatible ...

**Comment by RockyLin** [comment]
@eneim Thank you for this awesome lib!

These are what I use:
compile 'im.ene.lab:toro:2.0.0-SNAPSHOT'
compile 'im.ene.lab:toro-ext:2.0.0-SNAPSHOT'

Which dependency needs to change?

**Comment by eneim** [comment]
@RockyLin please refer to Readme for latest version. It should be 2.1.0 with a bit different in the artifact Id.
