### ISSUE TITLE
looping video

### ISSUE THREAD

**Issue by initfusion** [eneim/Toro#107]
how to set looping on video using ExtVideoViewHolder or ExoVideoViewHolder?

**Comment by eneim** [comment]
@initfusion Please take a look at this [sample](https://github.com/eneim/Toro/tree/develop/toro-sample/src/main/java/im/ene/toro/sample/feature/extended).

**Comment by initfusion** [comment]
Thank you so much...

**Comment by Nominalista** [comment]
I still don't know how to loop video. While extending ExtVideoViewHolder video is not looping.

**Comment by eneim** [comment]
@Nominalista You need to override the method ```getNextTarget``` and return ```Target.THIS_PLAYER``` instead. Sorry for the lack of documentation.
