### ISSUE TITLE
Get the progress of video play back

### ISSUE THREAD

**Issue by RockyLin** [eneim/Toro#108]
Hi, @eneim 

Thanks for this great Lib!

I used it on a Recyclerview and it works perfectly!  However,  I'm trying to implement a progress bar indicating the progress of the video playback.

In your  README.md, Section 2.Toro in action, I notice that there is a digital progress note. But I can't find it when I run the project sample.

PS:
MyViewHolder extends **ToroVideoViewHolder,** 
MyAdapter extends **ToroAdapter<ToroAdapter.ViewHolder>**

Thanks a lot!
![progress](https://cloud.githubusercontent.com/assets/6820710/19594286/0d5c55dc-97b7-11e6-9215-5effe3ebbf10.png)

**Comment by rafa0809** [comment]
Take a look at the class **ToroVideoViewHolder**. It contains this method:

```
@Override
 public void onPlaybackProgress(int position, int duration)
```

So you can easily update the view elements to show the current progress!

**Comment by RockyLin** [comment]
@rafa0809 Thanks for your reply!
I'm sorry! Are we talking about the same ToroVideoViewHolder? Cause I'm pretty sure that I cannot find the method you mentioned above in ToroVideoViewHolder.

Enlighten me if I'm wrong,please!  Much appreciated!

Thank you!
PS:I'm using Version 2.0.0 SNAPSHOT

**Comment by rafa0809** [comment]
@RockyLin I'm on version 1.2.0! Not sure about how to work on 2.0, sorry!

**Comment by eneim** [comment]
Hi, sorry for the inconvenient. In 2.x, you can always get the progress by calling ```player.getCurrentPosition()```. To show it, you just need to place a TextView and run a handler to update the TextView. I will put this in sample App.

**Comment by RockyLin** [comment]
@eneim Thanks a lot!

**Comment by rafa0809** [comment]
Hi again @eneim !
Will this feature be available again like in 1.2?

**Comment by eneim** [comment]
@rafa0809 You can always call "player.getCurrentPosition" because it is a part of both API version. Anyway it is highly recommended to use ver 2. It saves you some method counts in extra FYI.

**Comment by rafa0809** [comment]
Yes @eneim , I'm aware of this. But, is more elegant to implement the method ''void onPlaybackProgress(int position, int duration)'' in the ViewHolder like in 1.2. instead of implement my own thread that checks for ''player.getCurrentPosition()'' every time to update the video progress.

Otherwise, which is the best way to update a progressbar for the video progress?

**Comment by eneim** [comment]
@rafa0809 Ah I got it. I thought you want the getCurrentPosition feature into 1.2.0 :D. Actually in 1.2, I also used a handler to make it happen. So you can always to the same thing. I can provide a sample in a day or two, but the idea maybe extending the ToroPlayer interface, and build an extension on top of it. It maybe a over-kill, but that's the straightforward way I'm thinking about now.

**Comment by rafa0809** [comment]
Hi @eneim ! Any new about this sample?

**Comment by jemshit** [comment]
@eneim i couldn't found `getCurrentPosition ` on simpleExoPayer on v3.2.0, sth changed?

**Comment by jemshit** [comment]
Found, i had to do `playerView.getPlayer().getCurrentPosition` 👍

**Comment by jemshit** [comment]
Rxjava snippet:

```
SimpleExoPlayer player = playerView.getPlayer();
disposable = Observable.interval(1, TimeUnit.SECONDS)
               .subscribeOn(Schedulers.io())
               .observeOn(AndroidSchedulers.mainThread())
               .subscribe(aLong -> {
                    if (player != null)
                            handle(player.getDuration(), player.getCurrentPosition());
                    });
```
