### ISSUE TITLE
how to implement simple recyclerview with your lib which have images and videos and when video is foucs then it will auto play ..

### ISSUE THREAD

**Issue by iamnitesh** [eneim/Toro#118]
Hello , i am integrate your lib in my project but due to lot's of classes in your lib i don't getting idea how to implement in recyclerview for display images and play video with mute when focus and enable audio when tap on videoview.
please , help me..

**Comment by Nominalista** [comment]
See sample app in repository.

**Comment by iamnitesh** [comment]
is any way available to disable video auto play and set it manually when require ?

**Comment by eneim** [comment]
What do you mean by "when required". Can you give an example?

**Comment by iamnitesh** [comment]
from Toro Sample i have implement "extended" demo for display video and images but in "ExtendedAdapter", onBindViewHolder not available. so , how can i send images list  to "ExtendedNormalViewHolder" bind method.


when require means  ---> Need of  my application is user can set video auto play functionality from setting fragment whether they want video auto play functionality "on" or "off" for Application
if user switch "off" video auto play from setting fragment then video can not autoplay when scroll and focus in MediaFeed Fragment ,but user can play by clicking on playbutton.

can i set  like 
```
@Override public void onVideoPrepared() {
        super.onVideoPrepared();
        videoView.pause();
        stateView.setText("Prepared");
    }
```
for stop video auto play
 please help me ....

**Comment by eneim** [comment]
Please take a look at this Wiki: https://github.com/eneim/Toro/wiki/3.-ToroStrategy:-the-Judgement

The idea is: create your own ToroStrategy which "does nothing", when you don't want to play, call Toro.setStrategy() to that strategy, otherwise, use a built-in one.

P/S: I have already answered the same question from you with the same solution using ToroStrategy, please take a look on that.

**Comment by iamnitesh** [comment]
can you tell me what kind of Strategy i need to set for stop video auto play and allow to play when touch on VideoItem ?
As Discussed above ,this is need of My Application so i complete my task as soon as possible by your help ..

**Comment by iamnitesh** [comment]
how to prevent device sleep when video playing is running ?

**Comment by eneim** [comment]
This is not a Toro issue. I suggest you to search for "Android View keep Screen on" keyword.

About the Strategy, take a look at this [Do nothing Strategy](https://github.com/eneim/Toro/blob/dev-v2/toro/src/main/java/im/ene/toro/Toro.java#L55) and this [Method](https://github.com/eneim/Toro/blob/dev-v2/toro/src/main/java/im/ene/toro/Toro.java#L147)
