### ISSUE TITLE
How to pass video_url to onBind when implement onBindViewHolder method ?

### ISSUE THREAD

**Issue by iamnitesh** [eneim/Toro#119]
Hello , i am working with Extended Sample from Samples of Toro Lib but i am facing one issue 
here i have attach onBindViewHolder and ExtendedVideoViewHolder for your reference..

```
@Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        super.onBindViewHolder(holder, position);
        NewsFeed newsFeed=list.get(position);
        if (holder instanceof ExtendedNormalViewHolder) {
            ExtendedNormalViewHolder viewHolder = (ExtendedNormalViewHolder) holder;
            viewHolder.bind(this,newsFeed);
        }
        else if(holder instanceof ExtendedVideoViewHolder)
        {
            ExtendedVideoViewHolder videoViewHolder=(ExtendedVideoViewHolder)holder;
            videoViewHolder.bind(this,newsFeed);
        }

    }
```

```
 public class ExtendedVideoViewHolder extends ExtVideoViewHolder
{
  ......
  ........
 @Override
        public void bind(RecyclerView.Adapter adapter, @Nullable Object item) {

            if (!(item instanceof SimpleVideoObject)) {
                throw new IllegalArgumentException("Invalid Object: " + item);
            }
            this.video = (SimpleVideoObject) item;
            this.videoView.setMedia(Uri.parse(this.video.video));
            this.videoView.setVolume(0);
        }

   ...........
    ........

}
```

bind method throw InvalidObject Exception because i am passing videoViewHolder.bind(this,newsFeed); of type newsfeed and according to demo require type is  this.video = (SimpleVideoObject) item; 
so , how can i resolve this issue please help me
and when i Override onBindViewHolder in adapter at that time "protected Object getItem(int position)" is compulsory to implement ?

**Comment by Nominalista** [comment]
Your NewsFeed object should contain SimpleVideoObject, so whenever you calling onBind, you should pass newsFeed.getSimpleVideoObject().

**Comment by iamnitesh** [comment]
you means to say put class SimpleVideoObject inside NewsFeed Pojo ?

**Comment by Nominalista** [comment]
or NewsFeed can extends SimpleVideoObject but its weird. 

```
if (!(item instanceof SimpleVideoObject)) {
                throw new IllegalArgumentException("Invalid Object: " + item);
}
```

This checks if item is SimpleVideoObject so you have to pass SimpleVideoObject or it child. NewsFeed can contain on its field SimpleVideoObject and it that way you have to call onBind(..., newsFeed.getSimpleVideoObject())

**Comment by iamnitesh** [comment]
Hello , i do some stuff as you said but it still throw error

in, on BindViewHolder 
videoViewHolder.bind(this,newsFeed.getSimpleVideoObject());

 ```
@Override
    protected Object getItem(int position) {

        if(list.get(position).media_type.equalsIgnoreCase("image"))
        {
            return  new NewsFeed();
        }
        else
        {
            NewsFeed newsFeed = new NewsFeed();
            newsFeed.setSimpleVideoObject(list.get(position).media_url);
            return newsFeed.getSimpleVideoObject();
        }

    }
```
Exception throw here... 
```
@Override
        public void bind(RecyclerView.Adapter adapter, @Nullable Object item) {

            if (!(item instanceof SimpleVideoObject)) {
                throw new IllegalArgumentException("Invalid Object: " + item);
            }
            this.video = (SimpleVideoObject) item;
            this.videoView.setMedia(Uri.parse(this.video.video));
            this.videoView.setVolume(0);
        }
```

**Comment by eneim** [comment]
In the example I use the check to enforce that my VideoViewHolder only accept that type of data. You can remove it by your will.

**Comment by eneim** [comment]
Remove this from your implementation

```java
  if (!(item instanceof SimpleVideoObject)) {
                throw new IllegalArgumentException ...
```

**Comment by iamnitesh** [comment]
thanks @eneim and @Nominalista  now it's work like charm..

**Comment by iamnitesh** [comment]
Hello i face one more issue with my adapter here i am attach onBindViewHolder and getItem, problem is ExtendedNormalViewHolder not call but item is exact list.size() so, please tell me what is problem

```
@Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        super.onBindViewHolder(holder, position);
        NewsFeed newsFeed=list.get(position);

        if (holder instanceof ExtendedNormalViewHolder) {
            ExtendedNormalViewHolder viewHolder = (ExtendedNormalViewHolder) holder;
            viewHolder.bind(this,newsFeed);
        }
        if(holder instanceof ExtendedVideoViewHolder)
        {
            ExtendedVideoViewHolder videoViewHolder=(ExtendedVideoViewHolder)holder;
            videoViewHolder.bind(this,newsFeed);
        }

    }
```

```
@Override
    protected Object getItem(int position) {
        return  new NewsFeed();
    }
```

**Comment by eneim** [comment]
@iamnitesh I could not get the point from your question. Please tell me: what you have done, what is expected result, and what is the result you get.

P/S:

Don't do this

```
protected Object getItem(int position) {
        return  new NewsFeed();
}
```

**Comment by iamnitesh** [comment]
now i getting what i want..
Thank you for your help :)

**Comment by iamnitesh** [comment]
hello , can i get state when video is stop during play for display progressbar ?

**Comment by eneim** [comment]
@iamnitesh This is not an issue. Please figure it by yourself. HINT: ExoPlayer implement has a close stuff with that. Please investigate their code base for more information.

**Comment by iamnitesh** [comment]
@eneim  i am not saying this is issue, i am just asking you is it possible to get that perticular state from exoplayer using your library?, thank you.

**Comment by eneim** [comment]
I'm saying this request must be done by your investigation.

**Comment by iamnitesh** [comment]
ok i wil try..

**Comment by iamnitesh** [comment]
is there any way to restart playing when getback to perticular video after scroll ? i don't want to play from last point ..

**Comment by eneim** [comment]
1. Create an Adapter and implement MediaPlayerManager like [this one](https://github.com/eneim/Toro/blob/dev-v2/toro-sample/src/main/java/im/ene/toro/sample/feature/facebook/timeline/TimelineAdapter.java#L37) (It use the Composition pattern).

2. In [This method](https://github.com/eneim/Toro/blob/dev-v2/toro-sample/src/main/java/im/ene/toro/sample/feature/facebook/timeline/TimelineAdapter.java#L176), pass ***0*** as input **position**.

**Comment by iamnitesh** [comment]
hi @eneim , i have implement your library using **compile line** and as per discuss previous i want to show ProgressBar when **ExoPlayer.STATE_BUFFERING**  but i face one problem because you  set **onPlayerStateChanged****in **ExtPlayerViewHelper**. so, if i set **this.videoView.setPlayerCallback(...)** inside   **public void bind(RecyclerView.Adapter adapter, @Nullable Object item)** of my **public class ExtendedVideoViewHolder extends ExtVideoViewHolder** at that time my version of
**onPlayerStateChanged** is called and video is not play so what stuff i need to do for resolve this ?

**Comment by iamnitesh** [comment]
hi @eneim  i am getting player object null 

```
 adapter.setOnItemClickListener(new ExFbAdapter.ItemClickListener() {
                                @Override
                                protected void onVideoClick(RecyclerView.ViewHolder viewHolder, View view, NewsFeed item) {
                                    long duration = C.LENGTH_UNSET;
                                    long position = C.POSITION_UNSET;
                                    int order = viewHolder.getAdapterPosition();
                                    **ToroPlayer player = adapter.getPlayer();**
                                    if (player != null) {
                                        duration = player.getDuration();
                                        position = player.isPlaying() ? player.getCurrentPosition()
                                                : adapter.getSavedPosition(UtilToro.genVideoId(item.media_url, order)); // safe
                                    }
                                }
                            });
```
Please tell me what is issue my side ..
