### ISSUE TITLE
Multiple concurrent playing videos 

### ISSUE THREAD

**Issue by theostanton** [eneim/Toro#12]
Apologies for a feature request in issues section. I can't seem to find the reddit I found the library in, if you have a link to that we could continue discussion there. 

Would love to be able to have more than one video playing at a time by setting a max number in the strategy. Any prospect of implementing this ?

**Comment by eneim** [comment]
Here is the link you want

```https://www.reddit.com/r/androiddev/comments/44fket/simple_solution_for_auto_playback_video_list_in/```

IMO, I try to avoid multiple video. Since I don't see it's useful. Can you give me a good reason?

**Comment by theostanton** [comment]
Thanks. Have replied on reddit.
