### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by Apisov** [eneim/Toro#13]
Hello.
Is it possible to play a video in loop?

**Comment by Apisov** [comment]
Looks like I found some solution:
calling "resume" of videoview in "onPlaybackStopped" method.

Not sure that this is correct way, but it works anyway.

**Comment by eneim** [comment]
In Strategy I prepared a ```allowsImmediateReplay``` for that purpose (actually it is a bad method naming, and I will change it anyway, in the future release). For now, Toro doesn't support this method yet. Because it is not that straightaway to determine when a playback properly complete. Some new Player API may not follow current MediaPlayer API and then onCompletion may not be called. So I would like to research a bit more to provide better support.

For now your workaround could work in your case. So keep it. I will try to add the support as soon as possible.

**Comment by Apisov** [comment]
I see. Thank you for your reply.

If we started talking about future releases I have question:
Why you decided don't give access to Media Player from ToroVideoView?
In my case I was needed to mute sound or unmute. Or you have some another ways how to make it?

**Comment by eneim** [comment]
@Apisov You mean the built-in ```im.ene.lab.toro.widget.ToroVideoView``` class? I think the story is opposite: you have control to the **MediaPlayer** (here: it is the *android.media.MediaPlayer*). In ```ToroVideoViewHolder``` class (which holds a ToroVideoView as its Video player widget), you can see that I implemented many callbacks from MediaPlayer's interfaces. From there, If you use my built-in ViewHolder, you can override ```onPrepared``` method to have the control of the ```MediaPlayer object``` which has the responsibility to play your video. Note that this instance will be available after your Video is prepared (i.e onPrepared is the best place where you should access to it). And in my experience, you can control the Audio from there. Hope this help.

**Comment by Apisov** [comment]
Thank you a lot for such a detailed answer. I missed this possibility to control MediaPlayer. This is what I was looking, yes.

**Comment by AmrMohammed89** [comment]
@eneim hi , i have the same problem .. but the difference is that in my view holder the method "onPlaybackStopped" never called .. i don't know what is the problem ?

**Comment by eneim** [comment]
@AmrMohammed89 Hey can you make this as a new issue? And if it is possible please post your part of code where you use the widget too. Thanks!

**Comment by thanhbinh84** [comment]
I am using im.ene.toro2:toro-extended:2.1.0. I cannot find neither onVideoPrepared(MediaPlayer) nor isLoopAble(). Finally, I need to extend ExtVideoViewHolder and override getNextTarget() 
`@Override
        public Target getNextTarget() {
            return Target.THIS_PLAYER;
        }`
