### ISSUE TITLE
need sample/tutorial to play YouTube videos.

### ISSUE THREAD

**Issue by hendraanggrian** [eneim/Toro#132]
The [changelog](https://github.com/eneim/Toro/blob/dev-v2/CHANGELOG.md) confirms that this library is capable of playing YouTube videos, but then the sample module shows no example of it.

There are some YouTube video ids in [VideoSource.java](https://github.com/eneim/Toro/blob/dev-v2/toro-sample/src/main/java/im/ene/toro/sample/data/VideoSource.java), but the class is pretty much unused.

**Comment by eneim** [comment]
@hendraanggrian So sorry, it was in 2.0 RC-4 and no longer work. Youtube playback API is really un-friendly so I need to hold it back. If you are capable of getting the stream URL, playing that stream is just the same with any other Video IMO. Further investigation on Youtube API TOS may need.

**Comment by hendraanggrian** [comment]
@eneim thank you for clarifying. I imagine it is possible to retrieve the stream url by loading the webpage in some WebView, parse the html with Jsoup to scrap the actual stream url. It is not a very efficient solution but it might be the only working one at least until YouTube is officially supported again.

Once again, thank you for this fantastic library!

**Comment by eneim** [comment]
@hendraanggrian Thanks. You'd better take care of Youtube TOS before any further implementation. They have strict requirement on the content. That is one factor that prevents me to go further.
