### ISSUE TITLE
How to play all videos visible on screen

### ISSUE THREAD

**Issue by thanhbinh84** [eneim/toro#133]
(im.ene.toro2:toro-extended:2.1.0)
(Asus | nexus 7 2012 | 4.4.4 | root)
By default, there is only one video played at the time. Is it possible to play all videos visible on screen? I read on wiki about `ToroStrategy` and try to customize but no luck.

**Comment by eneim** [comment]
No, currently Toro supports single Video playback only. NO future support plan until I have a reasonable motivation. I always consider playing many video at a time is a bad practice, please give me some better points.

**Comment by thanhbinh84** [comment]
I am porting an iOS app into Android, that's a customer requirement. They said if iOS can do, so do Android. I have explained about performance, battery... but they insisted. It would be great if Toro could be open for this kind of feature with an warning about performance. Thanks.

**Comment by eneim** [comment]
Well, since you are not the only one to request this feature, I will try to make it. But it will be time consuming. Will keep you update with the roadmap.

**Comment by thanhbinh84** [comment]
That's great! such a good news.

**Comment by thanhbinh84** [comment]
It is possible now with version 3.1 

[https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/complex/ComplexListFragment.java](url)

Thanks a lot, @eneim, you are the man.
