### ISSUE TITLE
How to remain auto play top video till its visiblity is more than 50% during scrolling.

### ISSUE THREAD

**Issue by shailesh2208** [eneim/Toro#139]
I connected to toro library to auto play top video of Recyclerview using `"compile 'com.github.eneim:Toro:1.2.0"` gradle. It is working fine. When we start scroll from down to top then second video is playing automatically. Now I want that When the visibility of top video is going to less that 50% then second video auto play start and during scrolling top to bottom when top video get visibility more than 50% then second video auto play should be off and top video auto play should be start.
For achieving this functionality I am using this method

```
@Override
    public boolean wantsToPlay() {
        return visibleAreaOffset() >= 0.5f;
    }

    @Override
    public float visibleAreaOffset() {
        Rect videoRect = getVideoRect();
        Rect parentRect = getRecyclerViewRect();
        if (parentRect != null && !parentRect.contains(videoRect) && !parentRect.intersect(videoRect)) {
            return 0f;
        }
        float area = videoRect.height() * videoRect.width();
        float viewArea = getVideoView().getWidth() * getVideoView().getHeight();
        return viewArea <= 0f ? 1.f : area / viewArea;
    }
```
but during scrolling when the top video visibility is less than 100% then second video auto play start.
How can we achieve functionality to auto play top video till its visibility is more than 50%?

**Comment by eneim** [comment]
@shailesh2208 Take a look at your ToroStrategy too. It may be the one that will prior the View with higher visibility. Use the first one for your expected behaviour. I also suggest you to move on Toro 2.1.0 for latest support. Thanks for using Toro.
