### ISSUE TITLE
Video freezes, audio continue playing.

### ISSUE THREAD

**Issue by cubatertech** [eneim/Toro#144]
I'm using Toro 2.1 lib for auto playback video in Recycler view. Its working fine.
But face issue when app goes to onPause state & again resume from there. Then only hearing voice not showing video. Toro inside using ExoPlayer. Please provide some tips. Thanks.

**Comment by eneim** [comment]
@cubatertech Can you give more info about your case as follow:

- Gradle dependency that is related to Toro

- Device and Android version

- Video info: resolution, codec, audio spec, ...

- Video URL if possible.
