### ISSUE TITLE
TextureView in ToroVideoView destroys on opening another Activity

### ISSUE THREAD

**Issue by rahulrj** [eneim/Toro#15]
Suppose i open another Activity from `ToroVideoView`, in its `onTouchEvent()` function,then the `TextureView` gets destroyed and created again automatically. I get both `onSurfaceTextureDestroyed` and `onSurfaceTextureAvailable` callbacks one after other immediately.

**Comment by eneim** [comment]
@rahulrj I'll check it out. I think this surface should be destroyed if you move to another Activity. So the ```onSurfaceTextureAvailable``` is unexpected. Due to the issue title, I wonder what is your expected behavior actually?

**Comment by rahulrj** [comment]
@eneim I was trying to make the player full screen when i tap onto it.

**Comment by eneim** [comment]
@rahulrj I understand that. What I mean is "what would your expected behavior of that **Surface**" :D. Your issue title would tell me that you want it to be *alive* (not being destroyed), but IMO, I expected the Surface to be destroyed.
