### ISSUE TITLE
Video don't start after return to activity 

### ISSUE THREAD

**Issue by iarczi** [eneim/Toro#155]
Make sure to provide the following informations and check:

- [  compile "im.ene.toro2:toro-extended:2.1.0"] Toro dependencies

- [Samsung | G4 Active | 5.0.1 | clean ] Android manifacture | product name | OS Version | rooted or clean

- Logcat (if it was a fatal issue)

In Application class I have Toro.init

In Activty A I have recyclerView with videos
I first start Activty A and everything works
then I click on recyclerView item and start Activty B with full screen video
then on back pressed I return to Activty A, and now my video, which I clicked on, don't start
Moreover if I scroll, and this video wasn't recycled, it will never start again. 
Other videos (not clicked videos) works normal
Do you have any ideas why it happens?

Below flow of callbacks.

Activty A: onResume: Toro.register
ToroVideoHolder: onVideoPrepared: VIDEO_1
ToroVideoHolder: onVideoPrepared: VIDEO_2
ToroVideoHolder: onPlaybackStarted: VIDEO_1
ToroVideoHolder: onPlaybackPaused: VIDEO_2
ToroVideoHolder: onPlaybackStarted: VIDEO_1
Activty A: : onPause: Toro.unregister
ToroVideoHolder: onPlaybackPaused: VIDEO_1
Activty  B in
Activty  B out
Activty A: onResume: Toro.register
onPlaybackStarted: VIDEO_1
onVideoPrepared: VIDEO_1
onActivityInactive: VIDEO_1

**Comment by eneim** [comment]
@iarczi This is a known issue. I made a fixed but the SNAPSHOT contains some break changes. Let me push it to 2.1.1 in few days >.< 

Right now one possible work around is: refer to Facebook example, instead of starting new Activity for Full screen player, you can show a DialogFragment on top of current Activity, using the mechanism I used in Facebook example to switch the RecyclerView ...

 I personally prefer this approach. Please try it and tell me if you have trouble.

**Comment by iarczi** [comment]
I left it just it is, and can't wait for new version 2.1.1 :)

**Comment by micHar** [comment]
Hi @eneim, thanks for a nice lib! Unfortunately I have the same problem. Changing Activity to DialogFragment is a little bit problematic for me, so I would rather use the proper fix. Any timeframe for the 2.1.1 version?

**Comment by eneim** [comment]
I'm updating demo app with some good practice, and documentation. v2.2.0 is on plan to release next week with a few big change that needs migration, but not too much, only the Adapter I think (of course a migration guide will be added too).

**Comment by micHar** [comment]
Just to make sure - so the fix for activity lifecycle comes next week with 2.2.0?

**Comment by eneim** [comment]
Yes, right now you can check the current status on 2.2.0-SNAPSHOT and see if it works. Or check out branch dev-v3 and try the demo .

**Comment by eneim** [comment]
2.20-SNAPSHOT requires some changes on your Adapter, so you are warned ...

**Comment by eneim** [comment]
@micHar @iarczi Can you check out to see if [2.2.0-SNAPSHOT](https://github.com/eneim/Toro/releases/tag/2.2.0-SNAPSHOT) works for you? This is the closet to next major release. Feedback from you will be taken care for the final release if possible.

**Comment by micHar** [comment]
In the snapshot, the issue with changing activities has been fixed but there are some other issues introduced unfortunately. Eg.sometimes the video doesn't start at all, it doesn't loop like it used to and sometimes two videos on the list start playing together.

**Comment by eneim** [comment]
@micHar Can you provide more about your code that re-produces the issue?

**Comment by micHar** [comment]
Not today unfortunately, I don't have access to my computer.

**Comment by eneim** [comment]
@micHar FYI I also dealt with those issue in this snapshot (see other issues). So if they are still there for you, please tell me with your code I will take a look :D.

**Comment by micHar** [comment]
So probably they are fixed and I tried an older version. Will try the new one as soon as possible, because as far as this specific issue is concerned, I think it was fixed. Thanks for your great work @eneim :-)

**Comment by eneim** [comment]
I pushed latest one this afternoon, so probably it will fix the issue. But feedback is always welcome.

**Comment by eneim** [comment]
I should have numbered the snapshot release as beta or something, but next time it will be better.

**Comment by developerGM** [comment]
Using 2.2.0 the lifecycle problem is solved (in the old version, activity was destroyed and player set to null)
When I open a new Activity I use `Toro.pause()` and then on ActivityResult use `Toro.resume()`
The problem is that now, using 2.2.0, when scroll up, sometimes the previous videos doesn't play but stay in pause.

**Comment by eneim** [comment]
@developerGM I have acknowledged that issue and working on a fix now. The cause is that I cannot control the way ExoPlayer fires the state change event so I need to think about a workaround.

**Comment by developerGM** [comment]
@eneim yes understand. Thanks
But why with 2.1.0, this problems not happened ?

**Comment by eneim** [comment]
The part problem of not playing after scrolling back to top is my fault after releasing 2.2.0 (on an atempt to fix the duplicated playback). After fixing it in current local branch, it turns out that the main issue is the state of "prepared" where ExoPlayer doesn't care about that while I want to have a checkpoint of when your video is ready to play. So in short: there is a state that cause the trouble and sadly fixing one of them lead to the other ...

**Comment by eneim** [comment]
My current thinking is to forget the state of prepared and try to adapt the way ExoPlayer 2 thinks about a Media's state.

**Comment by developerGM** [comment]
so how can solve ? wait a new release ?

**Comment by eneim** [comment]
I'm thinking of pushing a snapshot to fix the scrollto top issue in a few hour.

**Comment by developerGM** [comment]
this is TOP, thanks. So I can continue to use 2.2.0 that is really stable now. Thanks @eneim for this work

**Comment by eneim** [comment]
@developerGM You can try 2.2.1-SNAPSHOT now, it should fix the scroll to top issue. The issue #174 is my highest priority now for 2.x.

**Comment by developerGM** [comment]
sorry...this ? 
`compile 'im.ene.toro2:toro-extended:2.2.1-SNAPSHOT'`

**Comment by eneim** [comment]
One of the following:

```groovy
compile 'im.ene.toro2:toro-extended:2.2.1-SNAPSHOT'

// or
compile 'im.ene.toro2:toro-ext-exoplayer2:2.2.1-SNAPSHOT'
```

You will need the snapshot repository in your project level gradle.build.

**Comment by developerGM** [comment]
Ok, I have tested "2.2.1-SNAPSHOT" using ExoPlayerView

This is my Log:
```
//MyFragment is collapsed
STATE_BUFFERING > VIDEO 0
STATE_READY > VIDEO 0
playWhenReady = false > VIDEO 0

//Open MyFragment with recyclerView, VIDEO 0 starts
STATE_READY > VIDEO 0
playWhenReady = true > VIDEO 0

// scroll down to VIDEO 1 but sometimes not starts
STATE_BUFFERING > VIDEO 1
STATE_BUFFERING > VIDEO 2
STATE_READY > VIDEO 1
playWhenReady = false > VIDEO 1
STATE_READY > VIDEO 2
playWhenReady = false > VIDEO 2

// scroll up to VIDEO 0 but not restarts
STATE_BUFFERING > VIDEO 0
STATE_READY > VIDEO 0
playWhenReady = false > VIDEO 0

```

**Comment by developerGM** [comment]
@eneim 
Now I am testing "2.2.1-SNAPSHOT" with ExoVideoView

in `STATE_READY `I always have `playWhenReady == false;`

My cicle is the follow:
```
- mRecyclerView.setAdapter(adapter)
- Toro.register(mRecyclerView)
- SlideUpPanel in COLLAPSED state...Toro.pause()
- SlideUpPanel in EXPANDED state...Toro.resume()
```

When I slide up the panel where is `mRecyclerView`, all videos don't play.

**Comment by developerGM** [comment]
@eneim any news ?

**Comment by eneim** [comment]
@developerGM sorry it is GTM +9 here so let me warm up a little bit for Monday morning >.<

**Comment by developerGM** [comment]
@eneim ehe yes of course, sorry.

**Comment by eneim** [comment]
@developerGM What do you mean by "This happen if I use PlayerCallback"?

**Comment by eneim** [comment]
Also, it is not suggested to dynamically use PlayerCallback, I should have provide the "addCallback" instead of "setCallback" ... But right now if you want to have control to STATE_BUFFERING, you can extend the ExoPlayerViewHelper class, override the playstatechange method there. Also there is extra work need to be done on ViewHolder side too (to apply the change for your custom ViewHelper).

**Comment by developerGM** [comment]
Ok, but I have always the problem that during slidingup my recyclerView, the video doesn't starts again...
I am testing "2.2.1-SNAPSHOT" using ExoPlayerView

**Comment by eneim** [comment]
@developerGM Ok so let narrow down to your current use case. I will figure out if it is the issue of pause/resume or not. Literally I could not carefully test those, but I think the approach is simple.

**Comment by developerGM** [comment]
Yes, This is the issue that I have using new 2.2.1-SNAPSHOT.
All others are solved now

**Comment by eneim** [comment]
@developerGM Can you checkout branch "fix/pause-resume" and try the first Example? I can make it works though, but have no idea if it matches your idea.

**Comment by developerGM** [comment]
@eneim In which folder ? I'm in "fix/pause-resume" branch now

**Comment by eneim** [comment]
@developerGM [here](https://github.com/eneim/Toro/tree/fix/pause-resume/toro-sample/src/main/java/im/ene/toro/sample/feature/sheet) (I reuse some class from other places just to verify the behaviour. This contains no fix now).

**Comment by developerGM** [comment]
@eneim Sorry, I think that my previous posts not are clear :)

With last 2.2.1-SNAPSHOT solved:
- if I COLLAPSE and EXPAND my panel I use Toro.pause() and Toro.resume() and works perfectly
- If I click on my Item (inside recyclerView), I use Toro.pause(), so I can open a new Activity and when come back using Toro.resume(), all works and player restarts

Now, the problem, with last ExoPlayerView is that if I scroll down, the videos play regular but when I scrollUp (come back to previous videos), those videos don't start again.

**Comment by eneim** [comment]
@developerGM Hmm, I think the issue of not start playing again is what I try to solve with this. You can try example Basic 4 which uses ExoPlayerView (see the list in Sample App).

**Comment by developerGM** [comment]
Ok, I will test the 2 examples. Thanks

**Comment by maxbaldrighi** [comment]
Hello @eneim!

I'm facing the exact same issue trying to apply the same use-case as @iarchii 's.
The only difference is that i'm using toro version **3.5.2**

Is this still a known unsolved issue?

Here what I'm not understanding after some debugging: after switching Activity the boolean value *playWhenReady* in `onPlayerStateChanged()` method switches automatically to false and even explicitly forcing it to true in `initialize()` method doesn't do the trick, because when the time comes the value is always false.

Any suggestion?

**Comment by eneim** [comment]
@maxbaldrighi do you have any code that can reproduce the issue? For example: how you switch Activity, code of your current ViewHolder where it doesn't work well.

**Comment by maxbaldrighi** [comment]
Sure, I will share with you some code as soon as I manage to put it together.
Thanks!

**Comment by maxbaldrighi** [comment]
ViewHolder source:

    public class FeedMemoryVideoVHToro extends FeedMemoryViewHolder implements ToroPlayer {

	private ExoPlayerViewHelper videoHelper;

	private PlayerView mainView;
	private ImageView thumbnailView;
	private View thumbnailViewLayout;

	private View playBtn;
	private View progressView;
	private TextView progressMessage;
	

	FeedMemoryVideoVHToro(View view, TimelineFragment fragment, OnTimelineFragmentInteractionListener mListener) {
		super(view, fragment, mListener);

		this.mainView = view.findViewById(R.id.video_view);
		thumbnailView = view.findViewById(R.id.video_view_thumbnail);
		thumbnailViewLayout = view.findViewById(R.id.video_view_thumbnail_layout);

		playBtn = view.findViewById(R.id.play_btn);
		progressView = view.findViewById(R.id.progress_layout);
		progressMessage = progressView.findViewById(R.id.progress_message);
		progressMessage.setText(R.string.buffering_video);

		playBtn.setOnClickListener(this);

		super.playBtn = this.playBtn;
	}


	@NonNull
	@Override
	public View getPlayerView() {
		return mainView;
	}

	@NonNull
	@Override
	public PlaybackInfo getCurrentPlaybackInfo() {
		return videoHelper != null ? videoHelper.getLatestPlaybackInfo() : new PlaybackInfo();
	}

	@Override
	public void initialize(@NonNull Container container, final @NonNull PlaybackInfo playbackInfo) {
		if (videoHelper == null) {
			String uri = "";
			if (mItem != null && Utils.areStringsValid(mItem.getContent()))
				uri = mItem.getContent();

			// call to HLApp.exoConfig to loop videos
			videoHelper = new LoopExoPlayerHelper(this, Uri.parse(uri));
			videoHelper.addEventListener(new Playable.DefaultEventListener() {

				@Override
				public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
					super.onPlayerStateChanged(playWhenReady, playbackState);

					switch (playbackState) {
						case Player.STATE_BUFFERING:
							progressView.setVisibility(View.VISIBLE);
							thumbnailViewLayout.setVisibility(
									(playbackInfo.getResumePosition() == 0) ? View.VISIBLE : View.GONE
							);
							playBtn.setVisibility(View.GONE);
							break;

						case Player.STATE_READY:
							progressView.setVisibility(View.GONE);
							thumbnailViewLayout.setVisibility(playWhenReady ? View.GONE : View.VISIBLE);
							playBtn.setVisibility(playWhenReady ? View.GONE : View.VISIBLE);
							break;
					}
				}
			});
		}
		videoHelper.initialize(container, playbackInfo);

		if (mainView.getPlayer() != null)
			mainView.getPlayer().setPlayWhenReady(true);

		if (canPlayWhenReady) {
			videoHelper.play();
			canPlayWhenReady = false;
		}
	}

	@Override
	public void play() {
		if (videoHelper != null) videoHelper.play();
	}

	@Override
	public void pause() {
		if (videoHelper != null) videoHelper.pause();
	}

	@Override
	public void release() {
		if (videoHelper != null) {
			videoHelper.release();
			videoHelper = null;
		}
	}

	@Override
	public boolean wantsToPlay() {
		return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
	}

	@Override
	public int getPlayerOrder() {
		return getAdapterPosition();
	}

	@Override
	public boolean isPlaying() {
		return videoHelper != null && videoHelper.isPlaying();
	}

	public boolean isAutoPlayOn() {
		return (
				getActivity().getUser().feedAutoplayAllowed(getActivity()) &&
						this.fragment != null && this.fragment.isVisibleToUser()
		);
	}

	private boolean canPlayWhenReady = false;
	public void onBindViewHolder(@NonNull Post object) {
		super.onBindViewHolder(object);

		if (!isPlaying() && !isAutoPlayOn()) {
			playBtn.setVisibility(View.VISIBLE);
			progressView.setVisibility(View.GONE);
		}
		else {
			if (isAutoPlayOn()) {
				if (videoHelper != null && !isPlaying())
					videoHelper.play();
				else if (videoHelper == null)
					canPlayWhenReady = true;
			}
		}

		MediaHelper.loadPictureWithGlide(getActivity(), mItem.getVideoThumbnail(), thumbnailView);
	}


	@Override
	public void onClick(View view) {
		if (view.getId() == R.id.play_btn) {
			if (Utils.isStringValid(mItem.getContent()) && videoHelper != null)
				videoHelper.play();
		}

		super.onClick(view);
	}


	@Override
	public boolean onSingleTapConfirmed(MotionEvent e) {

		mListener.saveFullScreenState();

		Intent intent = new Intent(getActivity(), VideoViewActivity.class);
		intent.putExtra(Constants.EXTRA_PARAM_1, mItem.getContent());
		intent.putExtra(Constants.EXTRA_PARAM_2, mItem.getVideoThumbnail());
		intent.putExtra(Constants.EXTRA_PARAM_3, getCurrentPlaybackInfo().getResumePosition());
		mMainView.getContext().startActivity(intent);

		return true;
	}


	//region == Getters and setters ==

	public ExoPlayerViewHelper getVideoHelper() {
		return videoHelper;
	}

	//endregion

    }

consisting in: 

- Constructor with just some views initialization,
- the ToroPlayer interface overridden methods,
- the override of onSingleTapConfirmed() triggers the new activity.

As I told you, the initialize() method works perfectly as long as I don't leave the first activity. As soon as I do it on the contrary, in onPlayerStateChanged() callback the value "playWhenReady" is always false, thus not triggering the autoplay.
Manually setting the value, setPlayWhenReady(true).
in onBindViewHolder() I tried using an additional boolean `canPlayWhenReady` in order to manually start the player, but again, no effect.

**Comment by eneim** [comment]
@maxbaldrighi will need some time to figure out the cleanest way. Right now, what I do on my demo app is to use startActivityForResult instead. And once the VideoViewActivity need to be finished, it tells the Activity started it about that event, and from there, reset the Container as below:

```java
@Override public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (resultCode == Activity.RESULT_OK && requestCode == RQ_PLAYBACK_INFO && data != null) {
      PlaybackInfo info = data.getParcelableExtra(RESULT_EXTRA_PLAYBACK_INFO);
      int order = data.getIntExtra(RESULT_EXTRA_PLAYER_ORDER, -1);
      if (order >= 0 && container != null) {
        container.setPlayerSelector(PlayerSelector.NONE);
        container.savePlaybackInfo(order, info);
        container.setPlayerSelector(selector);
      }
    }
  }
```

I will think about your case as well. What I'm working on now is to have the helper detachable, so that you can grab it from VideoViewPlayer, keep the playback smooth. And after coming back to the list, it should be fine. Will push something when I finish the draft.
