### ISSUE TITLE
Bug: Sometime app play two video in branch "dev-v3"

### ISSUE THREAD

**Issue by sonvp** [eneim/Toro#157]
Hi @eneim. when i scroll down sometimes happen case app play two video. You can check video below.

![device-2017-02-14-102001-_4_](https://cloud.githubusercontent.com/assets/8717317/22915452/f12e92d2-f2a9-11e6-8441-3ba378135fa0.gif)

**Comment by eneim** [comment]
@sonvp There was a commit that I prepare the player in onAttachedToWindow, can you check it in the ExtPlayerView? If it is still there, please update to latest dev-v3, or use 2.2.0-SNAPSHOT instead.

**Comment by sonvp** [comment]
- @eneim I can't find class "ExtPlayerView" in "dev-v3" ,I see only "ExtPlayerViewHolder" and "ExtPlayerViewHelper"
- And I neither find branch "2.2.0-SNAPSHOT" in github

**Comment by eneim** [comment]
@sonvp Just fixed my comment, it is 'ExoPlayerView' (please pull latest dev-v3 branch). SNAPSHOT is not a branch, it can be found on maven snapshot URL: "https://oss.sonatype.org/content/repositories/snapshots", you can use it as normal gradle dependency.

**Comment by eneim** [comment]
See [this](https://github.com/eneim/Toro/blob/dev-v2/build.gradle#L36) for snapshot URL setting, and [this](https://github.com/eneim/Toro/blob/dev-v2/toro-sample/build.gradle#L109) for gradle SNAPSHOT dependency (change it to 2.2.0-SNAPSHOT and comment out the module dependency).

**Comment by sonvp** [comment]
@eneim I pull latest dev-v3 branch and I check  'ExoPlayerView' , "onAttachedToWindow "  it wasn't there
and I change to 2.2.0-SNAPSHOT but I still see bug above

**Comment by eneim** [comment]
Hmm, can you give me your adapter (can modify it if you have something sensitive). An email to nam@ene.im also works.

**Comment by eneim** [comment]
ViewHolder too if possible @sonvp

**Comment by sonvp** [comment]
@eneim . I only change code Basic4Adapter.class and run app. Below is the code I changed
```
...
 @Nullable @Override protected Object getItem(int position) {
    //if (position % 3 == 0) {
    //  return new SimpleVideoObject("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4");
    //} else {
    //  return new SimpleObject();
    //}
    return new SimpleVideoObject("http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism");
  }
...
```

**Comment by eneim** [comment]
Hmm, got it. Let me check it too. Also you will get latest good state by 2.2.0-SNAPSHOT instead of dev-v3 (which suppose to be 2.2.0) :D.

**Comment by eneim** [comment]
@sonvp Hey can you checkout branch **feature/demo-update** and see if it works?

**Comment by sonvp** [comment]
@eneim I checkout branch feature/demo-update, but I still see bug above.

**Comment by sonvp** [comment]
@eneim You can check video describe steps by steps happen bug with link below.
https://drive.google.com/file/d/0B_Q06qKRUkZGcGpWcFRJUFZ2NTQ/view?usp=sharing

**Comment by eneim** [comment]
@sonvp Thanks a lot. I can now re-produce the issue and try to fix it soon.

**Comment by eneim** [comment]
@sonvp Please check out branch "fix/duplicated" which is dedicated for this fix. I believe it works correctly now.

**Comment by eneim** [comment]
@sonvp 2.2.0-SNAPSHOT is now better handling your case, please check it out (see [releases](https://github.com/eneim/Toro/releases/tag/2.2.0-SNAPSHOT)) for more information.

**Comment by sonvp** [comment]
Thank @eneim . I will check it out ([releases](https://github.com/eneim/Toro/releases/tag/2.2.0-SNAPSHOT))

**Comment by sonvp** [comment]
Hi @eneim . I checked your (releases) .
- I see issue in view Basic 4 (using ExoPlayerViewHolder) when I open view Basic 4. First video isn't playing, it only playing when I scroll RecycleView then I scroll down Third video and scroll up First video, it still isn't playing, 
- I checked  in view Basic 1 (using ExoVideoViewHolder), It work well.
- You can check bug with link below
https://drive.google.com/file/d/0B_Q06qKRUkZGMFBHbE9SU1RfbHc/view?usp=sharing

**Comment by eneim** [comment]
@sonvp thanks for your quick feedback. Actually the first one is kind of expected behaviour: There are 5 or 6 Views/ViewHolders are attached at launch. On that event, the video will be prepared and the last one got prepared wins the auto playback behaviour. In this case, the one got triggered is hidden below because the height changes and so on. 

This is not a nice UX, sadly. There is a work around is to implement a special Strategy that skip the auto playback until the first video is triggered. Want to note that by default Adapter doesn't know which is the first video to play, and IMO it should not (your app should decides that, using custom Strategy). A Strategy like that can be found [here: Facebook playlist sample](/toro-sample/src/main/java/im/ene/toro/sample/feature/facebook/playlist/FacebookPlaylistFragment.java#L95), even though it is not great now. If other issues are fine now I will spend time improve this strategy and make it official.
