### ISSUE TITLE
Previous Image with SetShutterView?

### ISSUE THREAD

**Issue by jonathansds** [eneim/Toro#163]
Hello,

First, let me say thanks for this great work!! So far the best lib I've found for this functionality! Thanks so much!

I'm using the Toro "toro-ext-exoplayer2:2.1.0" version and I'm trying figure out a way to instead of showing that black view before play the video, show an image took from the video. I noticed that this black view is the "shutterView" attribute in "ExoVideoVidew" component which already manage all the states and the proper moment to show/hide it. 
Is there a way to provide a method (setShutterView(url or bitmap or any convenient object)) which would set the shutterView then before you initialise this view with black background you would check if it's null or already set up?

It'd would be very appreciated!

Once again, thanks!

**Comment by eneim** [comment]
@jonathansds ExoVideoView is just another FrameLayout, you can always put your custom ImageView on top of it. You can check demo app, the "Facebook Timeline sample" and also take a look at its implementation [here](https://github.com/eneim/Toro/blob/dev-v2/toro-sample/src/main/java/im/ene/toro/sample/feature/facebook/timeline/VideoViewHolder.java).

**Comment by jonathansds** [comment]
Yup, I already implemented on that way. Just asking cause once it's already done (instead of a picture you put a black view) inside ExoVideoView and just a "set" method would need to be exposed, I thought it'd be better than just create another view and handle it outside the lib. Anyway, thanks so much for the reply, I did it and it worked.

Thanks.

**Comment by eneim** [comment]
@jonathansds thanks for your comment. I actually try to mimic the behaviour of ExoPlayer default SimpleExoPlayerView (in 2.2.0 I also implement ExoPlayerView on top of it). The shutterView is part of its internal so I don't want to touch :D Instead I will put another view for my custom behaviour.

**Comment by jonathansds** [comment]
Yup, works great! Well, so you can considerate this issue closed. Thanks a lot!
