### ISSUE TITLE
I am not able to access class "ExoPlayerViewHolder" 

### ISSUE THREAD

**Issue by AmanChugh** [eneim/Toro#165]
Make sure to provide the following informations and check:

- [ ] Toro dependencies ( compile "im.ene.toro2:toro:${toroVersion}"
    compile "im.ene.toro2:toro-extended:${toroVersion}"
    compile "im.ene.toro2:toro-ext-exoplayer:${toroVersion}"
    compile "im.ene.toro2:toro-ext-exoplayer2:${toroVersion}")

   toroVersion = '2.1.0'

**Comment by eneim** [comment]
Which makes you try to use this class?

P/S: you use the wrong version ...

**Comment by AmanChugh** [comment]
Can you please suggest me. I want to show Videos and photos on RecyclerView.

**Comment by eneim** [comment]
@AmanChugh want to ask from where you end up using "ExoPlayerViewHolder"? 

You can check this out for using this class:https://github.com/eneim/Toro/releases/tag/2.2.0-SNAPSHOT, but please read it carefully.

**Comment by AmanChugh** [comment]
So Is 2.2.0 is beta version?

**Comment by eneim** [comment]
Yes, if you want to use "ExoPlayerViewHolder". Otherwise you should use current "ExoVideoViewHolder" instead.

**Comment by AmanChugh** [comment]
ok thanks :)
