### ISSUE TITLE
How to get and set Video Volume in ExoPlayer

### ISSUE THREAD

**Issue by AmanChugh** [eneim/Toro#169]
How to get current Volume status of ExoVideoPlay and set Current Volume of device to ExoVideoPlayer

**Comment by developerGM** [comment]
You can use `videoView.setVolume(float);`

**Comment by eneim** [comment]
@AmanChugh The setter is as the second comment, while the getter is not public right now. If you are using ExoPlayerView (new Widget in 2.2.0) you can have it by the following call:

```java
float volume = playerView.getPlayer().getVolume();
```

Note that getPlayer() can returns Null if your view has not been prepared.
