### ISSUE TITLE
Toro.pause and Toro.resume

### ISSUE THREAD

**Issue by developerGM** [eneim/Toro#173]
Hi, using the new method:
```
Toro.pause()
Toro.resume()
```
I can't pause and resume my RecyclerView to play video...
In the 2.1.0 Toro version, using `Toro.rest(boolean);` all works fine

And if I set 
```
@Override
protected void onResume() {
   super.onResume();
   Toro.register(mRecyclerView)
}
```
I have this error:
`java.lang.RuntimeException: Adapter must be a PlayerManager`

**Comment by RockyLin** [comment]
@developerGM 

As the error said, your recyclerview's adapter is not implement interface **PlayerManager**.

**Comment by eneim** [comment]
@RockyLin Thanks. @developerGM Please refer to Changelog for 2.2.0, it has some big changes that you may need to know. Thanks for using Toro. I will take a look at pause and resume, internally it calls ```Toro.rest``` so I am surprised it doesn't work.

**Comment by developerGM** [comment]
@RockyLin @eneim 
Ok thanks, now I am using 2.2.0 and BaseAdapter (so this implements PlayerManager internally)
Now `Toro.pause()` and `Toro.resume()` works properly.
The problem is, using 2.2.0, when scroll down and than come up again, the player never play again but go to immediatly in `pause()`.

**Comment by eneim** [comment]
Never happens to me. Reopen this if 2.3.0 doesn't serve you.
