### ISSUE TITLE
How to load the video based in connectivity type

### ISSUE THREAD

**Issue by giovaniguerra** [eneim/Toro#178]
- [ ] Toro dependencies (compile "im.ene.toro2:toro-ext-mediaplayer:${toroVersion}")
                                       compile "im.ene.toro2:toro-extended:${toroVersion}"`)
toroVersion = 2.2.0

Hello, I have two questions about toro.
First one...
I'm trying to prevent the user from download the video if his internet is a mobile type (2G,3G,4G...), I want to use autoplay only if his internet is a wifi type. How I can achieve this? 
I try to override @preparePlayer in my ViewHolder like this:

```java
@Override
    public void preparePlayer(final boolean playWhenReady) {
        ConnectivityManager cm = (ConnectivityManager) ctx.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo activeNetwork = cm.getActiveNetworkInfo();
        if (activeNetwork != null) { // connected to the internet
            if (activeNetwork.getType() == ConnectivityManager.TYPE_WIFI) {
                // connected to wifi
                buttonPlay.setVisibility(View.GONE);
                super.preparePlayer(playWhenReady);
            } else if (activeNetwork.getType() == ConnectivityManager.TYPE_MOBILE) {
                // connected to the mobile provider's data plan
                buttonPlay.setVisibility(View.VISIBLE);
                buttonPlay.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        // download and play the video
                    }
                });
            }
        }
    }
```
The buttonPlay is a custom ImageButton that I want to show in front of the video (just like facebook does)
I'm not using facebook videos, I use some videos from my server.

Second..

If I use the playbackListener I can know when the video has ended, but I also need to know something like this: "User watched video for 20 seconds (duration is 60s)". So I can know how much he watched. What method should I override to get this information?

**Comment by eneim** [comment]
To start preparing the Video base on your connectivity state, you can create custom ToroStrategy to control when you player can play.

The second one: you can always call player.getCurrentPosition().
