### ISSUE TITLE
Change default black background ExoPlayerView

### ISSUE THREAD

**Issue by giovaniguerra** [eneim/Toro#180]
Hi!

I'm using the newer version 2.2.0. ("im.ene.toro2:toro-extended:2.2.0")...

How can I change the default black color ExoPlayerView uses before the player starts to play? I tried to change the background attr in xml but didn't work.

**Comment by eneim** [comment]
@giovaniguerra I use SimpleExoPlayerView internally, so this background is actually its setup. You should go to ExoPlayer repo for this request. Cheer!

**Comment by giovaniguerra** [comment]
@eneim Thanks!!! The solution was override the xml file (exo_simple_player_view.xml) and change the background color of shutter view. It's described in comments of SimpleExoPlayerView file in ExoPlayer repo.
