### ISSUE TITLE
cannot implement custom view no clear documentation

### ISSUE THREAD

**Issue by dayanithi06** [eneim/Toro#181]
cannot make custom view for eg: in recycler view holder.textview and here i cannot call like this . in this i can implement video only

**Comment by eneim** [comment]
@dayanithi06 ViewHolder implementation is a part of original RecyclerView, please refer it else where. You only need to implement ToroPlayer or extend pre-define BaseViewHolder to get support from Toro.

**Comment by eneim** [comment]
If you want to call field of ViewHolder like ```holder.mTextView``` then you need to have a public field of ```mTextView```, this is normal java constraint and not a part of Toro.

**Comment by dayanithi06** [comment]
Thank you @eneim  But if you make a documentation it will be useful
