### ISSUE TITLE
UI Bug: Exoplayer in recyclerview leaves black block while scrolling up forward in Android 7.1.1

### ISSUE THREAD

**Issue by RockyLin** [eneim/Toro#182]
Toro:2.1
Device: Nexus 5x, OS: Android 7.1.1, not rooted

Bug description: If you scroll the recyclerview  up forward while exoplayer is playing, chances are great that you may see exoplayer leaves a black block on the top over the status bar. If the exoplayer is not playing, scrolling the recyclerview won't cause such a bug.

Solution:in ExoVideoView.java, use TextureView instead of SurfaceView.

**Comment by RockyLin** [comment]
It seems that only happens in my project. The sample project works fine.

**Comment by creativecoderbee** [comment]
i have same issue

**Comment by eneim** [comment]
@creativecoderbee Hi, can you provide me more information about version you used, media Url to reproduce the issue and a screen record of what happened?

**Comment by creativecoderbee** [comment]
`implementation 'im.ene.toro3:toro:3.6.1.2802'
  implementation 'im.ene.toro3:toro-ext-exoplayer:3.6.1.2802'`

Am using above version, and issues shows only on height large videos.
