### ISSUE TITLE
Extended getNextTarget not called, no looping done

### ISSUE THREAD

**Issue by crackTheCode** [eneim/Toro#183]
I cannot get video loop work properly, when the video ends it goes to a black screen, I checked the sample end it doesn't loop either

I am using compile "im.ene.toro2:toro-extended:2.2.0"

I run it on OnePlus One API 25 and to emuator api 23 also.

**Comment by crackTheCode** [comment]
@eneim I imported as a module to do some debugging and I noticed that ExtPlayerViewHelper.onPlayerStateChanged is called when the video ends with playbackState == ExoPlayer.STATE_ENDED and playWhenReady == true so it doesn't enter to if statement block

**Comment by eneim** [comment]
@crackTheCode I see, thanks for the report. I will take a look on that soon.

**Comment by jpage4500** [comment]
I also noticed video's aren't looping. I verified this in the sample app - basic sample 3.. after the video finishes it stops and doesn't restart.

When debugging this in my app, getNextTarget() was called and I returned `Target.THIS_PLAYER` but I didn't see anything else in the log (including from Toro)

```
 onPlaybackStarted:
 onPlaybackCompleted:
 getNextTarget: 
```

**Comment by jpage4500** [comment]
I stepped through what's happening and here's what I noticed.

In ExtPlayerViewHelper `manager.startPlayback();` is called:
```
        case THIS_PLAYER:
          // immediately repeat
          if (manager != null) {
            manager.restorePlaybackState(player.getMediaId());
            manager.startPlayback();
          }
```

Then, in PlayerManagerImpl `player` is null
```
  @Override public void startPlayback() {
    if (player != null) {
      player.start();
    }
  }
```

**Comment by jpage4500** [comment]
could this be the issue?

https://github.com/eneim/Toro/commit/decd7a5594a43f4e265df74c2af62780d20332ac#diff-61ccaf5ee8c292d3f874ee08a2df9d30

**Comment by eneim** [comment]
Oh, maybe. Let me take a look at it.

**Comment by eneim** [comment]
@jpage4500 @crackTheCode Please try latest 2.2.1-SNAPSHOT to see if this has been fixed. Thanks.

**Comment by crackTheCode** [comment]
@eneim how to import it? 
compile "im.ene.toro2:toro-extended:2.2.1-SNAPSHOT"

doesn't work

**Comment by eneim** [comment]
@crackTheCode Do you have the snapshot repository in your gradle file?

**Comment by crackTheCode** [comment]
@eneim no I don't think so. How can I do it which is the repo

**Comment by eneim** [comment]
@crackTheCode You cannot get the SNAPSHOT or the latest SNAPSHOT doesn't work? :-s

**Comment by jpage4500** [comment]
>> Do you have the snapshot repository in your gradle file?

What's the snapshot repo URL? I don't think I have or know what this is - just have jcenter and mavenrepo. Are you using jitpack.io for pre-release builds?

**Comment by eneim** [comment]
@jpage4500 @crackTheCode Sorry, FYI 

```
maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
```

Put this into root build.gradle, inside 

```
allprojects {
}
```

block.

**Comment by crackTheCode** [comment]
@eneim I did it and I got the SNAPSHOT code but it doesn't work in my project? Your demo works?

**Comment by eneim** [comment]
@crackTheCode Let me double check.

**Comment by rajanbhavsar001** [comment]
I also had the same issue.

**Comment by eneim** [comment]
I figured out the issue. The player will release on every completion. Will come up with a fix soon.

**Comment by m7yank** [comment]
Is there any other way we can play video in loop ?

**Comment by eneim** [comment]
@m7yank let see if 2.3.0 helps you. Already on jcenter.
