### ISSUE TITLE
a Simple bug

### ISSUE THREAD

**Issue by bingbing720** [eneim/Toro#184]
Make sure to provide the following informations and check:

- [ ] Toro dependencies (Eg: ```com.github.eneim:Toro:develop-SNAPSHOT```)

- [ ] Android manifacture | product name | OS Version | rooted or clean (Eg: Sony | Z4 | 5.0 | clean)

- Logcat (if it was a fatal issue)

**Comment by bingbing720** [comment]
Good morning.
Thank you for your great code.
I want to tell you one your spelling bug on your document.
I am sorry for my bad english.
![capture](https://cloud.githubusercontent.com/assets/19614418/24592052/ee2ac3f4-1841-11e7-8276-cda002518ca0.PNG)

**Comment by eneim** [comment]
@bingbing720 Ah, thanks for pointing it out. I'll take a look on it asap.

**Comment by eneim** [comment]
Fixed in 2.3.0
