### ISSUE TITLE
Showing black video screen while scrolling.

### ISSUE THREAD

**Issue by krupalagile** [eneim/Toro#185]
Showing black screen while scrolling and until playback is not ready. It is also present in the sample. How to avoid showing that? I need to show some image thumb while video is not loaded.
Make sure to provide the following information and check:
- [x] Toro dependencies (Eg: ```com.github.eneim:Toro:develop-SNAPSHOT```)

- [x] Samsung | Galaxy S5 | Android 5.0 | Clean
- Logcat (if it was a fatal issue)

**Comment by eneim** [comment]
@krupalagile You didn't provide enough info. You can also put an imageview on top of your VideoView, show it while loading and hide it while playing.

**Comment by krupalagile** [comment]
But how can I get the state of loading and playing?
