### ISSUE TITLE
Play streaming video from local storage

### ISSUE THREAD

**Issue by cubatertech** [eneim/Toro#187]
Hi dear.

I want to play much faster videos in recycler view.
An idea come in my mind that a video is stream competed once then next time not again stream play from local storage. How it is possible please give me some tips. Thanks

**Comment by jpage4500** [comment]
I've been using https://github.com/danikula/AndroidVideoCache and it's worked pretty well

**Comment by cubatertech** [comment]
Great Thanks. I use https://github.com/danikula/AndroidVideoCache getting cool results.
