### ISSUE TITLE
Update methods count badges in README

### ISSUE THREAD

**Issue by mradzinski** [eneim/Toro#199]
Your badges are pretty old. Last method count reported 11319 lines of code just for Toro-core. The real count for the ExoPlayer 2 version (which as per your blog entry is the one you are actively developing) is of 17112 lines and 2383 Kb. All this information might be a show stopper for people who cares about library size and specially methods count given Android methods limit (which Toro will consume by around a 30%).

http://www.methodscount.com/?lib=im.ene.toro2%3Atoro%3A2.2.0
http://www.methodscount.com/?lib=im.ene.toro2%3Atoro-ext-exoplayer2%3A2.2.0

**Comment by eneim** [comment]
@mradzinski done :D.
