### ISSUE TITLE
Any callbacks for knowing when an item in Recyclerview is active

### ISSUE THREAD

**Issue by gouravd** [eneim/Toro#20]
Sorry if the answer is obvious as I just started testing this library today. 

I am working with a fullscreen horizontal scrolling recyclerview where only 1 item is visible at any time. It can only be scrolled in one direction (from right to left). I would like to do few operations on items that have been scrolled past (i.e scrolled outside the visible area, like update db that it has been viewed, or delete from db, add analytics for the view etc..).

I was wondering if I could any of the TORO methods/helpers or if there are any callbacks which I can use to do the operations once the items are invisible after being visible.

**Comment by eneim** [comment]
For lightweight operations, Base ViewHolder has [onAttachedToParent](https://github.com/eneim/Toro/blob/develop/toro/src/main/java/im/ene/lab/toro/ToroAdapter.java#L82) and [onDetachedFromParent](https://github.com/eneim/Toro/blob/develop/toro/src/main/java/im/ene/lab/toro/ToroAdapter.java#L89) Which respectively response to [Adapter#onViewAttachedToWindow(ViewHolder)](https://github.com/eneim/Toro/blob/develop/toro/src/main/java/im/ene/lab/toro/ToroAdapter.java#L38) and [Adapter#onViewDetachedFromWindow(ViewHolder)](https://github.com/eneim/Toro/blob/develop/toro/src/main/java/im/ene/lab/toro/ToroAdapter.java#L42). I think you can start from there to see if it suffice your process. Adapter's methods are called by Android system (the RecyclerView), ViewHolder's methods are my custom ones, called by its Adapter to connect it with the RecyclerView.

**Comment by gouravd** [comment]
Thanks for the suggestion. I tried it but they are not reliable for my use case. What I think would suit best is to provide a method in Toro (that we can override), that is called when the any item becomes active and/or inactive.

Currently I am planning to use ListView-Visibility-Utils from danylovolokh/VideoPlayerManager which provides the methods that I would need. But if simillar calbacks are available in Toro, I can get rid of that extra library.

**Comment by eneim** [comment]
What do you mean by active/inactive ? The video is playing = active or the view holder is 100% visible = active (then 95% visible is considered inactive).
