### ISSUE TITLE
toro looping issues

### ISSUE THREAD

**Issue by harikautilya** [eneim/Toro#209]
I have been try to loop my video playing in the toro player .
The structure i used is :
viewpager->frag1=>recyclerview loads 20 videos
                ->frag2=>recyclerview loads 20 videos
now the issue is one i was able to loop videos by calling onplaybackcompleted override and add seektoposition(0)
This raised issues like when i move from one fragment to another it doesnt cause a problem if the video plays
Now let me say the video has looped ....now when i move from one fragment to another the playback doesn't stop i was able to identy by going into the inner loop and found this
  if (manager.getPlayer() != null) 
which is returns null if the video is looped atleast once

compile "im.ene.toro2:toro-ext-exoplayer2:2.3.9"

**Comment by harikautilya** [comment]
i found out that u are setting the manager.setplayer(null) on playback completion  
but how can I avoid this?

**Comment by eneim** [comment]
Sorry, Toro currently doesn't play well with ViewPager ... You might want to manually control which RecyclewView / Fragment you want to focus, and disable the rest.

**Comment by harikautilya** [comment]
no i think fragment system is fine but after completion the player is being set to null only if we can avoid this the fragment system will work fine. 
any suggestion on how to do this?

**Comment by eneim** [comment]
@harikautilya If you are using the exoplayer 2 extension you can simply avoid this by using LoopMediaSource to wrap your original MediaSource. It works well with my library ... (using this will not trigger the complete event until you manually stop the player)

**Comment by harikautilya** [comment]
@eneim can u show me related file?

**Comment by harikautilya** [comment]
Currently i am using ExoPlayerViewHolder

**Comment by harikautilya** [comment]
`return new LoopingMediaSource(ExoPlayerHelper.buildMediaSource(itemView.getContext(),
                Uri.parse(videoThumbUrl),
                new DefaultDataSourceFactory(itemView.getContext(),
                        Util.getUserAgent(itemView.getContext(), "song")),
                itemView.getHandler(), null), 1);
`
this is my get media source

**Comment by harikautilya** [comment]
got it worked like a charm thanks

**Comment by eneim** [comment]
@harikautilya good to hear. I will improve this in next major release. But using LoopingMediaSource will be a good solution since I want to use ExoPlayer2 as main playback backend.

**Comment by harikautilya** [comment]
yes the issue i had is the put the loop count to 1 
when i put it Integer.MAX_VALUE - 1 it worked fine
