### ISSUE TITLE
Support for autoplay and loop Audio

### ISSUE THREAD

**Issue by gouravd** [eneim/Toro#21]
I guess adding support for Audio would be not very difficult by extending current framework. Is it something that can be accomodated in 1.2.0?

Bonus points for adding Visualization for Audio. :+1:

**Comment by eneim** [comment]
You mean ***only*** Audio? Like playing general music from your sdcard?. That is not considered now. Please keep in mind that Audio playback (no Surface) is totally different to Video playback (requires Surface).

**Comment by gouravd** [comment]
Right, but can we not use the same logic for audio. It should be easier as it does not require any surface, just requires MediaPlayer.

What I am doing currently is 
1) Extending ToroVideoViewHolder, but not setting the videoview any url in the OnBind.
2) Extending wantsToPlay and setting MediaPlayer url for the audio. This way the audio starts playing according to the proper strategy.

But I am unable to figure out how to stop the audio when the item becomes invisible. Can you suggest some ideas

**Comment by eneim** [comment]
You can have that from onDetachedFromParent callback. Let's give it a try.

**Comment by gouravd** [comment]
Yes, it works. Thanks
