### ISSUE TITLE
Is there a way to know how many time video looped?

### ISSUE THREAD

**Issue by rishabhcha** [eneim/toro#214]
Hello, my requirement is to count how many time video is viewed. As l'm looping video, so the function : **`onPlaybackCompleted()`** is never called. So, is there any way to know how many times video is watched by user, or can i get that user has watched the complete video at least once?  
Any clue or help please. Thank you.

**Comment by eneim** [comment]
@rishabhcha Hoping that you are using LoopingMediaSource, there is a callback for the loop count. Please refer to this document: https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/LoopingMediaSource.html

**Comment by rishabhcha** [comment]
Okay got the solution, thank you very much!!
