### ISSUE TITLE
im.ene.toro3 android native code

### ISSUE THREAD

**Issue by davisoqt** [eneim/toro#217]
Could you publish an example of version 3.0.0 alpha1 using native android code and not kotlin? I would like to test the functionality of playback several videos in a GridLayoutManger. Thanks..

**Comment by eneim** [comment]
Hi @davisoqt , I have put a few code in the App module, for example this [SimpleExoPlayerViewHolder.java](/app/src/main/java/im/ene/toro/sample/common/SimpleExoPlayerViewHolder.java). Can you take a look.

**Comment by davisoqt** [comment]
Is there any way to playback 2 videos that are within the same viewholder? Thanks..

**Comment by eneim** [comment]
I'm affraid it is not possible by now. You may want to have 2 ViewHolders for that, or you wrap them by a ViewGroup and then "tell lie" to the Container that it is your player view, and have a special setup for your Videos. I cannot provide a certain solution but please try it.

**Comment by eneim** [comment]
@davisoqt latest doc is using Java instead of Kotlin.
