### ISSUE TITLE
Error:Could not get unknown property 'bintray_user' for object of type com.novoda.gradle.release.PublishExtension

### ISSUE THREAD

**Issue by Sandeeppal1083** [eneim/toro#220]
When i am trying to build this project I am getting following error , Please help me in this:
Error:Could not get unknown property 'bintray_user' for object of type com.novoda.gradle.release.PublishExtension.

**Comment by MaheshK224** [comment]
will you please post answer to this error.(I am getting error while setup the project)

**Comment by kslim1025** [comment]
bintrayuser =""
bintraykey=""
