### ISSUE TITLE
Loop Video in toro v3

### ISSUE THREAD

**Issue by davisoqt** [eneim/toro#224]
How can I make the video play again once it is finished? Is available some function like 
@Override 
public Target getNextTarget () {
     Return Target.THIS_PLAYER;
   }
  Available in version 2.3.0? I'm using SimpleExoPlayerViewHolder.java

**Comment by eneim** [comment]
@davisoqt v3 will closely tight to ExoPlayer 2, you can use its official LoopingMediaSource for loop playback.
