### ISSUE TITLE
Error: Could not get unknown property 'bintray_user' for object of type com.novoda.gradle.release.PublishExtension.

### ISSUE THREAD

**Issue by DroidVent** [eneim/toro#233]
When i imported project it gives following error:
Error:Could not get unknown property 'bintray_user' for object of type com.novoda.gradle.release.PublishExtension.

**Comment by eneim** [comment]
@DroidVent please make sure after you cloned the project, you rename "gradle.properties-sample" to "gradle.properties". See the "contribution" section in readme for more information.

**Comment by DroidVent** [comment]
@eneim I renamed the file as you told but now error is changed as follows:

**Comment by eneim** [comment]
@DroidVent sorry that means you should dev it on Android Studio 3 (currently I'm using 3 alpha 6 to have support for Android O). If you want to contribute there is no other way, so sorry.

**Comment by eneim** [comment]
@DroidVent Or other wise: manually change the gradle plugin to 2.3.3 and try again ...

**Comment by bperin** [comment]
you can set

`bintrayUser = ""
  bintrayKey = ""`

as a workaround

**Comment by arthurmelo88** [comment]
> you can set
> bintrayUser = "" bintrayKey = ""
> as a workaround @bperin 
this worked for me ;)

**Comment by Parag09** [comment]
that worked for me too 
thanks you very much
