### ISSUE TITLE
Video do not auto play inside Viewpager with getChildFragmentManager()

### ISSUE THREAD

**Issue by toidv** [eneim/toro#235]
I'm using toroVersion = '3.0.0-beta1' with Android Studio 3.0 Canary 8. But the first fragment inside viewpager doesn't play automatically

1. im.ene.toro.widget.Container inside Viewpager with childFragmentManger
```
       VideoPagerAdapter adapter = new VideoPagerAdapter(getChildFragmentManager());
        for (VideoCategory category : categories) {
            adapter.addCategory(category);
        }
        viewPager.setAdapter(adapter);
        tlVideo.setupWithViewPager(viewPager);
```
2.  Setup each fragment item like this
```
@Override
public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    layoutManager = new LinearLayoutManager(getContext());
    adapter = new VideoAdapter();
    container.setLayoutManager(layoutManager);
    container.setAdapter(adapter);
    container.setCacheManager(adapter);
    container.addOnScrollListener(new EndlessRecyclerOnScrollListener(layoutManager) {
        @Override
        public void onLoadMore(int current_page) {
            getVideos();
        }
    });
    container.setPlayerSelector(null);
    handler.postDelayed(() -> {
        if (container != null) container.setPlayerSelector(selector);
    }, 200);

}
```

Handle in `setUserVisibleHint`
```
@Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        Timber.e("isVisibleToUser: " + isVisibleToUser);
        Timber.e("categoryId: " + categoryId);
        if (isVisibleToUser) {
            selector = PlayerSelector.DEFAULT;
        } else {
            selector = PlayerSelector.NONE;
        }
        handler.postDelayed(() -> {
            if (container != null) container.setPlayerSelector(selector);
        }, 200);
    }

```

The first screen video doesn't auto play. 

Please help to investigate. Thank you!

**Comment by eneim** [comment]
@toidv thanks. Can you show me a snapshot of how your "VideoCategory" looks like. Let me take a look overall first.

**Comment by toidv** [comment]
It is snapshot of `VideoCategory` @eneim 
```
public class VideoCategory extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("name")
    @Expose
    private String name;

    public VideoCategory() {

    }

    public VideoCategory(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```

**Comment by toidv** [comment]
Currently, The problem happened due to parent fragment did not dispatch `setUserVisibleHint` to child fragment in case of nested fragment inside `Viewpager` with `getChildFragmentManager`
My solution is
1. `setUserVisibleHint(false` on onCreate of fragment (default it is true)
```
@Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setUserVisibleHint(false);
    }
```
2. Create a method to dispatch `setUserVisibleHint` in ViewPagerAdapter
```
public class VideoPagerAdapter extends FragmentStatePagerAdapter {
    private final List<VideoCategory> categories = new ArrayList<>();
    private Fragment primary;

    public VideoPagerAdapter(FragmentManager fm) {
        super(fm);
    }

    @Override
    public void setPrimaryItem(ViewGroup container, int position, Object object) {
        super.setPrimaryItem(container, position, object);
        if (object instanceof Fragment) {
            primary = (Fragment) object;
        }
    }

    public void setUserVisibleHint(boolean isVisible) {
        if (primary != null){
            primary.setUserVisibleHint(isVisible);
        }
    }
}
```
3. Dispatch setVisibleHint to child fragment 
```
 @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        if (adapter != null) adapter.setUserVisibleHint(isVisibleToUser);
    }
```

4. Inside child fragment do as your solution

```
@Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        if (isVisibleToUser) {
            selector = PlayerSelector.DEFAULT;
        } else {
            selector = PlayerSelector.NONE;
        }
        handler.postDelayed(() -> {
            if (container != null) container.setPlayerSelector(selector);
        }, 200);

    }
```

Thank you!

**Comment by eneim** [comment]
@toidv this is interesting. My example uses the ViewPager directly in Activity. Let me investigate more on this behaviour. But it sounds great you have found a working solution.

**Comment by eneim** [comment]
@toidv I create a sample project and can see that it is calling setUserVisibleHint. I wonder how you can reproduce your issue ...

**Comment by toidv** [comment]
In my application, I have a menu (Tablayout) and each menu item has a sub menu by itself @eneim. For example
|NEW|-|Video|-|Board|
 		||  
|NEW|-|HOT|-|FITNESS|-|HAIR MAKE|

**Comment by eneim** [comment]
@toidv I see, so a big ViewPager whose each Page (which is a Fragment) is having another ViewPager right?

**Comment by toidv** [comment]
Yes, it is @eneim

**Comment by eneim** [comment]
@toidv I can reproduce your issue now. While I agree with your workaround, I have one comment: since ```setUserVisibleHint``` call doesn't follow the lifecycle, you should also check the case your Adapter is null and then update its when you create your Adapter. In detail: at launch, your ViewPager's second Fragment (call it Fragment1) will have userVisibility as ```false```, while its own ViewPager will have its first Fragment's userVisibility as ```true```. Fragment1 will call ```setUserVisibleHint``` before your Adapter is available --> Fragment1's first item in ViewPager will have.

Also calling "setUserVisibleHint(false);" from onCreate doesn't make sense to me. This method should not be bound to a lifecycle event, since it can be called randomly by system. (For instance: new Fragment in ViewPager will call the method before its onCreate, and that Fragment's ViewPager is setup after onCreate, you will not be able to pass the setUserVisibleHint call down to its Child). Also if you go back from a config changes, your ViewPager/Adapter will restore the primaryItem from ```onViewStateRestored``` and so on ... It may work, but I'm not sure it is bullet proof solution.

I'm creating a sample that mimic this and figure out a safe way to go for this.

**Comment by eneim** [comment]
@toidv I also push a new demo along with release 3.0.0, please take a look :D.

**Comment by toidv** [comment]
@eneim : Thank for your great support. Currently, I discover one more problem, for example. we have 5 Tablayouts: `|NEW|HOT|FITNESS|HAIR MARKE|MAKE UP|`  currently `NEW` is selected then user click to `MAKE UP` so `setUserVisibleHint` doesn't work correctly `isVisibleToUser` is false. To make it works, we have to add to parent fragment logic as below
```
vpVideo.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                if (adapter != null) adapter.setUserVisibleHint(isVisible());
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });
```

**Comment by eneim** [comment]
@toidv I think everytime you switch page, the "setUserVisibleHint" is called, but it is not following life cycle. I wonder if your problem is "setUserVisibleHint" is not called? or it is called at the wrong timing?

**Comment by MayankSoni** [comment]
Hello friends. I am facing same problem. here first video play successfully but next video not play what should i do ? please help me.
