### ISSUE TITLE
 I noticed that when I fling to the top or the bottom of the recycler the video that is visible prepares but doesn't start playback.

### ISSUE THREAD

**Issue by m7yank** [eneim/toro#238]

**Comment by eneim** [comment]
Hi, can you give more information? Which version you used, how your code looks like? Android version, Device type, Video source, etc.

**Comment by m7yank** [comment]
I mean when Video is partially visible on the screen, it is in preparing state (It show me in Log), But not played. 
untill it fully visible after scrolled.

**Comment by eneim** [comment]
Any idea when it finish preparing? If you video cannot be prepared I can't help. Also please tell me which toro version you are using.
