### ISSUE TITLE
Play youtube video

### ISSUE THREAD

**Issue by toidv** [eneim/toro#239]
Is it possible to play the video from youtube URL? For example `https://www.youtube.com/watch?v=XRVIk3josHI&feature=youtu.be`. I'm checking Youtube Player API but it seems we can't have multiple players in recycledview. It would be great if toro could support this feature?

**Comment by eneim** [comment]
I can give a suggestion on how to implement, but cannot provide first party support. The idea is to use the player API's fragment and attach/detach it dynamically.

**Comment by toidv** [comment]
Currently, I using YouTubeThumbnailView to load the thumbnail to display as the place holder, each time user clicks on the thumbnail, we use a fragment/activity to display player. What do you mean about use player API's fragment attach/detach dynamically? Is it same with my approach?

**Comment by eneim** [comment]
@toidv to make it able to play Youtube Video in list, you need to use its Fragment instead of ThumbnailView from what I have tried ... I will make an example to demonstrate *how I did it* in few days (sorry pretty busy at the moment).

**Comment by toidv** [comment]
Thank you, waiting for the exciting thing

**Comment by eneim** [comment]
@toidv I pushed a new module to dev-v3 branch. Take a look at **app-youtube** module (it must be in separated module to prevent 65K method issues in main sample and reduce build time, also I'm not officially support Youtube so this is for your information only). Make sure to provide your own youtube_apikey (see gradle.properties-sample for a reference, rename it to ``gradle.properties`` and put your key there before building the project).

**Comment by toidv** [comment]
Thank you, @eneim  it looks great! but it pauses right after play ~1 second. I'm investing now

**Comment by eneim** [comment]
@toidv Please get logcat information if possible. FYI It works well on my Nexus 5X, maybe something related to Device, platform, etc ...

**Comment by eneim** [comment]
@toidv Any luck with latest sample? Can I close this issue for now?
