### ISSUE TITLE
Video looping

### ISSUE THREAD

**Issue by lumyus** [eneim/toro#244]
Apparently there is no more looping for videos supported in the newest version 3.0.0.
Are there any plans in bringing it back?

Cheers

**Comment by eneim** [comment]
@lumyus If you are using toro 3 and ExoPlayer then using LoopingMediaSource is the way to go. There is an example for it: [here](https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/custom/CustomExoPlayerViewHolder.java#L38)
