### ISSUE TITLE
Video not playing with RecyclerView

### ISSUE THREAD

**Issue by jemshit** [eneim/toro#248]
Hi, i have a classic `Activity` and `RecyclerView` inside it to populate list. Now i am trying to add Toro Video Player into my custom `ViewHolder`. I have written same code for ViewHolder as [this](https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/basic/BasicPlayerViewHolder.java) and for[ xml](https://github.com/eneim/toro/blob/dev-v3/app/src/main/res/layout/view_holder_exoplayer_basic.xml). I have tried both local video Uri and remote Url with `Uri.parse("...")` but videos are not playing, it is just black. I have only changed ViewHolder and xml as in example, nothing else. Do i have to do something more to make video play?

Target Sdk 25
Support Library 25.3.1
ExoPlayer r2.5.1 (core, ui, dash, hls, smooth-streaming)
Toro: 3.0.0

**Comment by eneim** [comment]
@jemshit Do you have any logcat that sounds to be telling you something wrong? Can you try to clone my project, run the demo and see if it could play or not?

**Comment by jemshit** [comment]
Example apps need AS 3 i guess, could not run them on 2.3.3

**Comment by eneim** [comment]
@jemshit Ah Ok. First please help by information from logcat if there is any suspiciously. Also, ExoPlayer 2.5.1 has some changes internally, so I suggest you to test with 2.4.x too if possible.

**Comment by jemshit** [comment]
Nothing on logcat, nothing. I Log inside ViewHolder class (ToroPlayer interface methods), non of them are being called. Let me try changing expolayer version

**Comment by eneim** [comment]
Ok. That sounds pretty weird to me. But please try it first.

**Comment by jemshit** [comment]
Here is [sample project](https://github.com/jemshit/ToroSample) with my configurations.

**Comment by eneim** [comment]
@jemshit Hmm just found the problem. You need to use **Container** in place of RecyclerView. Because it is where my logic works :).

**Comment by jemshit** [comment]
Works now. I'll return if i have other issues :)
