### ISSUE TITLE
How to display images and videos like Instagram 

### ISSUE THREAD

**Issue by jeremy-jamez** [eneim/toro#252]
I'm trying to achieve a list of videos and photos which are retrieved from `Firebase` using `FirebaseRecyclerAdapter`. It should operate like Instagram, where you scroll and when a video comes into view, it plays and the user can interact with it and when they continue scrolling the video should stop and display whatever is next in the list, whether photo or video.
I've searched everywhere for this type of implementation but all the ones I've found only deals with videos.
Can this library be used to achieve what I'm looking for?

**Comment by eneim** [comment]
Hi @jeremy-jamez what you want is exactly what toro does for you, please give it a shot and tell me what you feel. If it doesn't feel right for you just get back here and we will talk about that.

**Comment by jeremy-jamez** [comment]
I've tried it out but the images and videos don't load.
Here is my implementation.

**PostsRecyclerAdapter:**
```
postsRecyclerAdapter = new FirebaseRecyclerAdapter<Posts, PostsViewHolder>(
                Posts.class,
                R.layout.feed_item,
                PostsViewHolder.class,
                postsQuery
        ) {

            @Override
            protected void populateViewHolder(PostsViewHolder viewHolder, Posts model, int position) {
                final DatabaseReference postRef = getRef(position);

                viewHolder.bind(model.post_img);
            }
        };
        recyclerView.setAdapter(postsRecyclerAdapter);
```

**PostsViewHolder:**
```
public class PostsViewHolder extends RecyclerView.ViewHolder implements ToroPlayer {

    SimpleExoPlayerViewHelper helper;
    Uri mediaUri;

    SimpleExoPlayerView playerView;


    public PostsViewHolder(View itemView) {
        super(itemView);
        playerView = (SimpleExoPlayerView) itemView.findViewById(R.id.player);
    }

    @NonNull
    @Override
    public View getPlayerView() {
        return playerView;
    }

    @NonNull
    @Override
    public PlaybackInfo getCurrentPlaybackInfo() {
        return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
    }

    @Override
    public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
        if (helper == null) {
            helper = new SimpleExoPlayerViewHelper(container, this, mediaUri);
        }
        helper.initialize(playbackInfo);
    }

    @Override
    public void play() {
        if (helper != null) helper.play();
    }

    @Override
    public void pause() {
        if (helper != null) helper.pause();
    }

    @Override
    public boolean isPlaying() {
        return helper != null && helper.isPlaying();
    }

    @Override
    public void release() {
        if (helper != null) {
            helper.release();
            helper = null;
        }
    }

    @Override
    public boolean wantsToPlay() {
        return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
    }

    @Override
    public int getPlayerOrder() {
        return getAdapterPosition();
    }

    @Override
    public void onContainerScrollStateChange(Container container, int newState) {

    }

    @Override public String toString() {
        return "ExoPlayer{" + hashCode() + " " + getAdapterPosition() + "}";
    }

    void bind(String media){
        Log.d("PostsViewHolder", "Media: " + media);
        this.mediaUri = Uri.parse(media);
    }
}
```
**FeedListActivity:**
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_feed_list);

        recyclerView = (Container) findViewById(R.id.feedRecyclerView);
        mLayoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(mLayoutManager);

        recyclerView.setItemAnimator(new DefaultItemAnimator());
        recyclerView.setHasFixedSize(true);
    }
```
**feed_item.xml:**
```
<FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.google.android.exoplayer2.ui.SimpleExoPlayerView
                android:id="@+id/player"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:surface_type="texture_view"
                app:resize_mode="fit"
                app:use_controller="false"
                />
        </FrameLayout>
```
There are other views which I've omitted from the above code because they load perfectly, only videos and images are not loaded.

**Comment by thealpha** [comment]
yo bro did you get the answer

**Comment by thealpha** [comment]
did you use this library for video play

**Comment by eneim** [comment]
@thealpha what is your requirement? Toro targets Video playback as first problem to solve. You can custom it to play whatever you want :).

**Comment by jeremy-jamez** [comment]
Yes, works as expected

**Comment by thealpha** [comment]
bro  jeremy-jamez   the video is playing but I can't view both photo and video ....please can you help me ...or show your code please

**Comment by eneim** [comment]
@thealpha Please try 2 ViewHolder types, one for Photo and one for Video

**Comment by thealpha** [comment]
thanks a lot for responding ....eneim ...

**Comment by thealpha** [comment]
bro still struggling your video plays well but I can't use both photo and video ...

**Comment by jeremy-jamez** [comment]
@thealpha could you show your ViewHolder and adapter code

**Comment by eneim** [comment]
@thealpha I suppose you have little experience working with multiple View types in RecyclerView, please refer to this for your app: [Heterogenous Layouts inside RecyclerView](https://guides.codepath.com/android/Heterogenous-Layouts-inside-RecyclerView).

**Comment by sidndis** [comment]
i want to show a thumbnail as video preview until the video is loading or preparing. Once its prepared i want to remove the thumbnail and show the video running. When i scroll up to next video preview should be back over the video. I hope you understand what i am saying. Facebook, Instagram all are following same approach. Can you help me in this ?

**Comment by thealpha** [comment]
use glide for loading video thumbnail...set its path as video uri.....if you still don't understand use my code

**Comment by thealpha** [comment]
`       @Override
        public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
            if (helper == null) {
                helper = new SimpleExoPlayerViewHelper(container, this, mediaUri);
            }
            helper.initialize(playbackInfo);
          //  container.setCacheManager(CacheManager.DEFAULT);
                RequestOptions requestOptions = new RequestOptions()
                        .placeholder(R.color.black);
            Glide.with(mContext)
                    .setDefaultRequestOptions(requestOptions)
                    .load(mediaUri)
                    .into(thumb);
        }

        @Override
        public void play() {
            if (helper != null) helper.play();
            thumb.setVisibility(View.GONE);

        }
`

**Comment by thealpha** [comment]
`    @Override
           public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
            if (helper == null) {
                helper = new SimpleExoPlayerViewHelper(container, this, mediaUri);
            }
            helper.initialize(playbackInfo);
                RequestOptions requestOptions = new RequestOptions()
                        .placeholder(R.color.black);
            Glide.with(mContext)
                    .setDefaultRequestOptions(requestOptions)
                    .load(mediaUri)
                    .into(thumb);
             }

            @Override
            public void play() {
            if (helper != null) helper.play();
            thumb.setVisibility(View.GONE);

            }`

**Comment by VikasChauhanNVC** [comment]
Hey guys,
I'm trying to get data from firebase to multiple recycler view (here I'm using two views of recycler view vertical and horizontal inside the same activity ). But while I'm trying to fetch all data the recycler view activity adapter is called very fastly even data still under the process of fetching due to which there is passing empty ArrayList<>() to the recycler view adapter. And recycler view activity is showing nothing, in other words, it is blank.
So give me any solution so that I can stop code flow until all data isn't fetched to ArrayList which I'm passing into recycler view adapter class.

(NOTE: I had already used Countdowntimer() but there is a problem with it that scope of the return type of method isn't viable inside this method )

**Comment by eneim** [comment]
@VikasChauhanNVC It is not what Toro can help.
