### ISSUE TITLE
RTMP Extension Support

### ISSUE THREAD

**Issue by lumyus** [eneim/toro#253]
Hey @eneim , 

I was wondering if and when you will support RTMP which was recently added in Exoplayer 2.5.

Thanks

**Comment by lumyus** [comment]
I was able to retrieve a stream from an rtmp// url however the app crashes with the following error from time to time:

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 17672 (Loader:Extracto)
02-22 20:05:53.086 509-509/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-22 20:05:53.086 509-509/? A/DEBUG: Build fingerprint: 'google/angler/angler:6.0.1/MMB29Q/2480792:user/release-keys'
02-22 20:05:53.087 509-509/? A/DEBUG: Revision: '0'
02-22 20:05:53.087 509-509/? A/DEBUG: ABI: 'arm64'
02-22 20:05:53.088 509-509/? A/DEBUG: pid: 17056, tid: 17672, name: Loader:Extracto >>> com.exoplayer.videoplayer <<<
02-22 20:05:53.088 509-509/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0`

I believe that there is not the correct Type set up in this code:

```
DataSource.Factory mediaDataSourceFactory = buildDataSourceFactory(transferListener);

    int type =
        Util.inferContentType(isEmpty(extension) ? mediaUri.getLastPathSegment() : "." + extension);
    switch (type) {
      case C.TYPE_SS:
        return new SsMediaSource(mediaUri, buildDataSourceFactory(transferListener),
            new DefaultSsChunkSource.Factory(mediaDataSourceFactory), handler, null);
      case C.TYPE_DASH:
        return new DashMediaSource(mediaUri, buildDataSourceFactory(transferListener),
            new DefaultDashChunkSource.Factory(mediaDataSourceFactory), handler, null);
      case C.TYPE_HLS:
        return new HlsMediaSource(mediaUri, mediaDataSourceFactory, handler, null);
      case C.TYPE_OTHER:
```

I think you should add a RTMP type in here: ` case C.TYPE_OTHER`:.

Here a few resources for the issue:
https://github.com/ant-media/LibRtmp-Client-for-Android/issues/2
https://github.com/google/ExoPlayer/tree/release-v2/extensions/rtmp

**Comment by eneim** [comment]
@lumyus I just release 3.1.0 last week to update ExoPlayer to 2.5.1, can you take a look. Generally I don't touch the player level, so you will get whatever ExoPlayer supports. If you need help on creating custom MediaSource I will have a deep dive into it :D.

**Comment by lumyus** [comment]
@eneim
Thanks man! Yes I already updated to 2.5.1 however there is still some
issue. I get this in the logcat that I posted. Any idea on what might be
the problem?

Keep up the good work

Am 10.09.2017 21:15 schrieb "Nam Nguyen Hoai" <notifications@github.com>:

**Comment by eneim** [comment]
@lumyus Got it. Seems that current helpers doesn't help you to create non-Default DataSource Factory. There is a plan to make my helpers more generic, seems that it is time to speed it up.

**Comment by lumyus** [comment]
@eneim great! Ping me if you need more detailed logcat or when you are done with the more generic helpers. :D

**Comment by eneim** [comment]
@lumyus It turns out that ExoPlayer by default will detect your source if it is RTMP or not, and if you also include the rtmp extension (seems that you did), it will use rtmp as normal. In your case, I guess the cause is closer to the ExoPlayer/rtmp extension. Can you ask for that issue on ExoPlayer repository first? The logcat actually tells something about native code error which maybe the hardware ability to decode your stream.

**Comment by lumyus** [comment]
Acutally the update of the Exoplayer and the extension to 2.5.2 fixed the
issue. Everything is working fine now!
Thanks for the help :)

Am 12.09.2017 06:57 schrieb "Nam Nguyen Hoai" <notifications@github.com>:

**Comment by eneim** [comment]
@lumyus that sounds great!
