### ISSUE TITLE
Support scale video: fitCenter, Centercrop...

### ISSUE THREAD

**Issue by hiennguyen1001** [eneim/toro#254]
Hi @eneim
Currently, Your ExoPlayerHelper class use SimpleExoPlayerView which just allow scale video with: fit_width, fix_height, fill, fit. 
So, I can not scale my video with scale type: fitCenter, Centercrop...
Can you update your library to support a Player View have scale type above. Thank your

**Comment by eneim** [comment]
@hiennguyen1001 Currently I only support SimpleExoPlayerView as it comes from ExoPlayer officially. To support more ability, either you create your own widget or you request ExoPlayer team for that. Creating one is not in my plan sadly. I suggest you to refer to the code made by SimpleExoPlayerView and create your own version.
