### ISSUE TITLE
[Question] how to mute on version 3.1 

### ISSUE THREAD

**Issue by thanhbinh84** [eneim/toro#257]
Hi @eneim, 

I am using version 3.1, I searched in sample project but didn't found the way to mute.

`MyViewHolder extends RecyclerView.ViewHolder implements ToroPlayer`

` @Override
    public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
        if (!URLUtil.isValidUrl(mVideoUrl)) return;
        if (helper == null) {
            helper = new LoopingExoPlayerViewHelper(container, this, Uri.parse(mVideoUrl));
        }
        helper.initialize(playbackInfo);
    }`

Please advise. Thanks

**Comment by eneim** [comment]
@thanhbinh84 if you are using SimpleExoPlayerView then after you setup, you can call ```playerView.getPlayer().setVolume(0.0);``` to mute. You can check null for safety of course.

**Comment by thanhbinh84** [comment]
Perfect. Thanks a lot.
