### ISSUE TITLE
Auto Playing not work when Container inside of NestedScrollView 

### ISSUE THREAD

**Issue by Anilugale** [eneim/toro#258]
What kind of issue is this?

- [ ] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [x] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [x] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [x] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [x] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [x] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by Anilugale** [comment]
There is structure like tweeter details view. tweet with video + and it comments with video. 

<NestedScrollView>
 <Header of tweet>
   <RecyclerView -- video or image multiple 
   </ RecyclerView>
<Header/>
<RecyclerView  -- comments list
  <recycler item -- comment with multile video />
</RecyclerView>

<NestedScrollView/>

**Comment by eneim** [comment]
@Anilugale What makes you think they use NestedScrollView for it? Actually they use ListView for the Tweet detail. I suggest you not to nest a RecyclerView inside a ScrollView. For this purpose you can always have a RecyclerView as your Header (the Tweet content), this one is one ViewHolder for the main RecyclerView, other ViewHolders are the comment as well. The imagine is as below:

```xml
<RecyclerView>
  <TweetDetailViewHolder>
  // If tweet detail requires a RecyclerView, use RecyclerView here. If not, just a normal ViewGroup.
  </TweetDetailViewHolder>
  // Below: ViewHolders for comments, so many of them
  <TweetCommentViewHolder></TweetCommentViewHolder>
  <TweetCommentViewHolder></TweetCommentViewHolder>
  <TweetCommentViewHolder></TweetCommentViewHolder>
  ...
</RecyclerView>
```

**Comment by Anilugale** [comment]
thanks for replay let me try this @eneim

**Comment by eneim** [comment]
@Anilugale Sure, let me know if you have trouble with that. Actually my suggestion is not only for my library :D, generally putting a RecyclerView inside a NestedScrollView with the same scroll direction is somehow not a good idea. But let's see if your code works first.

**Comment by Anilugale** [comment]
yup sure @eneim and thanks for support

**Comment by eneim** [comment]
@Anilugale any chance this issue will be closed? Do you need further help for your usecase?

**Comment by Anilugale** [comment]
yes it had closed. thanks for replay

**Comment by Terenfear** [comment]
One of possible solutions is to set a custom OnScrollChangeListener with debouncing capabilities on a NestedScrollView. Roughly it could work like that: if there are no events in, say, 50 ms then we pass a RecyclerView.SCROLL_STATE_IDLE into a Container, otherwise pass a RecyclerView.SCROLL_STATE_SETTLING. Plus you can filter out repetitive values to reduce an amount of processing.
