### ISSUE TITLE
getAdapterPosition() returns always -1

### ISSUE THREAD

**Issue by anthony3444** [eneim/toro#282]
Hi!

I've implemented CacheManager with this example: https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/facebook/timeline/TimelineAdapter.java

Unfortunately there is no change. The playback restarts at each time. I put a breakpoint and the problem is in this call:

```
@Override
        public int getPlayerOrder() {
            return getAdapterPosition();
        }
```

getAdapterPosition() returns always -1, I can't understand why? Have you got a special implementation of your method getPlayerOrder() with cache manager?

Thank you very much!

**Comment by eneim** [comment]
@anthony3444 Did you set the CacheManager to Container? As you can see [here](https://github.com/eneim/toro/blob/dev-v3/toro-core/src/main/java/im/ene/toro/widget/Container.java#L371) , both CacheManager and the Order are taken into account :). Please double check and let me know. Also you can show me your implementation of CacheManager as well.

**Comment by anthony3444** [comment]
@eneim : I found my problem. It's a viewholder inside a parent viewholder. So I just gave this viewholder parent and it works like a charm!

```
        @Override
        public int getPlayerOrder() {
            return mParentViewHolder.getAdapterPosition();
        }
```
