### ISSUE TITLE
ToroPlayerHelper & ExoPlayerHelper acquiring & releasing performance

### ISSUE THREAD

**Issue by DummyCo** [eneim/toro#285]
Hi there! Thank you for great implementation.
As far as I can see, player & helper releasing/creating on view detach & init while using players in RecyclerView is quite expensive.
Would it be wise to suggest implementation with reused players (pool?) among helpers or something like that?

**Comment by eneim** [comment]
@DummyCo Hi there, this is actually the biggest homework I have with Toro. At the meantime I'm investing my time finding a good way to switch the player resource between ViewHolder (ToroPlayer) in safe way. No good result so far, but I'm still working on it.

**Comment by eneim** [comment]
@DummyCo can you take a look at 3.4.0-A1 and give it a try? This will slightly improve the performance of creating SimpleExoPlayer and stuff. It may not yet cover all performance-pain points, but the feedback will help me to bring them to the final release :D. The Changelog and demo-exoplayer is where you can find demo code.

**Comment by DummyCo** [comment]
Hi, @eneim!
Thank you for that efforts :tada:
Integrating'n'testing it now, will notify the results ASAP.

**Comment by DummyCo** [comment]
@eneim tested it on Nexus 5X & Pixel XL.
I was experiencing 1-2 frames drop on 3.2.0 version during video item detaching, now it's completely gone, flow is average 60fps on any video items mess, testing it with devices side-to-side.
Thank you, looking forward to next releases.
