### ISSUE TITLE
[Question] RecyclerView with item child is ViewPager

### ISSUE THREAD

**Issue by VuDung** [eneim/toro#289]
Hi @eneim 
Thanks for awesome library. I'm trying implement this with my application:
- My app has list video, with every item child which has list video inside(same structure).
- Current, i'm using ViewPager as item child of RecyclerView.
* Problem: Auto play video (item visible on ViewPager which visible on RecyclerView) when i scroll RecyclerView.
Can i try this library for support Video list auto playback?

**Comment by eneim** [comment]
You mean your ViewHolder's itemView is a **ViewPager** ? How this **ViewPager** is used? using Fragments or just Views inside it? Why not using RecyclerView instead of ViewPager?

**Comment by VuDung** [comment]
Thanks for your reply.

> You mean your ViewHolder's itemView is a ViewPager ?

=> Yes

>  How this ViewPager is used? using Fragments or just Views inside it?

=> i'm using view

> Why not using RecyclerView instead of ViewPager?

For some reasons, i used ViewPager. If i change ViewPager to RecyclerView, can i use your library for support video list auto playback?

**Comment by eneim** [comment]
Please take a look at this issue #287 , it is discussed about Nested RV (RV as Child of a big RV (Container)). Also there is a link to a demo I made for the case. Hope it helps.

**Comment by eneim** [comment]
If you have any issue implementing it, let me know. When you find it has resolved your problem, please help to close this issue :D.
