### ISSUE TITLE
How to get video buffered percentage - i am using HLS video need to show a loader till the video buffered and goes to on playing state. It has been suggested to get by using ExoPlayer.getBufferedPercentage help me to get those value in toro player.

### ISSUE THREAD

**Issue by vigneshr87** [eneim/toro#292]
What kind of issue is this?

- [x] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [ ] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by eneim** [comment]
@vigneshr87 as you are using SimpleExoPlayerView, you can get the SimpleExoPlayer instance and then get the Buffered percent from it. Don't forget to check null.
