### ISSUE TITLE
Mixed ViewHolder types of nested ToroPlayer

### ISSUE THREAD

**Issue by DummyCo** [eneim/toro#293]
Hi there, @eneim!
I'm trying to apply logic mentioned in #287 for the case where nested _RecyclerView_ has not only _ToroPlayer_ _ViewHolders_ but also other types. Strange things happen in that case, initial position is damaged, some suspicious views appear in _LayoutManager_.
Any ideas? Do we have support of such case? Thank you!

**Comment by eneim** [comment]
@DummyCo thanks. Can you help me a screenshot/screen record for this? At the moment I'm trying to bring ExoPlayer pool and cache to improve performance, which takes a lot of time. A really bad issues can be queued right after that one (the terrible issues can be put above it ...). So would like to know how terrible is this thing ^^!

**Comment by DummyCo** [comment]
@eneim oh sorry. I've started deep investigation about this behavior and tried to implement same case on your _MediaListViewHolder_ with two hosted _ViewHolder_ types (with and without a video) and it worked great. As it turns out, having nested _ViewHolder_ (in nested _RecyclerView_) with nested _ViewStub_ where _ImageView_ backed with _Glide_ is inflated causes the situation where that _ImageView_ has zero dimensions. Sorry for misleading again :)

**Comment by eneim** [comment]
@DummyCo Sounds to be a good investigation :D. In fact I need some doc telling user about many stuffs. I would include this into a blog post (if I can manage to make one, but sure I want to).
