### ISSUE TITLE
How can I play multiple videos at once on visible screen?

### ISSUE THREAD

**Issue by ajaystha005** [eneim/toro#294]
Any help??

Thank you

**Comment by eneim** [comment]
@ajaystha005 You can implement your own ```PlayerSelector``` and return the list of Player you want to play there, set it to your Container and that it. See [this](https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/complex/ComplexListFragment.java#L78) for a demo.

**Comment by ajaystha005** [comment]
Thank you
