### ISSUE TITLE
video not display in Recyclerview from web url using Toro video library (Blank and Black screen)

### ISSUE THREAD

**Issue by sodiqOladeni** [eneim/toro#298]
I'm working on a project that involves displaying a list of videos from the backend using retrofit, i want to display the video with some data on the UI using recyclerview, i'm trying to use TORO video labrary to handle the video but instead of displaying the video the video space is blank and black and other info apart the video was displayed successfully, when checking the logcat for error message.
What i want is proper usage of the library if i'm getting it wrong, or link to other library that you have tested that i could use or how you do it in your own project if you have done it before.

check adapter code below used with the library.

    package com.theconnector.allClass.adapters;
    
    import android.app.Activity;
    import android.content.Context;
    import android.net.Uri;
    import android.support.annotation.NonNull;
    import android.support.annotation.Nullable;
    import android.support.design.widget.Snackbar;
    import android.support.v7.widget.RecyclerView;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.ArrayAdapter;
    import android.widget.ImageView;
    import android.widget.TextView;
    import android.widget.VideoView;
    
    import com.bumptech.glide.Glide;
    import com.google.android.exoplayer2.ui.SimpleExoPlayerView;
    import com.klinker.android.simple_videoview.SimpleVideoView;
    import com.theconnector.R;
    import com.theconnector.allClass.api.model.AuditionRoom;
    import com.theconnector.allClass.api.model.Timeline;
    
    import java.util.List;
    
    import im.ene.toro.ToroPlayer;
    import im.ene.toro.ToroUtil;
    import im.ene.toro.exoplayer.SimpleExoPlayerViewHelper;
    import im.ene.toro.media.PlaybackInfo;
    import im.ene.toro.widget.Container;
    
    public class AuditionRoomAdapter extends RecyclerView.Adapter<AuditionRoomAdapter.ViewHolder> {
    
        private Context context;
        private List<AuditionRoom> data;
    
        public AuditionRoomAdapter(Context context, List<AuditionRoom> data) {
            this.context = context;
            this.data = data;
        }
    
        @Override
        public ViewHolder onCreateViewHolder(ViewGroup viewGroup, int viewType) {
            View view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.audition_timeline, viewGroup, false);
            return new ViewHolder(view);
        }
    
        @Override
        public void onBindViewHolder(final ViewHolder holder, int position) {
            holder.username.setText(data.get(position).getUsername());
            holder.userPostText.setText(data.get(position).getUserMessage());
            holder.yes.setText(""+data.get(position).getYes_votes_count());
            holder.no.setText(""+data.get(position).getNo_votes_count());
            Glide.with(context).load(data.get(position).getUserProfilepicUrl()).into(holder.userProfilePic);
    //        Glide.with(context).load(data.get(position).getUpload_file_url()).into(holder.userPostImage);
            holder.bind(Uri.parse(data.get(position).getUpload_file_url()));
    
        }
    
        @Override
        public int getItemCount() {
            return data.size();
        }
    
        public class ViewHolder extends RecyclerView.ViewHolder implements ToroPlayer{
    
            TextView username;
            TextView userPostText;
            TextView yes;
            TextView no;
            ImageView userProfilePic;
            ImageView userPostImage;
            SimpleExoPlayerView playerView;
            SimpleExoPlayerViewHelper helper;
            Uri mediaUri;
    
            public ViewHolder(View itemView) {
                super(itemView);
    
                userProfilePic = itemView.findViewById(R.id.audition_user_profile_pic);
                username = itemView.findViewById(R.id.audition_user_name);
                userPostText =  itemView.findViewById(R.id.audition_user_post_text);
                //userPostImage = itemView.findViewById(R.id.audition_user_post_image);
                playerView = itemView.findViewById(R.id.player);
    
                yes =  itemView.findViewById(R.id.audition_yes_figure);
                no = itemView.findViewById(R.id.audition_no_figure);
            }
    
            @NonNull
            @Override
            public View getPlayerView() {
                return playerView;
            }
    
            @NonNull
            @Override
            public PlaybackInfo getCurrentPlaybackInfo() {
                return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
            }
    
            @Override
            public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
                if (helper == null) {
                    helper = new SimpleExoPlayerViewHelper(container, this, mediaUri);
                }
                helper.initialize(playbackInfo);
            }
    
            @Override
            public void play() {
                if (helper != null) helper.play();
            }
    
            @Override
            public void pause() {
                if (helper != null) helper.pause();
            }
    
            @Override
            public boolean isPlaying() {
                return helper != null && helper.isPlaying();
            }
    
            @Override
            public void release() {
                if (helper != null) {
                    helper.release();
                    helper = null;
                }
            }
    
            @Override
            public boolean wantsToPlay() {
                return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
            }
    
            @Override
            public int getPlayerOrder() {
                return getAdapterPosition();
            }
    
            @Override
            public void onSettled(Container container) {
    
            }
    
            // called from Adapter to setup the media
            void bind(Uri item) {
                if (item != null) {
                    mediaUri = item;
                }
            }
        }
    }

**Comment by eneim** [comment]
@sodiqOladeni Can you give me the info of your video? Its format, codec, profile, etc? A video that can reproduce the issue would be perfect.

**Comment by sodiqOladeni** [comment]
@eneim the video format is mp4, i'm playing the video from url using retrofit. the video play when i tried to play it via the browser with the received url, im sure there is no issue with the video

**Comment by eneim** [comment]
@sodiqOladeni mp4 is just the container, what I concern is the codec it is. Depends on what device (the Android phone) you are using, it could support the video codec or not. For example, Samsung S8 may support decoding HEVC but Nexus 5 may not, even though videos are mp4s. And you browser is just as powerful as your PC so it should be fine. If you can send me a part of your Video (make sure that part can be used to reproduce the issue) I can do the investigation on my side :D.

**Comment by sodiqOladeni** [comment]
@eneim i dont know what you meant by part of the video, this is the url of the video
http://krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72%20-%20Recap.mp4

and the device i'm using for testing is Samsung S5 and Itel1409, will be glad if the issue can be resolved

**Comment by eneim** [comment]
@sodiqOladeni Got it. I just download it and also change the link in comment for your privacy. Let me see.

**Comment by sodiqOladeni** [comment]
ok, thanks for that

**Comment by sodiqOladeni** [comment]
@eneim check the below logcat error message for more understanding
 Source error.
                                                                       com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72 - Recap.mp4: open failed: ENOENT (No such file or directory)

**Comment by eneim** [comment]
What version are you using? It says the file is not found. I have a Samsung S5 so let me see.

**Comment by sodiqOladeni** [comment]
i'm using version 3.3.0

**Comment by eneim** [comment]
@sodiqOladeni try putting "http" or "https" to your URL's scheme.

Long story short: your URL appears to have no scheme, and will be recognized as a local file --> it will create a FileDataSource but there is no actual file in your storage.

**Comment by sodiqOladeni** [comment]
@eneim i dont get your suggestion, are you talking about the video URL and the server URL

**Comment by eneim** [comment]
@sodiqOladeni Ok let me help you a walkthrough about the issue:

So here is our issue, taken from your error log:

```
com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72 - Recap.mp4: open failed: ENOENT (No such file or directory)
```

It says that ExoPlayer is using a **FileDataSource** to read your Video, which supposes to be created to read local file only, which doesn't sound right to me because your file is from internet.

So here is where the DataSource got created by ExoPlayer (from DefaultDataSource.java):

```java
@Override
  public long open(DataSpec dataSpec) throws IOException {
    Assertions.checkState(dataSource == null);
    // Choose the correct source for the scheme.
    String scheme = dataSpec.uri.getScheme();
    if (Util.isLocalFileUri(dataSpec.uri)) {
      if (dataSpec.uri.getPath().startsWith("/android_asset/")) {
        dataSource = getAssetDataSource();
      } else {
        dataSource = getFileDataSource();
      }
    } else if (SCHEME_ASSET.equals(scheme)) {
      dataSource = getAssetDataSource();
    } else if (SCHEME_CONTENT.equals(scheme)) {
      dataSource = getContentDataSource();
    } else if (SCHEME_RTMP.equals(scheme)) {
      dataSource = getRtmpDataSource();
    } else if (DataSchemeDataSource.SCHEME_DATA.equals(scheme)) {
      dataSource = getDataSchemeDataSource();
    } else {
      dataSource = baseDataSource;
    }
    // Open the source and return.
    return dataSource.open(dataSpec);
  }
```

And the FileDataSource is created when ``Util.isLocalFileUri(dataSpec.uri)`` returns ``true``.

Looking into that method, it turns out that: if you links doesn't have a scheme, it will be judged as a local file. So let take a look back:

Your Video link is: ``krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72 - Recap.mp4``.

Assuming you are not so sure about ``Scheme`` I'm telling, seeing the following Url:
``https://eneim.github.io/path/another-path?query=parameter`` --> in this link, ``https`` is called the **Scheme**. You can read more about it here: [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier).

So as you can see, your URL doesn't have a scheme, it has been seen as a local file which will absolutely crash ExoPlayer.

What I suggest, is after you get ``krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72 - Recap.mp4`` from your server, you can put ``http`` or ``https`` to it, like below:

``https://krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72 - Recap.mp4``

And see if it works.

**Comment by eneim** [comment]
@sodiqOladeni FYI fixing your link to this:

``http://krystanet.com/auditions/98d5f481477281aadaEeYCbEqXXXebLE72%20-%20Recap.mp4``

works.

**Comment by sodiqOladeni** [comment]
@eneim kindly drop your twitter handle, i need to follow you everywhere. The video is now working after
appending the schema, Thanks so much for your time.
Another thing is how can i put control on the videos for user to use ?

**Comment by eneim** [comment]
@sodiqOladeni As you are using SimpleExoPlayerView, it has an option (in xml file) called 'user_controller'. See below snippet:

```xml
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
          android:id="@+id/playerView"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          app:use_controller="true"
          />
```

Using ``app:use_controller="true"`` will show the controller (default), set it to false will hide the controller.

Sorry I'm not an active Twitter user.

**Comment by sodiqOladeni** [comment]
ok thanks, everything now work as expected
