### ISSUE TITLE
When I run the build gradle, I got this error 

### ISSUE THREAD

**Issue by ismailtosun** [eneim/Toro#299]
> Error:Could not get unknown property 'youtube_apikey' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=16, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=27, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=im.ene.toro.youtube, testApplicationId=null, testInstrumentationRunner=android.support.test.runner.AndroidJUnitRunner, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.
> 
> Consult IDE log for more details (Help | Show Log)

**how to solve this ?**

**Comment by eneim** [comment]
@ismailtosun there is app-youtube demo app that requires your own youtube Api Key. Please search for how to create one (it is one of the Google API key), and replace it in gradle.properties-sample, and then rename that file to gradle.properties.
