### ISSUE TITLE
ViewHolder initialized without calling bind on a RecycleView

### ISSUE THREAD

**Issue by FranciscoNin** [eneim/toro#303]
Hi @eneim! Again, thanks for this great library.

I'm having this issue where I have a timeline with pictures and videos. I'm using the same ViewHolder for both of them, as I need everything else that goes along with a Post, just changing if it's picture or video.

The thing is that when a video viewholder is recycled but now it's a picture, this viewholder is getting initialized again, playing the video where there's an image. I want to know if there's any way to prevent that. I made this code below to stop it from playing, but it's still initializing.

ViewHolder: 
`void onRecycled() {
            urlSource = null;
            release();
        }`

Adapter:
`@Override
    public void onViewRecycled(ViewHolder holder) {
        holder.onRecycled();
    }`

Thanks!

**Comment by eneim** [comment]
@FranciscoNin I guess when the bind() is called, you have not clear the Uri or something that holds information of your Video. When RecyclerView's onChildAttachedToWindow is called, if it detects that your ViewHolder is a **ToroPlayer** then it (the Container) will ask for all the initialization and playback stuff. I suggest to not use them together ... You can build a base ViewHolder whose main use case is fo r Photo post, and extend it for the case of Video. A bit more code but sounds safer to me :(.

**Comment by FranciscoNin** [comment]
It makes sense!
Thanks, I'll try it out!
