### ISSUE TITLE
Top part of current row video is covered with last row video?

### ISSUE THREAD

**Issue by navdroid** [eneim/toro#312]
I am facing this issue when scrolling in the recyclerView, current row video upper part is covered with the last row video. This happens like 3 out of 5 times . Is there a way to fix this ?

![screenshot_20180309-144756](https://user-images.githubusercontent.com/1570679/37203075-7bd1f6b0-23b2-11e8-8074-e9e080141585.png)

**Comment by eneim** [comment]
@navdroid Hi there, can you give me more information?

Toro version? Android device and version? ExoPlayer version? xml of your Video? There is a high chance it is ExoPlayer issue or TextureView issue, but let me know so I can help.

**Comment by navdroid** [comment]
Hi @eneim ,

Toro version - v3.1.0.
Android Device - Nexus 6 Android 7.1.1
ExoPlayer - r2.5.1.

Xml of Video:

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

        <import type="android.view.View" />
        <variable
            name="post"
            type="com.appster.turtle.network.response.Posts" />
    </data>

    <android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="5.8dp"
        android:layout_marginStart="4.8dp"
        android:elevation="8dp"
        app:cardCornerRadius="11.5dp">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <RelativeLayout
                android:id="@+id/fl_video"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:clickable="true"
                android:focusable="true">

                <com.google.android.exoplayer2.ui.SimpleExoPlayerView
                    android:id="@+id/video_view"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/media_height"
                    android:clickable="false"
                    app:default_artwork="@anim/fade_in"
                    app:resize_mode="fixed_width"
                    app:use_controller="false" />


                <RelativeLayout
                    android:id="@+id/rl_video_click"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_alignBottom="@id/video_view"
                    android:layout_alignTop="@id/video_view"
                    android:clickable="true"
                    android:focusable="true">

                    <ImageView
                        android:id="@+id/iv_play"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_centerInParent="true"
                        android:contentDescription="@null"
                        android:scaleType="center"
                        android:src="@drawable/ic_play" />
                </RelativeLayout>


                <ImageView
                    android:id="@+id/iv_media"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/media_height"
                    android:layout_centerInParent="true"
                    android:contentDescription="@null"
                    android:scaleType="centerCrop" />

            </RelativeLayout>

            
            
            
            
            
            

            

            <RelativeLayout
                android:id="@+id/fl_image_user"
                android:layout_width="@dimen/post_user_image"
                android:layout_height="@dimen/post_user_image"
                android:layout_below="@id/fl_video"
                android:layout_marginTop="13.4dp"
                android:layout_marginStart="@dimen/dimen_15_4"
                app:bindShowProfile="@{post.usersListModel.userId}">

                <com.mikhaellopez.circularimageview.CircularImageView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_centerInParent="true"
                    android:src="@{post.usersListModel.profileUrlType==3 ? @drawable/ic_pp_cred:@drawable/ic_transparent}"
                    app:civ_border_width="0dp" />

                <com.mikhaellopez.circularimageview.CircularImageView
                    android:layout_width="@dimen/image_w"
                    android:layout_height="@dimen/image_w"
                    android:layout_centerInParent="true"
                    android:background="@color/transparent"
                    android:contentDescription="@null"
                    android:visibility="@{post.usersListModel.profileUrlType==3 ? View.INVISIBLE:View.VISIBLE}"
                    app:civ_border_width="0dp"
                    app:profileImageurl="@{post.usersListModel.profileUrl}" />

                <ImageView
                    android:layout_width="@dimen/post_user_init"
                    android:layout_height="@dimen/post_user_init"
                    android:layout_centerInParent="true"
                    android:background="@color/transparent"
                    android:contentDescription="@null"
                    android:visibility="@{post.usersListModel.profileUrlType==3 ? View.VISIBLE:View.INVISIBLE}"
                    app:profileImageurl="@{post.usersListModel.profileUrl}" />


            </RelativeLayout>


            <com.appster.turtle.widget.CustomTextView
                android:id="@+id/tv_username"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@id/fl_video"
                android:layout_marginStart="@dimen/margin_7_8"
                android:layout_toEndOf="@id/fl_image_user"
                android:layout_marginTop="@dimen/dimen_9_6"
                android:text='@{"@"+post.usersListModel.userName}'
                android:textColor="#090909"
                android:padding="0dp"
                android:lineSpacingExtra="0sp"
                android:textSize="16.3sp"
                android:includeFontPadding="false"
                app:customFont="@string/eina_01_semibold" />

            <com.appster.turtle.widget.CustomTextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@id/tv_username"
                android:layout_marginStart="@dimen/margin_7_8"
                android:layout_toEndOf="@id/fl_image_user"
                android:text="@{post.usersListModel.universityBaseModel.displayName}"
                android:textColor="#a9aab1"
                android:padding="0dp"
                android:includeFontPadding="false"
                android:textSize="12.5sp"
                app:customFont="@string/eina_01_semibold" />

            <ImageView
                android:layout_width="3.8dp"
                android:layout_height="17.3dp"
                android:layout_alignBottom="@id/fl_image_user"
                android:layout_alignParentEnd="true"
                android:layout_alignTop="@id/fl_image_user"
                android:layout_marginEnd="19.2dp"
                android:src="@drawable/menu" />


            <com.appster.turtle.widget.CustomTextView
                android:id="@+id/tv_caption"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignStart="@id/fl_image_user"
                android:layout_below="@id/fl_image_user"
                android:layout_marginTop="8dp"
                android:lineSpacingExtra="6.7sp"
                android:text="@{post.caption}"
                android:textColor="#212121"
                android:textSize="16.3sp"
                app:customFont="@string/eina_01_regular" />

            <include
                android:id="@+id/bottom_layout"
                layout="@layout/post_bottom_layout"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignStart="@id/tv_caption"
                android:layout_below="@id/tv_caption"
                android:layout_marginBottom="18.5dp"
                android:layout_marginTop="12.5dp" />
        </RelativeLayout>


    </android.support.v7.widget.CardView>


</layout>`

**Comment by navdroid** [comment]
Got my mistake . Sorry for bothering you. I was not using :

` app:surface_type="texture_view"
android:minHeight="@dimen/media_height"`

**Comment by eneim** [comment]
Hey, usng TextureView is not a good choice everytime. If you can give me the video file (either by file or url) that produces this issue I can continue the investigation.
