### ISSUE TITLE
 How to use Cache and Looping source [ requesting network URL ]

### ISSUE THREAD

**Issue by ishroid** [eneim/toro#320]
This is most beautiful library for ExoPlayer lover.

Anyone please let me know, how to use Cache and Looping source in Toro Library.

Or if any expert know other link of related article or library please let me know.

thank you

**Comment by ishroid** [comment]
THANK YOU IT WORKS 👍 💯 🥇

**Comment by denno640** [comment]
@ishroid @eneim I have been trying to use the caching as well as looping. I succeed in looping using ExoPlayerViewHelper in my viewholder class. How do I get the caching in my project? I have used the gradle dependencies to get Toro. I'm suspecting I have to change the way I'm importing the library? Please help

**Comment by eneim** [comment]
Hey, there is a comment above about Cache, can you take a look?

**Comment by froozesocial** [comment]
How can I achieve this in Java?
