### ISSUE TITLE
Display loading image till the video is loaded the first time in listview

### ISSUE THREAD

**Issue by ritesh94** [eneim/toro#329]
Thanks for such a powerful library. Saved lot of time. Complex work made easy.

My question is how do I display a loading image till the video is loaded the **first time**?

Once the video is loaded and playing 
Either when the user scrolls the list or pauses the video or video is buffering the loading image shouldn't appear.

`addPlayerEventListener` is not helping for this requirement

**Comment by eneim** [comment]
@ritesh94 Thanks for using Toro. Right now I'm thinking about using ExoPlayer and EventListener's onFirstFrameRendered, but need to try it first. You can setup the listener using ExoPlayerHelper and so on.

**Comment by ritesh94** [comment]
@eneim 
Yes thats perfect. Thanks..!!
