### ISSUE TITLE
How do i mute youtube videos on autoplay..i know that the youtube api does not support muted videos but is there any way to mute the toro player so that if an external app is playing music..it doesnt stop when the muted youtube video starts on my app?

### ISSUE THREAD

**Issue by kaustubhamrit** [eneim/toro#332]
What kind of issue is this?

- [ ] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [x] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by eneim** [comment]
Sorry, there is no way to mute Youtube video. I suppose it is a part of Youtube API TOS so even if you can do so, you will be against that term.

**Comment by kaustubhamrit** [comment]
Thanks for the information.
Great work btw! :D
