### ISSUE TITLE
How can i mute video ?

### ISSUE THREAD

**Issue by yankelandroid** [eneim/toro#347]
What kind of issue is this?

- [x] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [ ] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by eneim** [comment]
@yankelandroid Can you answer the questions in template?

**Comment by yankelandroid** [comment]
its done its just a question

**Comment by eneim** [comment]
@yankelandroid Yeah, but I need to know which version of Toro you are using, therefore I know how you can mute the Video. Please help :D.

**Comment by yankelandroid** [comment]
yes of course sorry haha :)

 'im.ene.toro3:toro:3.2.0'
 'com.google.android.exoplayer:exoplayer:r2.5.4'

**Comment by eneim** [comment]
@yankelandroid Thanks.

Supposing that you are using ``ExoPlayerHelper`` for your ViewHolder, the ```player``` instances is not exposed, so it is not straight forward to mute. You can use your ```playerView`` instance, getPlayer() as ```SimpleExoPlayer``` and then call ```setVolume()``` from there.

In latest 3.5.2, there is interface to work with volume though. It is not trivial to update from 3.2.0 to 3.5.2, but if you have time please give it a try.

**Comment by yankelandroid** [comment]
i solved it thx , i change the volume in the func overrid play

**Comment by eneim** [comment]
@yankelandroid Got it. Good to hear that. Please consider to close the issue as well :D.
