### ISSUE TITLE
Does toro worksin child recyclerview inside parent recyclerview?

### ISSUE THREAD

**Issue by dajver** [eneim/toro#355]
@eneim Hi! I have found that if put toro into child recyclerview holder which will be in parent recyclerview holder, it is not working. For example

I have parent view holder where I waht to have list of all my videos in horizontal recycler view. Here I create anopther adapter with child view holder to show them in horizontal list.

`
public class ProcessedViewHolder2 extends RecyclerViewHolder {

    @BindView(R.id.title)
    TextView title;
    @BindView(R.id.time)
    TextView time;
    @BindView(R.id.videoPagerRecycler)
    RecyclerView videoPagerRecycler;

    private Context context;
    private EdgeModel mEdgeModel;
    private boolean isDefined = false;

    public ProcessedViewHolder2(Context context, ViewGroup parent) {
        super(parent, R.layout.item_feed_processed2);
        this.context = context;

        if(!isDefined) {
            PagerSnapHelper snapHelper = new PagerSnapHelper();
            snapHelper.attachToRecyclerView(videoPagerRecycler);
            isDefined = true;
        }
    }

    public void bind(EdgeModel mEdgeModel, FeedRecyclerAdapter.OnItemClickListener onItemClickListener) {
        this.mEdgeModel = mEdgeModel;
        title.setText(mEdgeModel.getNode().getName());
        time.setText(TimeSinceUtils.getTimeAgo(context, mEdgeModel.getNode().getCreatedAt()));

        VideoPagerRecyclerAdapter videoPagerRecyclerAdapter = new VideoPagerRecyclerAdapter(context, blinkEdgeModel.getNode().getClips(), blinkEdgeModel.getNode());
        videoPagerRecycler.setLayoutManager(new LinearLayoutManager(context, LinearLayoutManager.HORIZONTAL, false));
        videoPagerRecycler.setAdapter(videoPagerRecyclerAdapter);

        videoPagerRecycler.addItemDecoration(new LinePagerIndicatorDecoration());
    }
}
`

And I have child view holder where I show my video with placeholder. And here it doesn't work...

`
public class VideoPagerViewHolder extends RecyclerViewHolder implements ToroPlayer {

    @BindView(R.id.video)
    VideoPlayerView mVideoPlayerView;
    @BindView(R.id.image)
    ImageView image;

    private LoopExoPlayerHelper helper;
    private NodeModel mNodeModel;
    private ClipsModel mClipsModel;

    public VideoPagerViewHolder(ViewGroup viewParent) {
        super(viewParent, R.layout.item_video_pager);
    }

    public void bind(ClipsModel mClipsModel, NodeModel mNodeModel) {
        this.mClipsModel = mClipsModel;
        this.mNodeModel = mNodeModel;

        Picasso.get().load(mNodeModel.getThumbnail()).into(image);
        blinkVideoPlayerView.initPlayer(helper, mNodeModel);
    }

    // TORO

    @Override
    public View getPlayerView() {
        return blinkVideoPlayerView.getExoPlayerView();
    }

    @Override
    public PlaybackInfo getCurrentPlaybackInfo() {
        return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
    }

    @Override
    public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
        if (helper == null) {
            helper = new LoopExoPlayerHelper(this, Uri.parse(mNodeModel.getDashManifest()));
        }
        helper.initialize(playbackInfo);
        mVideoPlayerView.initPlayer(helper, mNodeModel);
    }

    @Override
    public void play() {
        image.setVisibility(View.GONE);
        mVideoPlayerView.playVideo();
    }

    @Override
    public void pause() {
        image.setVisibility(View.VISIBLE);
        mVideoPlayerView.pauseVideo();
    }

    @Override
    public boolean isPlaying() {
        return helper != null && helper.isPlaying();
    }

    @Override
    public void release() {
        if (helper != null) {
            helper.release();
            helper = null;
        }
    }

    @Override
    public boolean wantsToPlay() {
        return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
    }

    @Override
    public int getPlayerOrder() {
        return getAdapterPosition();
    }

    @Override
    public void onSettled(Container container) { }
}
`

But when I put this sub view holder outside of parent recycler view holder, it works. What it could be? Does Toro work with sub recycler view inside parent recyclerview?

**Comment by dajver** [comment]
My stupidity, I tried to use recyclerview instead of container :D

**Comment by eneim** [comment]
@dajver sounds good :D
