### ISSUE TITLE
Playerview of one fragment show in other fragment

### ISSUE THREAD

**Issue by HemangiVekaria** [eneim/toro#359]
I am using com.google.android.exoplayer2.ui.playerview in one of my app.
In my app i have tab bar with fragments and in first fragment of tab i am using recyclerview with this playerview. 

This work fine in that fragment. Now when i switch to second tabs fragment there i also use RecyclerView with PlayerView. for both fragments recyclerView adapter and xml files are different. But still when second fragment open Playerview plays video of first fragment and current fragment in same Player view in half.

I dont know whats the problem with this. event in my whole app where i use playerview same problem occure except first fragment.

**Comment by eneim** [comment]
@HemangiVekaria can you share with me how you setup your ViewPager (you are using it right?).

**Comment by HemangiVekaria** [comment]
Thanks @eneim I am not using view pager. I have five tabs in my main activity. When activity open i replace FirstFragment with Recyclerview to one Frame. After that on click of other tab i replace SecondFragment in same frameLayout container.

**Comment by eneim** [comment]
:-? 

> current fragment in same Player view in half.

What do you mean by that? Any screenshot for easy to imagine result?

You replacing the Fragment using fragmentTransction.replace or fragmentTransaction.attach/detach or fragmentTransaction.add/remove?

(I suppose It will affect how RecyclerView is attached/detached)

**Comment by HemangiVekaria** [comment]
I am using fragmentTransacton.replace for replacing fragment.

"same player view half" by mean when second fragment open with recyclerView with Playerview at that time Player view of that fragment is already there. Playerview of first fragment is upon current Playerview. When you scroll listview at that time current player view scroll up with recycler view while playerview from first is stick on same position. so when scroll it show in half view.
![device-2018-08-03-181403](https://user-images.githubusercontent.com/17717369/43643642-90bf94fa-9749-11e8-86db-2251962aec8a.png)


When scroll up at that time current screen player goes behind player view from home

**Comment by eneim** [comment]
@HemangiVekaria I see. I think this is something with [1] PlayerView that use SurfaceView and [2] Artifact problem of old playback.

Can you verify the following things:

- [1] Using TextureView for PlayerView (set the xml attribute). It is not recommended to use TextureView though, I just want to verify my theory.

- [2] Change Container to RecyclerView in all your fragments (to make sure this is not something toro or ExoPlayer have done wrong).

Please let me know what you see :D. I will actively looking into this case.

**Comment by HemangiVekaria** [comment]
Using texture view for player view it's worked for me... Thank you so much @eneim

**Comment by eneim** [comment]
@HemangiVekaria About the repeat mode, I need to figure out this field. For your information, current version of Toro still use LoopingMediaSource for looping the Video. I'm updating it to newer implementation of ExoPlayer. Though my time is quite tight lately, I will push some update soon.

**Comment by HemangiVekaria** [comment]
Thanks @eneim.... LoopingMediaSource for looping the Video worked for me.
