### ISSUE TITLE
Unable to add Toro in android studio

### ISSUE THREAD

**Issue by GaurangShahaAppstute** [eneim/Toro#36]
Followed the configuration steps provided but gradle is showing Error:(31, 13) Failed to resolve: com.github.eneim:Toro:1.2.0.

**Top level build.gradle is as below -**

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
       maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Module level build.gradle is as below -**

```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "in.appstute.myapplication"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'
    compile 'com.github.eneim:Toro:1.2.0'
}
```

Hope I will get quick response. Thanks in advance. :)

**Comment by eneim** [comment]
Thanks for your interest. I made a change on your comment to make your code looks better.

Can you provide me some following information:

- gradle version (from ```/gradle/gradle-wrapper.properties``` file)
- Android Studio version
- Which you prefer to use now: ```classpath 'com.android.tools.build:gradle:1.5.0'``` or ```classpath 'com.android.tools.build:gradle:2.0.0' ```.

- And please check your internet connection too.

If you can run gradle task with option ```--info``` or ```--trace```, please give me the error output.

**Comment by GaurangShahaAppstute** [comment]
- gradle version (from /gradle/gradle-wrapper.properties file) is 2.8

`#Wed Oct 21 11:34:03 PDT 2015
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-all.zip`

- Android Studio version is 1.5.1

- I can use any of `classpath 'com.android.tools.build:gradle:1.5.0'` or` classpath 'com.android.tools.build:gradle:2.0.0'`.

- Also I am connected to internet.

**Comment by GaurangShahaAppstute** [comment]
For gradle lower than 2.11 I was getting  **peer not authenticated error when downloading with gradle**. Able to add the library after updating gradle to 2.11. To update the version I changed to distributionUrl=https\://services.gradle.org/distributions/gradle-2.11-all.zip in /gradle/gradle-wrapper.properties file. 
Thanks @eneim for the direction and creating such great library. :+1:

**Comment by iamnitesh** [comment]
me also unable to add toro dependency here is my both Gradle files 



```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    ext {
        toroVersion = '2.1.0'
    }

    dependencies {

        // include in your module (app or library)
        // include only core Toro library
       // compile "im.ene.toro2:toro:${toroVersion}"

        // include extension for ExoPlayer v2 (Toro is included already)
        compile "im.ene.toro2:toro-ext-exoplayer2:${toroVersion}"
        // include extension for ExoPlayer v1 (Toro is included already)
        compile "im.ene.toro2:toro-ext-exoplayer:${toroVersion}"
        // include extension for Legacy MediaPlayer (Toro is included already)
        compile "im.ene.toro2:oro-ext-mediaplayer:${toroVersion}"

        // include Toro extended helper (Toro and ExoPlayer v2 extension is included already)
        compile "im.ene.toro2:toro-extended:${toroVersion}"
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**and the second one is app level gradle


```
 `apply plugin: 'com.android.application'**


android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "com.example.creativeinfoway2.playvideotesting"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.+'
    testCompile 'junit:junit:4.12'

}
```

hoping for quick response comes, thank you

**Comment by eneim** [comment]
You must include dependencies inside app-level gradle file. Please see my demo app for reference.

**Comment by iamnitesh** [comment]
In demo point 3. HOW TO USE  you have said  Projects top level gradle. which is where I added dependency

**Comment by eneim** [comment]
@iamnitesh Only add "jcenter()" there if you have not. The rest are added to module level dependencies.

**Comment by iamnitesh** [comment]
thanks for your response.it is working.

**Comment by eneim** [comment]
Good to hear that :D

**Comment by Tourenathan-G5organisation** [comment]
I followed the guide how to set the library, but i always have the following problem:  

> Error:Failed to resolve: im.ene.toro2:oro-ext-mediaplayer:2.1.0

here is the structure of the the top level build.gradle file
`
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.google.gms:google-services:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by Tourenathan-G5organisation** [comment]
Here is also the content of the app module build.gradle
`
apply plugin: 'com.android.application'


android {
    compileSdkVersion 25
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.toure.testingapp"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            res.srcDirs = [
                    'src/main/res',
                    'src/main/res/layouts',
                    'src/main/res/layouts/module_gesu',
                    'src/main/res/layouts/module_gcmq',
                    'src/main/res/layouts/module_gcpd',
                    'src/main/res/layouts/module_geqr',
                    'src/main/res/layouts/module_gmsg',
                    'src/main/res/layouts/module_gpub',
                    'src/main/res/layouts/module_gesretrait',
                    'src/main/res/layouts/module_gcgd',
                    'src/main/res/layouts/module_gnot'

            ]
        }
    }
}

ext {
    toroVersion = '2.1.0'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support:support-v4:25.0.1'
    compile 'com.github.ganfra:material-spinner:1.1.1'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.android.support:cardview-v7:25.0.1'
    compile 'com.github.h6ah4i:android-advancedrecyclerview:0.9.2'
    compile 'com.truizlop.sectionedrecyclerview:library:1.2.0'
    compile 'com.github.alex-townsend:SwipeOpenItemTouchHelper:1.2.1'
    compile 'dev.dworks.libs:volleyplus:+'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.github.satyan:sugar:1.5'
    compile 'com.iceteck.silicompressorr:silicompressor:1.1.0'
    compile "com.google.android.gms:play-services-gcm:9.6.1"
    compile 'com.google.firebase:firebase-messaging:9.6.1'

    /* Start of Toro dependencies */

    // include in your module (app or library)
    // include only core Toro library
    compile "im.ene.toro2:toro:${toroVersion}"

    // include extension for ExoPlayer v2 (Toro is included already)
    compile "im.ene.toro2:toro-ext-exoplayer2:${toroVersion}"
    // include extension for ExoPlayer v1 (Toro is included already)
    compile "im.ene.toro2:toro-ext-exoplayer:${toroVersion}"
    // include extension for Legacy MediaPlayer (Toro is included already)
    compile "im.ene.toro2:oro-ext-mediaplayer:${toroVersion}"

    // include Toro extended helper (Toro and ExoPlayer v2 extension is included already)
    compile "im.ene.toro2:toro-extended:${toroVersion}"

    /* End of Toro dependencies */

}
apply plugin: 'com.google.gms.google-services'
`

**Comment by Tourenathan-G5organisation** [comment]
Please @eneim , hope to hear from you as soon as possible.

**Comment by eneim** [comment]
@Tourenathan-G5organisation please use only the dependencies you need. And Exo1 and Exo2 **CANNOT** be used together. Please carefully read my REAME.

**Comment by Tourenathan-G5organisation** [comment]
Ok, thanks for your help @eneim
