### ISSUE TITLE
Play auto next

### ISSUE THREAD

**Issue by aderinto05** [eneim/toro#374]
I use this version : im.ene.toro3:toro:3.5.2
Can this version use auto next in Playable? 
When I use im.ene.toro2:toro-extended:2.3.0 for auto next, it's not compatible.

What kind of issue is this?

- [x] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

**Comment by eneim** [comment]
@aderinto05 How would you describe the "auto next" you mention here?

**Comment by aderinto05** [comment]
I had found solution thanks @eneim
