### ISSUE TITLE
cache videos from url

### ISSUE THREAD

**Issue by imran-samed** [eneim/toro#379]
I want to cache videos from url, videos are playing while is connected with internet, but videos are not playing in offline mode

  - [**3.6.1.2802** ] Toro version.

I used your facebook sample, and passed video URL instead of uri in **MediaUrl**

`public enum MediaUrl {
TEARS_OF_STEEL("http://xxxxxxxx.com/uploads/153634027269703.mp4", 2.4f), //
BIG_BUCK_BUNNY("http://xxxxxxxx.com/uploads/MOV_0003.mp4", 1.7777777778f), //
COSMOS_LAUNDROMATY("http://xxxxxxxx.com/uploads/153634027269703.mp4", 2.4f), //
;

private final String url;
private final float ratio;

MediaUrl(String url, float ratio) {
    this.url = url;
    this.ratio = ratio;
}

MediaUrl(String url) {
    this(url, 1.7777777778f);
}

public String getUrl() {
    return url;
}

public Uri getUri() {
    return Uri.parse(this.url);
}

public float getRatio() {
    return ratio;
}

@Override
public String toString() {
    return name() + "{" + "url='" + url + '\'' + ", ratio=" + ratio + '}';
}
}`

**Comment by eneim** [comment]
@imran-samed You can construct your Cache instance without limit of the storage. See [this line](https://github.com/eneim/toro/blob/dev-v3/demo-exoplayer/src/main/java/toro/demo/exoplayer/DemoApp.kt#L43) but instead of using LeastRecentlyUsedCacheEvictor you can use NoOpCacheEvictor. But make sure to read the javadoc in that class for the warning.

**Comment by imran-samed** [comment]
@eneim  i tried that demo also, but  didn't work for me.

**Comment by imran-samed** [comment]
> See this line but instead of using LeastRecentlyUsedCacheEvictor you can use NoOpCacheEvictor.

while trying that, I'm getting  error.
See the ScreenShot

![image](https://user-images.githubusercontent.com/34650172/45422891-44868a00-b6af-11e8-9082-0381e100657e.png)

**Comment by eneim** [comment]
@imran-samed About the error, it says you may have more than accepted number of parameter. The "NoOpCacheEvictor" doesn't have a parameterized constructor ...

**Comment by eneim** [comment]
Let me check the NoOpCacheEvictor again on my demo.

**Comment by eneim** [comment]
@imran-samed Can you share with me the ViewHolder where you implement ToroPlayer? Please make sure you have the right Config in your Helper class.

**Comment by imran-samed** [comment]
I'm using user **demo-exoplayer** also, its same, nothing is changed.

**Comment by eneim** [comment]
@imran-samed Having the following works in my demo, at least for one video of length 1:41

```Kotlin
if (helper == null) helper = ExoPlayerViewHelper(this, videoUri!!, null, DemoApp.config!!)
```

```Kotlin (DemoApp)
val cache = SimpleCache(
        File(filesDir.path + "/toro_cache"),
        // LeastRecentlyUsedCacheEvictor(cacheFile)
        NoOpCacheEvictor()
    )
    config = Config.Builder()
        .setMediaSourceBuilder(MediaSourceBuilder.LOOPING)
        .setCache(cache)
        .build()
```

**Comment by eneim** [comment]
<img width="454" alt="screen shot 2018-09-12 at 21 29 41" src="https://user-images.githubusercontent.com/1776230/45424966-00a57c00-b6d3-11e8-9d45-20827221db51.png">

Above is how the cache is done. Can you try that again and use Android Studio to double check the cache folder?

**Comment by imran-samed** [comment]
@eneim  ok, let me try this.

**Comment by imran-samed** [comment]
@eneim Thanks Man, its working absolutely fine.

**Comment by omidraha** [comment]
Java code:
```
long cacheFile = 10 * 1024 * 1024; // 10MB

SimpleCache cache = new SimpleCache(new File(getCacheDir().getAbsolutePath() + "/media_cache"),
		new LeastRecentlyUsedCacheEvictor(cacheFile));

config = new Config.Builder()
		.setMediaSourceBuilder(MediaSourceBuilder.DEFAULT)
		.setCache(cache)
		.build();

ExoCreator exoCreator = ToroExo.with(this).getCreator(config);

```
