### ISSUE TITLE
Add the ability for developers to request audio focus

### ISSUE THREAD

**Issue by kikin81** [eneim/Toro#38]
In my implementation I playback muted videos in a recycler view.
Unfortunately, if the user has another background music playing, the Toro video player will request focus automatically when the video is ready.

I would like the ability to not do this in order to provide auto playing muted videos without interrupting the user's music from another app.

**Comment by eneim** [comment]
Hi @kikin81 , Would #40 solve your problem? I'm not really good at audio focusing and background video playback, so please take a look and give feedback. I will learn more and give my best effort to support.

**Comment by kikin81** [comment]
Hey @eneim, I work with @wemped and his PR satisfied my request.
Thanks for taking a look.
