### ISSUE TITLE
Videos don't auto-play when setNestedScrollingEnabled is false on the container

### ISSUE THREAD

**Issue by reshthedev** [eneim/toro#382]
What kind of issue is this?

- [x] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [ ] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by reshthedev** [comment]
Hello @eneim , many thanks for this library..
I tried using the container nested in a scrollview to load videos and it was so laggy and it doesn't play the last video on the list of URLs i passed, so i tried using the container.setNestedScrollingEnabled(false); and now it doesn't play at all and i don't understand why. Please help me as i'm still new to android development..

**Comment by reshthedev** [comment]
> @reshthedev Is is a must for you to nest a RecyclerView/Container into a ScrollView? Because it is a known bad practice. Not just my lib but anyone will not suggest you to do so. What is your ultimate use case?
> 
> Setting the scrolling to false will disable Container to observe the scrolling event, which will disable the library ...

Many thanks sir.. But i'm trying to implement the recyclerview on a profile page just like Facebook profile page on android which i can scroll to the posts after viewing the profile details of the user..

I'm thinking of switching to the CollapsingToolbarLayout to show the profile details and the Toro container under it.. Could you help me suggest another way to implement my design?

**Comment by eneim** [comment]
@reshthedev Depending on how much experience in Android you have, I think you should try CollapsingToolbarLayout first. See if it works.

**Comment by reshthedev** [comment]
> @reshthedev Depending on how much experience in Android you have, I think you should try CollapsingToolbarLayout first. See if it works.

Finally fixed it using CollapsingToolbarLayout and the recyclerview below it.. Thanks for the library, looking forward to seeing more new updates.
