### ISSUE TITLE
'Cannot access Hide' compilation error  

### ISSUE THREAD

**Issue by Mahmoud-S-Ali** [eneim/toro#388]
Hi eneim, Thanks for this great library. I'm getting a compilation error "cannot access Hide" only on versions higher than 3.5.2.

![capture](https://user-images.githubusercontent.com/13187144/47510076-abcf5680-d877-11e8-9d29-18bf79b4ef4a.PNG)

**Comment by eneim** [comment]
@Mahmoud-S-Ali Hmm, I think Glide annotation processing doesn't work well. Can you clean your Project and make sure kotlin version are matched?

**Comment by Mahmoud-S-Ali** [comment]
It worked fine after upgrading to sdk 28 and to glide version 4.8.0. Thanks
