### ISSUE TITLE
Audio Continue play after deleting video from recycler view

### ISSUE THREAD

**Issue by vikasgupta4190** [eneim/toro#393]
What kind of issue is this?

- [ ] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [x] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [x] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by vikasgupta4190** [comment]
Audio Continue Play After Deleting Video from List and notify adapter .

**Comment by eneim** [comment]
@vikasgupta4190 Can you share with me how you remove it and how you notice the Adapter? Does Audio keep playing for long after that?

**Comment by vikasgupta4190** [comment]
This is my Holder class -


public class KhojPostHolder extends RecyclerView.ViewHolder implements ToroPlayer  , ToroPlayer.EventListener {
    ToroPlayerHelper helper;

    @Nullable private Uri mediaUri;

    public PlayerView playervideo;

    public KhojPostHolder(View view) {
        super(view);
 
        playervideo;= view.findViewById(R.id.playervideo);

    
    }
    @NonNull @Override public View getPlayerView() {
        return homeadaptervideo;
    }

    @NonNull @Override public PlaybackInfo getCurrentPlaybackInfo() {
        return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
    }

    @Override
    public void initialize(@NonNull Container container, @NonNull PlaybackInfo playbackInfo) {
        if (helper == null) {
            if (mediaUri != null) helper = new ExoPlayerViewHelper(this, mediaUri);
        }

        if (helper != null) {
            helper.addPlayerEventListener(this);
            helper.initialize(container, playbackInfo);
        }
    }

    @Override public void play() {
        if (helper != null) helper.play();
    }

    @Override public void pause() {
        if (helper != null) helper.pause();
    }

    @Override public boolean isPlaying() {
        return helper != null && helper.isPlaying();
    }

    @Override public void release() {
        if (helper != null) {
            helper.removePlayerEventListener(this);
            helper.release();
            helper = null;
        }
    }

    @Override public boolean wantsToPlay() {
        return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
    }

    @Override public int getPlayerOrder() {
        return getAdapterPosition();
    }

    @Override public String toString() {
        return "ExoPlayer{" + hashCode() + " " + getAdapterPosition() + "}";
    }
    @Override public void onBuffering() {
        posterView.setVisibility(View.VISIBLE);
    }

    @Override public void onPlaying() {
        posterView.setVisibility(View.GONE);
    }

    @Override public void onPaused() {
        posterView.setVisibility(View.VISIBLE);
    }

    @Override public void onCompleted() {
        posterView.setVisibility(View.GONE);
    }

   public void bind(Uri media) {
        this.mediaUri = media;
       posterView.setVisibility(View.VISIBLE);
        posterView.setImageDrawable(itemView.getResources().getDrawable(R.drawable.progress_animation));
    }
}


This is my adapter class -



    @Override
    public KhojPostHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.postfeeddemo, parent, false);

        return new KhojPostHolder(itemView);
    }

    @Override
    public void onBindViewHolder(final KhojPostHolder holder,final int position) {

        final PostPojoData postPojo = postlist.get(position);
        // delete portaion

        if (postPojo.getUserid().equals(userid)) {
            holder.editAndDeleteOption.setVisibility(View.VISIBLE);
            holder.editAndDeleteOption.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    //creating a popup menu
                    PopupMenu popup = new PopupMenu(context, holder.editAndDeleteOption);
                    //inflating menu from xml resource
                    popup.inflate(R.menu.main);


                    //adding click listener

                    popup.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener() {
                        @Override
                        public boolean onMenuItemClick(final MenuItem menuitem) {
                            switch (menuitem.getItemId()) {
                                case R.id.delete:
                                    AlertDialog.Builder builder;
                                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                                        builder = new AlertDialog.Builder(context, android.R.style.Theme_Material_Dialog_Alert);
                                    } else {
                                        builder = new AlertDialog.Builder(context);
                                    }
                                    builder.setTitle("Delete Post")
                                            .setMessage("Are you sure you want to delete this entry?")
                                            .setPositiveButton(android.R.string.yes, new DialogInterface.OnClickListener() {
                                                public void onClick(DialogInterface dialog, int which) {
                                                    ApiInterface apiService =
                                                            ApiClient.getClient().create(ApiInterface.class);

                                                    Call<DeletePojo> userdata = apiService.deletepost(postPojo.getID());
                                                    userdata.enqueue(new Callback<DeletePojo>() {
                                                        @Override
                                                        public void onResponse(Call<DeletePojo> call, Response<DeletePojo> response) {

                                                            if (!response.body().getError()) {

                                                                postlist.remove(postlist.get(position));
                                                                notifyDataSetChanged();
                                                                Toast.makeText(context, ""+response.body().getMessage() , Toast.LENGTH_SHORT).show();


                                                            } 

                                                        }

                                                        @Override
                                                        public void onFailure(Call<DeletePojo> call, Throwable t) {
                                                            Log.e("Delete Post", "" + t.getMessage());
                                                        }
                                                    });

                                                }
                                            })
                                            .setNegativeButton(android.R.string.no, new DialogInterface.OnClickListener() {
                                                public void onClick(DialogInterface dialog, int which) {
                                                    // do nothing
                                                }
                                            })
                                            .setIcon(android.R.drawable.ic_dialog_alert)
                                            .show();

                                    break;
                            }
                            return false;
                        }
                    });
                    //displaying the popup
                    popup.show();

                }
            });
        }
     

notify code here 
postlist.remove(position);                         // post is list type
notifyDataSetChanged();
                            
why this problem occur .??

**Comment by vikasgupta4190** [comment]
<com.google.android.exoplayer2.ui.PlayerView
                android:id="@+id/playervideo"
                android:layout_width="match_parent"
                android:layout_height="250dp"
                android:layout_marginTop="4dp"
                android:layout_marginBottom="4dp"
                android:visibility="gone"
                android:minHeight="250dp"
                app:resize_mode="fill"
                app:surface_type="texture_view"
                app:use_controller="false"
                >
                <android.support.v7.widget.AppCompatImageView
                    android:id="@+id/posterView"
                    android:layout_width="match_parent"
                    android:layout_height="250dp"
                    android:adjustViewBounds="true"
                    android:scaleType="centerCrop"
                    />
            </com.google.android.exoplayer2.ui.PlayerView>

**Comment by vikasgupta4190** [comment]
@Override
    public void onBindViewHolder(final KhojPostHolder holder,final int position) {

        final PostPojoData postPojo = postlist.get(position);
        // delete portaion
        holder.bind(null);

 if (isVideoFile(arrayList.get(0))) {


             
                    holder.playervideo.setVisibility(View.VISIBLE);
                   
                    holder.bind(Uri.parse(arrayList.get(0).toString()));

                }

}


//  note:- If i set holder.bind(null) at starting onbindviewholder then problem solved. How can i solve this issue using other way ??

**Comment by vikasgupta4190** [comment]
Can you please help me. Thank for make this awesome library.

**Comment by eneim** [comment]
Hey. Sure. I’m looking into it. It’s Monday here so I need to secure a few hours first.

Just want to make sure, on the UI the ViewHolder is correctly disappear right? And if possible please try with “notifyItemRemove...” call and see if it is better?

I will still investigate with all case.

**Comment by eneim** [comment]
@vikasgupta4190 Can you share with me a video Url that can produce this issue? Via email is OK: nam@ene.im . Tried with my default URL and it works fine :(.

**Comment by vikasgupta4190** [comment]
Issue solve thank you very much .

**Comment by eneim** [comment]
@vikasgupta4190 Sounds great. Will close the issue. If you find anything weird just let me know!
