### ISSUE TITLE
video not pause when hide fragment

### ISSUE THREAD

**Issue by javacl** [eneim/toro#399]
Hello. i use this lastest version of toro in my app for autoplayerRecyclerview

 implementation "im.ene.toro3:toro:3.6.1.2802"
 implementation "im.ene.toro3:toro-ext-exoplayer:3.6.1.2802"

i want to make application like instagram. now i have multi fragments when i play video for example in my homeFragment now i want go to ProfileFragment. i want pause video in my Home fragment but when i hide fragment video not paused and it's nothing for pause video and unregister recyclerview

![photo_2018-12-03_14-24-58](https://user-images.githubusercontent.com/45559398/49369828-987d9980-f707-11e8-8f95-3db6a944eb64.jpg)
![photo_2018-12-03_14-25-01](https://user-images.githubusercontent.com/45559398/49369838-9fa4a780-f707-11e8-8508-002db5c3c579.jpg)

**Comment by eneim** [comment]
Can you try container.setPlayerSelector(PlayerSelector.NONE) when you change/switch the fragments?

**Comment by javacl** [comment]
> Can you try container.setPlayerSelector(PlayerSelector.NONE) when you change/switch the fragments?

thanks men you solved my life xD >3
