### ISSUE TITLE
Video got Black and SurfaceView Instead of TextureView

### ISSUE THREAD

**Issue by charlizesmith** [eneim/toro#408]
What kind of issue is this?
**No Video is Shown. Video is getting black and only audio is played**

Toro version: 3.6.2.2804

Android version : 28

Device name : Mi Note 4

Source code : 
I have integrated  toro library in our app Successfully. It working awesome on some devices. But, when i install the same app on redmi note 4 device for testing, video got black and only audio was coming. There was a **out of memory error.** I searched for some solution and i got with 

**android:largeHeap="true"
 android:hardwareAccelerated="false"**

But as soon as i added this lines in Manifest file, it was showing TextureView can not be used. So i chanege, TexttureView to SurfaceView and is working fine right now. **Why it was showing memory error on note 4 device? Is there any difference if i used SurfaceView instead of TextureView?**

Waiting for your reply. please help. Thank you.

**Comment by eneim** [comment]
@charlizesmith 

TextureView requires 'android:hardwareAccelerated' to be true.

I don't have a Mi Note so may not  be able to reproduce it successfully. If you can send me the logcat of the 'Out of memory error' it will be helpful.

**Comment by charlizesmith** [comment]
The issue was due to drawable which i used as default tumbnail image for video. 
Thank you for the help.
