### ISSUE TITLE
Item taking too long to load

### ISSUE THREAD

**Issue by android4canada** [eneim/toro#424]
Hello,
I followed the BasicDemo and I have URLs for 2 videos on the server. I am using Toro with Exo player
I noticed that the recycler view takes long time show the contents (upon start). And when it shows the content, the video starts playing.

1) Is it trying to download the whole video before playing it? Can I change that?
2) Shouldn't the contents such as texts  and thumbnail be shown right away? I have all the contents as part of VideoViewHolder ( didn't separate it into two).

Thank you so much

**Comment by android4canada** [comment]
Figured it out. I need to use values for LoadControl to enable buffering

**Comment by saadbzu** [comment]
android4canada I also face the same issue how you solve the problem please help
