### ISSUE TITLE
Videos/itesm are repeating after the 3rd item

### ISSUE THREAD

**Issue by android4canada** [eneim/toro#432]
Hello,
I am facing a weird behaviour. I have a list of 10 items/videos.  When you start the first item/video occupies the full screen. As you scroll, the second item is loaded, then the third item is loaded, but beyond 3rd items it is loading the 1st item in the list, then 2nd and so on. I am just just seeing the first 3 items duplicated until I hit the last position.

Why is this? I made a debug breakpoint and noticed that the onBindView is called 3 times only and is not called anymore as you scroll down or up. PLEASE PLEASE help a fellow developer

Here is my feedAdapter
```
@Override
    public VideoViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(context).inflate(R.layout.feed_rv_row, parent, false);
        return new VideoViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull FeedAdapter.VideoViewHolder holder, int position) {
        final VideoPostResults videoPostResult = items_arr.get(position);
..
.
.
}
```

```
Here is my Viewholder
 public class VideoViewHolder extends ViewHolder implements ToroPlayer {


        PlayerView playerView;



        @Nullable public ExoPlayerViewHelper helper;
        @Nullable public Uri mediaUri;

        VideoViewHolder(View itemView) {
            super(itemView);
            playerView = itemView.findViewById(R.id.videoView);
        }



        @NonNull @Override
        public View getPlayerView() {
            return this.playerView;
        }

        @NonNull @Override
        public PlaybackInfo getCurrentPlaybackInfo() {
            return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
        }

        @Override
        public void initialize(@NonNull Container container, @NonNull PlaybackInfo playbackInfo) {
 if (mediaUri == null) throw new IllegalStateException("mediaUri is null.");
            if (helper == null) {
                DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
                TrackSelection.Factory videoTrackSelectionFactory =
                        new AdaptiveTrackSelection.Factory(bandwidthMeter);
                TrackSelector trackSelector =
                        new DefaultTrackSelector(videoTrackSelectionFactory);
                LoadControl loadControl = new DefaultLoadControl(
                        new DefaultAllocator(true, 16),
                        GlobalVar.VideoPlayerConfig.MIN_BUFFER_DURATION,
                        GlobalVar.VideoPlayerConfig.MAX_BUFFER_DURATION,
                        GlobalVar.VideoPlayerConfig.MIN_PLAYBACK_START_BUFFER,
                        GlobalVar.VideoPlayerConfig.MIN_PLAYBACK_RESUME_BUFFER, -1, true);
                DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
                        Util.getUserAgent(context, "Chirp"), bandwidthMeter);
                MediaSourceBuilder mediaSourceBuilder = MediaSourceBuilder.LOOPING;
                Config config = new Config.Builder().setLoadControl(loadControl).setDataSourceFactory(dataSourceFactory).setMediaSourceBuilder(mediaSourceBuilder).build();
                helper = new ExoPlayerViewHelper(this, mediaUri, null, config);


                helper.initialize(container, playbackInfo);
}

```

Offcourse I cut a lot of "non impacting code". But this is weird!! Can you suggest anything?

Thank you

**Comment by android4canada** [comment]
Any comments? I am really struggling with this issue :(

**Comment by eneim** [comment]
@android4canada sorry did not see this issue. 

```
if (helper == null) { }
```

Here you should only **create the helper** if it is not created yet.

```
helper.initialize(container, playbackInfo);
```

Must be called outside of the creation. Thinking that: if the ViewHolder is reused, but the helper instance is there, it will never be initialized for new data.

// I have no idea why the onBindView is not called, but it is not implemented by toro ...

**Comment by android4canada** [comment]
Thank you for your response. Since the onBindView is not called upon scroll, it is making me think that that something with layouting of Toro. OnBindView gets called when layout is updated and visibility is changed. I actually put a break point inside the Container on child attached  and noticed that that the break point is being hit on every scroll but something seems to be blocking onbindview from being called and just loading the old view instead

**Comment by android4canada** [comment]
I found the reason. You are right, it is not due to your library. It is due to the fact that I used the sample code which has "set stable Id" and it was not refreshing views. By removing it, it worked!

**Comment by eneim** [comment]
@android4canada good to hear that.
