### ISSUE TITLE
Rewind/Restart video when it is finished/ended

### ISSUE THREAD

**Issue by bstillitano** [eneim/toro#435]
What kind of issue is this?

- [x] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [ ] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

I am wanting to do the following:
1. When video finished playing perform a function. Some sort of listener on the video to detect when video starts/stops playing.
2. Call a function to seek through the video. Something along the lines of 
```
fun helper.seekTo(position: Int = 0)
```

**Comment by eneim** [comment]
@bstillitano in current version, you can listen to ``onCompleted`` event, and use your PlayerView to access the ``ExoPlayer`` instance and seek manually. It is a bit dirty trick, in next update I will add a method to the Helper to help you update the PlaybackInfo. Please try this suggestion first.

**Comment by bstillitano** [comment]
@eneim what what I set the onCompleted event on? The playerView or the ExoPlayerViewHelper?

**Comment by bstillitano** [comment]
@eneim nevermind, I figured it out. Thanks for the advice and looking forward to the update that makes this a little easier.

Example below:

```
helper?.addPlayerEventListener(object : ToroPlayer.EventListener {
            override fun onBuffering() {
                //Do something
            }

            override fun onFirstFrameRendered() {
                //Do something
            }

            override fun onPlaying() {
                //Do something
            }

            override fun onPaused() {
                //Do something
            }

            override fun onCompleted() {
                //Do something
            }
        })
```
