### ISSUE TITLE
Get current video playing progress

### ISSUE THREAD

**Issue by RockyLin** [eneim/toro#437]
What kind of issue is this?
Toro version. latest_release = '3.6.2.2804'

@eneim 
I'm implementing feature like facebook timeline.  How to get the playing progress while video is playing? Thanks a lot!
~~~
<com.google.android.exoplayer2.ui.PlayerView
                android:id="@+id/video_player"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/colorLightGray"
                app:resize_mode="zoom"
                app:surface_type="texture_view"
                app:use_controller="false" />
 ~~~

**Comment by eneim** [comment]
@RockyLin you can set use_controller to true and I think you can customize the UI of the controller. Please take a look at PlayerView document (ExoPlayer library).

**Comment by RockyLin** [comment]
@eneim Thanks a lot!
