### ISSUE TITLE
Pause all video 

### ISSUE THREAD

**Issue by anonym2** [eneim/toro#441]
HI I'm using your library for  my custom Story player like Instagram , Now I need to pause video when user press the screen and play it when he left  ,  what is the method for doi that ?

**Comment by eneim** [comment]
@anonym2 You can pause all Video by [setting the PlayerSelector](https://github.com/eneim/toro/blob/release/v3.6.2.2903/toro-core/src/main/java/im/ene/toro/widget/Container.java#L354) to something that [selects nothing](https://github.com/eneim/toro/blob/release/v3.6.2.2903/toro-core/src/main/java/im/ene/toro/PlayerSelector.java#L139).

**Comment by anonym2** [comment]
Thanks
