### ISSUE TITLE
New Issue 

### ISSUE THREAD

**Issue by vijayakumarksv** [eneim/toro#451]
When i added 
**implementation 'im.ene.toro3:toro:3.6.2.2804'
implementation 'im.ene.toro3:toro-ext-exoplayer:3.6.2.2804'**
those library to got this below error,
class file for com.google.android.gms.internal.zzbgl not found

**Comment by eneim** [comment]
@vijayakumarksv You will need exoplayer as dependency as well.

**Comment by vijayakumarksv** [comment]
I need more clarification about this. Because I couldn't implement your plugin in my project.

**Comment by eneim** [comment]
@vijayakumarksv Currently toro-exoplayer depends on ExoPlayer library (full package, but on production the unnecessary things will be stripped out by R8/Proguard). So you also need to include them in the build.gradle.

**Comment by vijayakumarksv** [comment]
For toro exoplayer build.gradle right?

**Comment by eneim** [comment]
@vijayakumarksv Yes. It use ExoPlayer so it requires exoplayer as dependency.
