### ISSUE TITLE
videos not resume.

### ISSUE THREAD

**Issue by saeid130** [eneim/toro#453]
my project works correctly but when videos off from screen did not resume start again.

**Comment by eneim** [comment]
@saeid130 can you share the source code that can reproduce the issue?

**Comment by saeid130** [comment]
that's my adapter code and VideoViewHolder that holder i'm using Toro: 
`public class PostAdapter extends RecyclerView.Adapter {

    ArrayList<Integer> types = new ArrayList<Integer>();
    ArrayList<String> names = new ArrayList<String>();
    ArrayList<Boolean> likes = new ArrayList<Boolean>();
    ArrayList<Boolean> tags = new ArrayList<Boolean>();
    ArrayList<Boolean> extend = new ArrayList<Boolean>();
    ArrayList<String> urls = new ArrayList<String>();
    //ArrayList<ExpandableStatusFix> fixes = new ArrayList<ExpandableStatusFix>();
    Context context;
    Typeface font;
    String text;
    Spannable s;
    Connection connect;

    public PostAdapter(Context context,Typeface font ,ArrayList<Integer> types, ArrayList<Boolean> likes, ArrayList<String> names, ArrayList<String> urls){
        this.context = context;
        this.types = types;
        this.likes = likes;
        this.names = names;
        this.urls = urls;
        this.font = font;
        for (int i=0; i < this.types.size() ; i++){
            tags.add(false);
            extend.add(false);
        }
        text = context.getString(R.string.lorem_description);
    }

    @NonNull
    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view;
        switch (viewType){
            case 1:
                view = LayoutInflater.from(context).inflate(R.layout.post_pic,null);
                return new ImageViewHolder(view);
            case 2:
                view = LayoutInflater.from(context).inflate(R.layout.post_video,null);
                return new VideoViewHolder(view);
        }
        return null;
    }
    @Override
    public int getItemViewType(int position) {
        switch (types.get(position)){
            case 1:
                return 1;
            case 2:
                return 2;
            default:
                return position;
        }
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getItemCount() {
        return types.size();
    }

    @SuppressLint("ClickableViewAccessibility")
    @Override
    public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
        switch (types.get(position)){
            case 1:

                ((ImageViewHolder)holder).user_name.setText(names.get(position));
                Picasso.get().load(urls.get(position)).into(((ImageViewHolder)holder).post_picture);

                if (likes.get(position)){
                    ((ImageViewHolder)holder).like.setImageResource(R.drawable.like_);
                }else {
                    ((ImageViewHolder)holder).like.setImageResource(R.drawable.like);
                }

                if (tags.get(position)){
                    ((ImageViewHolder)holder).listView.setVisibility(View.VISIBLE);
                }else {
                    ((ImageViewHolder)holder).listView.setVisibility(View.GONE);
                }

                if (extend.get(position)){
                  expandTextView(((ImageViewHolder)holder).explain);
                } else {
                    collapseTextView(((ImageViewHolder)holder).explain,2);
                }
                ((ImageViewHolder)holder).explain.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Boolean status = extend.get(position);
                        status = !status;
                        extend.set(position,status);
                        notifyDataSetChanged();
                    }
                });

                ((ImageViewHolder)holder).like.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        likeAnimate(holder,position);
                    }
                });

                ((ImageViewHolder)holder).post_picture.setOnClickListener(new View.OnClickListener() {
                    final int doubleClickTimeout = ViewConfiguration.getDoubleTapTimeout();
                    Handler handler = new Handler(Looper.getMainLooper());
                    long firstClickTime = 0L;
                    @Override
                    public void onClick(View view) {
                        long now = System.currentTimeMillis();

                        if (now - firstClickTime < doubleClickTimeout) {
                            handler.removeCallbacksAndMessages(null);
                            firstClickTime = 0L;
                            //on double
                            likeAnimate(holder,position);
                        } else {
                            firstClickTime = now;
                            handler.postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    // on single
                                    if (tags.get(position)){
                                        tags.set(position,false);
                                        notifyDataSetChanged();
                                    }else {
                                        tags.set(position,true);
                                        notifyDataSetChanged();
                                    }
                                    firstClickTime = 0L;
                                }
                            }, doubleClickTimeout);
                        }
                    }
                });


                break;
            case 2:
                ((VideoViewHolder)holder).user_name.setText(names.get(position));
                ((VideoViewHolder)holder).bind(Uri.parse(urls.get(position)));
                //((VideoViewHolder)holder).post_video.setVideoURI(Uri.parse(urls.get(position)));

                if (likes.get(position)){
                    ((VideoViewHolder)holder).like.setImageResource(R.drawable.like_);
                }else {
                    ((VideoViewHolder)holder).like.setImageResource(R.drawable.like);
                }

                if (extend.get(position)){
                    expandTextView(((VideoViewHolder)holder).explain);
                } else {
                    collapseTextView(((VideoViewHolder)holder).explain,2);
                }
                ((VideoViewHolder)holder).explain.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Boolean status = extend.get(position);
                        status = !status;
                        extend.set(position,status);
                        notifyDataSetChanged();
                    }
                });

                ((VideoViewHolder)holder).like.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        likeAnimate2(holder,position);
                    }
                });

                break;
        }
    }

    public class ImageViewHolder extends RecyclerView.ViewHolder{
        MyTextView user_name;
        CircleImageView profile_pic;
        ImageButton settings ;
        ImageView post_picture;
        VideoView post_video = null;
        ImageButton like;
        ImageButton comment;
        TextView explain;
        ImageView likeAnim;
        RecyclerView listView;

        public ImageViewHolder(View itemView) {
            super(itemView);

            user_name = (MyTextView) itemView.findViewById(R.id.username);
            explain = (TextView) itemView.findViewById(R.id.explain);
            profile_pic = (CircleImageView) itemView.findViewById(R.id.profile_pic);
            settings = (ImageButton) itemView.findViewById(R.id.setting);
            post_picture = (ImageView) itemView.findViewById(R.id.post_picture);
            //post_picture.setCornerRadiiDP(16, 16, 16, 16);
            like = (ImageButton) itemView.findViewById(R.id.like);
            comment = (ImageButton) itemView.findViewById(R.id.comment);
            likeAnim = (ImageView) itemView.findViewById(R.id.like_anim);
            listView = (RecyclerView) itemView.findViewById(R.id.recycler);

            explain.setTypeface(font);

            //explain.setTrimLength(100);

            //explain.setMovementMethod(LinkMovementMethod.getInstance());


            Linkify.TransformFilter filter = new Linkify.TransformFilter() {
                public final String transformUrl(final Matcher match, String url) {
                    return match.group();
                }
            };

            Pattern mentionPattern = Pattern.compile("@([A-Za-z0-9_-]+)");
            String mentionScheme = "http://www.twitter.com/";
            Linkify.addLinks(explain, mentionPattern, mentionScheme, null, filter);

            Pattern hashtagPattern = Pattern.compile("#([A-Za-z0-9_-]+)");
            String hashtagScheme = "http://www.twitter.com/search/";
            Linkify.addLinks(explain, hashtagPattern, hashtagScheme, null, filter);

            stripUnderlines(explain);
            explain.setMovementMethod(new TextViewClickMovement(new TextViewClickMovement.OnTextViewClickMovementListener() {
                @Override
                public void onLinkClicked(String linkText, TextViewClickMovement.LinkType linkType) {

                }

                @Override
                public void onLongClick(String text) {

                }
            },context));

            likeAnim.setVisibility(View.GONE);
            ArrayList <String> name = new ArrayList<String>();

            for (int j=0 ; j<5 ; j++){
                name.add("Saeid");
            }
            for (int j=0 ; j<5 ; j++){
                name.add("Armaghaan");
            }
            TagAdapter2 adapter = new TagAdapter2(context,name);
            LinearLayoutManager layoutManager
                    = new LinearLayoutManager(context, OrientationHelper.HORIZONTAL, false);
            listView.setLayoutManager(layoutManager);
            listView.setAdapter(adapter);

            Log.i("saeid","is created.");

            comment.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    view.getContext().startActivity(new Intent(view.getContext(),Comment.class));
                }
            });


        }
    }


    public class VideoViewHolder extends RecyclerView.ViewHolder implements ToroPlayer{
        MyTextView user_name;
        CircleImageView profile_pic;
        ImageButton settings ;
        SimpleExoPlayerView post_video;
        SimpleExoPlayerViewHelper helper;
        ImageButton like;
        ImageButton comment;
        TextView explain;
        ImageView likeAnim;
        Uri mediaUri;

        public VideoViewHolder(View itemView) {
            super(itemView);

            user_name = (MyTextView) itemView.findViewById(R.id.username);
            explain = (TextView) itemView.findViewById(R.id.explain);
            profile_pic = (CircleImageView) itemView.findViewById(R.id.profile_pic);
            settings = (ImageButton) itemView.findViewById(R.id.setting);
            post_video = (SimpleExoPlayerView) itemView.findViewById(R.id.post_video);
            like = (ImageButton) itemView.findViewById(R.id.like);
            comment = (ImageButton) itemView.findViewById(R.id.comment);
            likeAnim = (ImageView) itemView.findViewById(R.id.like_anim);

            explain.setTypeface(font);

            Linkify.TransformFilter filter = new Linkify.TransformFilter() {
                public final String transformUrl(final Matcher match, String url) {
                    return match.group();
                }
            };

            Pattern mentionPattern = Pattern.compile("@([A-Za-z0-9_-]+)");
            String mentionScheme = "http://www.twitter.com/";
            Linkify.addLinks(explain, mentionPattern, mentionScheme, null, filter);

            Pattern hashtagPattern = Pattern.compile("#([A-Za-z0-9_-]+)");
            String hashtagScheme = "http://www.twitter.com/search/";
            Linkify.addLinks(explain, hashtagPattern, hashtagScheme, null, filter);

            stripUnderlines(explain);
            explain.setMovementMethod(new TextViewClickMovement(new TextViewClickMovement.OnTextViewClickMovementListener() {
                @Override
                public void onLinkClicked(String linkText, TextViewClickMovement.LinkType linkType) {

                }

                @Override
                public void onLongClick(String text) {

                }
            },context));

            likeAnim.setVisibility(View.GONE);
            comment.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    view.getContext().startActivity(new Intent(view.getContext(),Comment.class));
                }
            });
        }

        @NonNull
        @Override
        public View getPlayerView() {
            return post_video;
        }

        @NonNull
        @Override
        public PlaybackInfo getCurrentPlaybackInfo() {
            return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
        }

        @Override
        public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
            if (helper == null) {
                helper = new SimpleExoPlayerViewHelper(container, this, mediaUri);
            }
            helper.initialize(playbackInfo);
        }

        @Override
        public void play() {
            if (helper != null) helper.play();
        }

        @Override
        public void pause() {
            if (helper != null) helper.pause();
        }

        @Override
        public boolean isPlaying() {
            return helper != null && helper.isPlaying();
        }

        @Override
        public void release() {
            if (helper != null) {
                helper.release();
                helper = null;
            }
        }

        @Override
        public boolean wantsToPlay() {
            return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
        }

        @Override
        public int getPlayerOrder() {
            return getAdapterPosition();
        }

        void bind(Uri media) {
            this.mediaUri = media;
        }
    }

    private void stripUnderlines(TextView textView) {
        Spannable s = new SpannableString(textView.getText());
        URLSpan[] spans = s.getSpans(0, s.length(), URLSpan.class);
        for (URLSpan span: spans) {
            int start = s.getSpanStart(span);
            int end = s.getSpanEnd(span);
            s.removeSpan(span);
            span = new URLSpanNoUnderline(span.getURL());
            s.setSpan(span, start, end, 0);
        }
        textView.setText(s);
    }

    private class URLSpanNoUnderline extends URLSpan {
        public URLSpanNoUnderline(String url) {
            super(url);
        }
        @Override public void updateDrawState(TextPaint ds) {
            super.updateDrawState(ds);
            ds.setUnderlineText(false);
        }
    }

    private void expandTextView(TextView tv){
        ObjectAnimator animation = ObjectAnimator.ofInt(tv, "maxLines", tv.getLineCount());
        animation.setDuration(200).start();
    }

    private void collapseTextView(TextView tv, int numLines){
        ObjectAnimator animation = ObjectAnimator.ofInt(tv, "maxLines", numLines);
        animation.setDuration(200).start();
    }

    public static Bitmap scaleDown(Bitmap realImage, float maxImageSize,
                                   boolean filter) {
        float ratio = Math.min(
                (float) maxImageSize / realImage.getWidth(),
                (float) maxImageSize / realImage.getHeight());
        int width = Math.round((float) ratio * realImage.getWidth());
        int height = Math.round((float) ratio * realImage.getHeight());

        Bitmap newBitmap = Bitmap.createScaledBitmap(realImage, width,
                height, filter);
        return newBitmap;
    }

    public void likeAnimate(RecyclerView.ViewHolder holder,int position){
        ((ImageViewHolder)holder).like.setImageResource(R.drawable.like_);
        likes.set(position,true);
        Animation animation = AnimationUtils.loadAnimation(context, R.anim.fade_in);
        Animation animation2 = AnimationUtils.loadAnimation(context, R.anim.fade_out);
        ((ImageViewHolder)holder).likeAnim.setVisibility(View.VISIBLE);
        animation2.setAnimationListener(new Animation.AnimationListener() {
            @Override
            public void onAnimationStart(Animation animation) {

            }

            @Override
            public void onAnimationEnd(Animation animation) {
                ((ImageViewHolder)holder).likeAnim.setVisibility(View.GONE);
            }

            @Override
            public void onAnimationRepeat(Animation animation) {

            }
        });
        ((ImageViewHolder)holder).likeAnim.startAnimation(animation);
        ((ImageViewHolder)holder).likeAnim.startAnimation(animation2);
        notifyDataSetChanged();
    }
    public void likeAnimate2(RecyclerView.ViewHolder holder,int position){
        ((VideoViewHolder)holder).like.setImageResource(R.drawable.like_);
        likes.set(position,true);
        Animation animation = AnimationUtils.loadAnimation(context, R.anim.fade_in);
        Animation animation2 = AnimationUtils.loadAnimation(context, R.anim.fade_out);
        ((VideoViewHolder)holder).likeAnim.setVisibility(View.VISIBLE);
        animation2.setAnimationListener(new Animation.AnimationListener() {
            @Override
            public void onAnimationStart(Animation animation) {

            }

            @Override
            public void onAnimationEnd(Animation animation) {
                ((VideoViewHolder)holder).likeAnim.setVisibility(View.GONE);
            }

            @Override
            public void onAnimationRepeat(Animation animation) {

            }
        });
        ((VideoViewHolder)holder).likeAnim.startAnimation(animation);
        ((VideoViewHolder)holder).likeAnim.startAnimation(animation2);
        notifyDataSetChanged();
    }
}`
