### ISSUE TITLE
animation is restart the videos

### ISSUE THREAD

**Issue by saeid130** [eneim/toro#454]
I'm using toro in recyclerView everything is great but when any animation loads in item view video are restart. my animation like this: 

`private void expandTextView(TextView tv){
        ObjectAnimator animation = ObjectAnimator.ofInt(tv, "maxLines", tv.getLineCount());
        animation.setDuration(200).start();
    }`

anybody have an idea

**Comment by eneim** [comment]
@saeid130 can you share a screen record of the behavior? Cannot imagine how animating a TextView affect the Video playback.

**Comment by saeid130** [comment]
I have notifyDataSetChanged(); after my animation and that's causing video restart. It solved thank you.
