### ISSUE TITLE
Helper - Play Method Error - Not Play

### ISSUE THREAD

**Issue by lucazin** [eneim/toro#457]
What kind of issue is this?

- [ ] Bug:  When start loading and play the video i have this error here, please help me..
i try everything.. change version.. look at demo.. and nothing

  - [ ] Toro version:

`  implementation 'im.ene.toro3:toro:3.6.2.2804'
    implementation 'im.ene.toro3:toro-ext-exoplayer:3.6.2.2804'
    implementation ("com.google.android.exoplayer:exoplayer:2.9.3") {
        exclude group: 'com.android.support'
    }`

  - [ ] Android version 9.0

  - [ ] Device name :A70

  - [ ] Source code:

` public class ListaCandidatosVH extends RecyclerView.ViewHolder implements ToroPlayer {
    
        ImageView fullscreen;
    
        PlayerView playerView;
        ExoPlayerViewHelper helper;
        Uri mediaUri;
        TextView state;
        ImageView img_vol,img_playback;
        boolean isMuted; //to mute/un-mute video (optional)
    
        private final Playable.EventListener listener = new Playable.DefaultEventListener() {
            @Override public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                super.onPlayerStateChanged(playWhenReady, playbackState);
                state.setText(format(Locale.getDefault(), "STATE: %d・PWR: %s", playbackState, playWhenReady));
            }
        };
       
        
        public ListaCandidatosVH(View view)
        {
            super(view);
    
            img_vol = (ImageView) view.findViewById(R.id.img_vol);
            fullscreen = (ImageView) view.findViewById(R.id.fullscreen);
            playerView = (PlayerView ) itemView.findViewById(R.id.playerView);
        }
    
        @NonNull
        @Override
        public View getPlayerView() {
            return playerView;
        }
    
        @NonNull
        @Override
        public PlaybackInfo getCurrentPlaybackInfo() {
            return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
        }
    
        @Override
        public void initialize(@NonNull Container container, @NonNull PlaybackInfo playbackInfo) {
            if (helper == null)
            {
                helper = new ExoPlayerViewHelper (container, this, mediaUri);
                helper.addEventListener(listener);
                
            }
            helper.initialize(container,playbackInfo);
        }
    
        @Override
        public void play() {
            if (helper != null)
            {
                helper.play();
                helper.setVolume(0f);
                isMuted = true;
            }
        }
    
        @Override
        public void pause() {
            if (helper != null) helper.pause();
        }
    
        @Override
        public boolean isPlaying() {
            return helper != null && helper.isPlaying();
        }
    
        @Override
        public void release() {
            if (helper != null) {
                helper.removeEventListener(listener);
                helper.release();
                helper = null;
            }
        }
    
        @Override
        public boolean wantsToPlay() {
            return ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= 0.85;
        }
    
        @Override
        public int getPlayerOrder() {
            return getAdapterPosition();
        }
    
        void bind(Uri media) {
            this.mediaUri = media;
        }
    }
    `

  - LogCat
`019-10-14 10:02:03.950 15308-15308/br.com.oneplace E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/RenderersFactory;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;Lcom/google/android/exoplayer2/drm/DrmSessionManager;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/br.com.oneplace-9vafVwIM0vqaS0u3JElNeQ==/base.apk!classes56.dex)
        at im.ene.toro.exoplayer.ToroExoPlayer.<init>(ToroExoPlayer.java:47)
        at im.ene.toro.exoplayer.DefaultExoCreator.createPlayer(DefaultExoCreator.java:118)
        at im.ene.toro.exoplayer.ToroExo.requestPlayer(ToroExo.java:153)
        at im.ene.toro.exoplayer.PlayableImpl.ensurePlayer(PlayableImpl.java:261)
        at im.ene.toro.exoplayer.PlayableImpl.ensureMediaSource(PlayableImpl.java:251)
        at im.ene.toro.exoplayer.PlayableImpl.play(PlayableImpl.java:101)
        at im.ene.toro.exoplayer.ExoPlayable.play(ExoPlayable.java:47)
        at im.ene.toro.exoplayer.ExoPlayerViewHelper.play(ExoPlayerViewHelper.java:108)`

**Comment by lucazin** [comment]
![aaa](https://user-images.githubusercontent.com/28266902/66754640-ce81c300-ee6c-11e9-8866-b4445384f564.jpeg)

**Comment by eneim** [comment]
@lucazin I think you have figure out the cause about ExoPlayer version. As ExoPlayer 2.10.x is out, i will update this library soon to meet the update.

**Comment by lucazin** [comment]
Thanks!

Em ter, 15 de out de 2019 às 01:38, Nam Nguyen Hoai <
notifications@github.com> escreveu:

**Comment by Krutika-chotara** [comment]
I am still getting same error. Is there any solution ?
