### ISSUE TITLE
How can i loop the video? Any Update in library?

### ISSUE THREAD

**Issue by saadbzu** [eneim/toro#459]
What kind of issue is this?

- [ ] Question. If so, declare clearly your **target** and your current implementation with code formatted in markdown.

- [ ] Bug report. If so, please supply the way to reproduce the issue, including addition information as follow:
  - [ ] Toro version.
  - [ ] Android version (can be found in Device info). **Rooted/Custom rom devices are not supported**.
  - [ ] Device name (eg: Nexus 5X, Samsung Galaxy S8)
  - [ ] Source code that can reproduce the issue (a snapshot is expected).
  - [ ] Logcat stack trace in case of fatal issue.
  
- [ ] Feature request. Start by telling me what problem you’re trying to solve. Don’t send pull requests to implement new features without first getting my support. Sometimes I leave features out on purpose to keep the project small.

- [ ] Other. Senseless issues are normally ignored. Please understand and cooperate.

**Comment by eneim** [comment]
@saadbzu If you are using latest version, you can use [this config](https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/ToroDemo.java#L40) to have Video looped.

**Comment by saadbzu** [comment]
@eneim Thank you for this update. I will try.

**Comment by froozesocial** [comment]
Sorry for opening this again, but where did you end up putting it? It didn't work in MainActivity for me. Do I need to put It in the Adapter? thanks.
