### ISSUE TITLE
Unable to Implement Container#onScrollStateChanged(int)

### ISSUE THREAD

**Issue by Prachethan** [eneim/toro#461]
implementation 'im.ene.toro3:toro:3.6.2.2903'
    implementation 'im.ene.toro3:toro-ext-exoplayer:3.6.2.2903'

Container not automatically playing videos. If we pinch manually on the container then only the particular video is playing.. Im using collapsing toolbar. So i tried to implement the Container#onScrollStateChanged(int). but i ended up with the following error. Im using AndroidX

error: constructor Behavior in class im.ene.toro.widget.Container.Behavior cannot be applied to given types;
required: androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior<Container>
found: androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior,<anonymous BehaviorCallback>
reason: actual and formal argument lists differ in length

**Comment by eneim** [comment]
There is a part in Readme addresses the issue with CollapsingToolbarLayout, please double check.

Also you can try latest alpha release as it is updated to use AndroidX without any function change.

**Comment by Prachethan** [comment]
I followed the code from readme.. but no luck... So implemented the recyclerview (container)with multiple view type. But scrolling is not smooth with collapsing toolbar. I tried following
1. Applied behavior to (recycler view)container within coordinator layout.
2. Nestedscrolling set to false.

Guide to achieve my goal. Thanks in advance 😊

**Comment by eneim** [comment]
@Prachethan Why do you need to "Nestedscrolling set to false"? Is your Container inside another NestedScrollView or anything? Do you have a chance to try the ``3.7.0.2905-A1`` release because it will work well with AndroidX?
