### ISSUE TITLE
no content provider error

### ISSUE THREAD

**Issue by deeppandya** [eneim/toro#47]
I am having below error when i try to load video in recyclerview. Some times it works some times my screen is empty.

W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /data/user/0/com.example.test/files/media/m_4083661.mp4
05-25 12:56:41.841 22929-22929/com.example.test W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

Could you please check it and please let me know ?

Thanks. great library

**Comment by eneim** [comment]
So you are loading file from your app's file folder? I will reproduce the issue to see if I could help.

**Comment by deeppandya** [comment]
Thanks for your quick response. i am having this problem since last week. and i checked everything in my code. 
I can send you my code if it helps you to speed things up.

let me know.

Thanks again

**Comment by eneim** [comment]
Thanks. It will be definitely helpful.

**Comment by deeppandya** [comment]
Hello,

Any update regarding this problem ? 
it's strange because some time it's working but sometimes i am having black screen. like i can see the video information like title,etc. but video is not playing and giving below error,

W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /data/user/0/com.example.test/files/media/m_4083661.mp4
05-25 12:56:41.841 22929-22929/com.example.test W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

In my code,
in the **bind** method of viewholder, 
mVideoView.setVideoURI(Uri.parse(mItem.getFile().getAbsolutePath()));

I am setting path of the file from the local file system.

Let me know if you need more information.

Thanks

**Comment by eneim** [comment]
@deeppandya So sorry. I'm focusing on some new stuff mean while having so less of time. I will spend time investigating this weekend.

**Comment by deeppandya** [comment]
Hello,

I am having below error,

06-07 11:07:42.144 19711-19711/com.app.example W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /data/user/0/com.app.example/files/media/m_228753.mp4
06-07 11:07:42.146 19711-19711/com.app.example W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
06-07 11:07:42.153 19711-19711/com.app.example W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /data/user/0/com.app.example/files/media/m_4083661.mp4
06-07 11:07:42.156 19711-19711/com.app.example W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

After having this error, if i open another activity and come back to video activity it's not working. everytime i have to kill the application and then if i open video activity, it's working.

Can you please help me with this ? this is the only i am having. everything working fine. 

Thanks

**Comment by eneim** [comment]
@deeppandya Ok sorry. I will actively working on this from now. Please post here your Activity class which plays the Videos. I want to see your setup for Toro and looking at other life cycle implementation. Thanks and sorry.

**Comment by eneim** [comment]
Could you try the following suggestions?

[This one](http://stackoverflow.com/questions/33434315/mediaplayer-fails-to-open-parsed-uri)

[And this one](https://groups.google.com/forum/m/#!topic/android-developers/I3L6-xvdcHQ).

It seems that this is either an issue of MediaPlayer class.

FYI I'm working on a new version which is built on top of ExoPlayer. So hopefully It could solve your problems better. Please let me know if these urls help.

**Comment by jmartinez360** [comment]
Hello I am having the same error with this:
Uri uri = Uri.parse(((Video) object).getUrl());
      mVideoView.setVideoURI(uri);

**Comment by deeppandya** [comment]
hey,
try to create a content provider and instead of using Uri.parse, use content provider to get the files. it solved the issue for me.

**Comment by deeppandya** [comment]
look at below link,
https://developer.android.com/reference/android/support/v4/content/FileProvider.html

**Comment by eneim** [comment]
@deeppandya It's good to hear that. Generally, Uri can be used for online content too, so using FileProvider could not solve every issue. Using it for local file is the right way I guess. Hm using ```Uri.parse(someUrl)``` is used in various places, I will try to figure out how could it help me. Thanks again.

**Comment by abhi2githubb** [comment]
> hey, try to create a content provider and instead of using Uri.parse, use content provider to get the files. it solved the issue for me.

hey deep can you please more explaination regarding this because i have same issue and i cant understood
