### ISSUE TITLE
Hls videos does not change its quality according to network bandwidth.

### ISSUE THREAD

**Issue by Sumit123rox** [eneim/Toro#484]
I'm using MediaSourceBuilder.DEFAULT to setMediaSourceBuilder in exoConfig. But when I play the video it plays on high resolution. It does not change its quality according to bandwidth.

`exoConfig = new im.ene.toro.exoplayer.Config.Builder(mInstance).setMediaSourceBuilder(MediaSourceBuilder.DEFAULT).setCache(cache)
                .setLoadControl(new DefaultLoadControl.Builder().setBufferDurationsMs(
                        DefaultLoadControl.DEFAULT_MIN_BUFFER_MS, DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                        1000, DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS
                ).createDefaultLoadControl()).build();`

Please provide a solution for it.

**Comment by androidvk** [comment]
@Sumit123rox Do you have different qualities of videos stored in the server??

**Comment by eneim** [comment]
@Sumit123rox can you share a video url that has this issue so I can test on my end?

**Comment by shiv71** [comment]
@Sumit123rox  did you find any soloution for this i am having same issue.
