### ISSUE TITLE
Gradle sync wont pass

### ISSUE THREAD

**Issue by xylik** [eneim/Toro#72]
Hi, today i cloned master branch and tried to start demo but gradle sync failed with this error:

Error:Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@61eaae09.

have any suggestions how to resolve the issue ?

**Comment by andrijans** [comment]
I'm having the same issue.

**Comment by eneim** [comment]
Please wait, I'm finishing some clean up before final release so there may be some hidden flags ...

**Comment by eneim** [comment]
@andrijans @xylik At the mean time, please add the following to your ```gradle.properties``` file:

```groovy
bintray_user=
bintray_apikey=
bintray_gpg_password=
```

If empty string doesn't work, please add some abitrary *one-character* String there (to prevent co-incident user/password, one-character is recommended since Bintray won't allow too short user name and password).

**Comment by xylik** [comment]
Thanks it's working when I added 

bintray_user=
bintray_apikey=
bintray_gpg_password=
