### ISSUE TITLE
Can Toro support google's exoplayer, or other players?

### ISSUE THREAD

**Issue by LLin233** [eneim/Toro#80]
I would like to use Toro to support autoplay, etc, however, we are using exoplayer, does Toro support it?

**Comment by eneim** [comment]
Hi there, thanks for your interest. Toro v1 is based on default MediaPlayer API and contains lots of not so good practices. 

To fix that, Toro v2 is in development right now which will use ExoPlayer by default. Currently latest RC release is RC5 (see Changelog.md for more), I plan to have final release at the end of this month (end of August). You can check out latest commits from **develop** branch for latest implementation. Final release will have many changes comparing to RC5 though.

So stay tune.

**Comment by LLin233** [comment]
That's cool, thanks.

**Comment by eneim** [comment]
@LLin233 FYI Toro 2.1.0 is out for you.

**Comment by LLin233** [comment]
@eneim Thanks for the noticing, I would definitely look into it.

**Comment by LLin233** [comment]
@eneim quick question..the lib is using custom ExoVideoview...do we need to implement our own if we need to use our player?

**Comment by eneim** [comment]
@LLin233 You mean a player API other than ExoPlayer or MediaPlayer? Yeah you should have your own way to add your API into the View which is expected to be a custom VideoView.
