### ISSUE TITLE
Autoplay does not work when new Activity is started

### ISSUE THREAD

**Issue by EligijusStarinskas** [eneim/Toro#81]
- the latest develop branch

- Lg nexus 5x (android 7)

I tried your library and everything works just fine when I have a single activity, but when I open a new Activity with same logic (RecyclerView filled with video list) autoplay does not work for the first time.

Lets say we have two activities : FirstActivity(FA) and SecondActivity(SA). When I'm in FA and I open SA here is a sequence of activity lifecycle methods : 
1) SA -> onActivityStarted()
2) FA -> onActivityStopped()

So the problem is that FA -> onActivityStopped() is called in the last place.

In my case, autoplay does not work for the first time as FA -> onActivityStopped() is called right after I do all the stuff to play first video in recycler view. onActivityStopped() method calls       dispatchOnActivityInactive(activity) and that's how it stops video playback in SA.

Am I doing something wrong or there is a bug in your library?

Thanks.

**Comment by eneim** [comment]
@EligijusStarinskas Thanks for the report. I will check it later. I guess I need to investigate how to deal well with Activity states for both API N and below.

**Comment by eneim** [comment]
Fixed in #86
