### ISSUE TITLE
Trying to Inflate in RecyclerView -> InflateException / ClassNotFoundException

### ISSUE THREAD

**Issue by adventurist** [eneim/toro#82]
Greetings! I don't believe this is an issue with your library so much as a configuration issue for which you may be able to offer valuable advice. I am trying to inflate a layout for a viewholder in my recyclerview which contains your Toro view. Unfortunately, I keep receiving both an InflateException and a ClassNotFoundException.

Any ideas on how to best configure my project? 

gradle-wrapper.properties

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.11-all.zip

```

app/build.gradle

```
plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "twitcher.twitcherurlconnect"
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

ext {
    toro_latest_version = '1.2.0'
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'com.android.support:design:23.2.1'
    compile 'com.yqritc:recyclerview-flexibledivider:1.4.0'
    compile "com.github.eneim:Toro:${toro_latest_version}"
    compile "com.github.eneim:Toro:1.2.0"

}

Device: Android: Nexus 5 API 23 x86 Emulator

Stack Tr
> E/AndroidRuntime: FATAL EXCEPTION: main
> Process: twitcher.twitcherurlconnect, PID: 29559
> android.view.InflateException: Binary XML file line #84: Binary XML file line #84: Error inflating class im.ene.lab.toro.player.widget.ToroVideoView
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>     at twitcher.twitcherurlconnect.StatusesAdapter.onCreateViewHolder(StatusesAdapter.java:160)
>     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5464)
>     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4689)
>     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599)
>     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
>     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
>     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
>     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1174)
>     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
>     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4043)
>     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
>     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
>     at android.view.Choreographer.doFrame(Choreographer.java:603)
>     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
>     at android.os.Handler.handleCallback(Handler.java:739)
>     at android.os.Handler.dispatchMessage(Handler.java:95)
>     at android.os.Looper.loop(Looper.java:148)
>     at android.app.ActivityThread.main(ActivityThread.java:5417)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>  Caused by: android.view.InflateException: Binary XML file line #84: Error inflating class im.ene.lab.toro.player.widget.ToroVideoView
>     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
>     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
>     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
>     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
>     at twitcher.twitcherurlconnect.StatusesAdapter.onCreateViewHolder(StatusesAdapter.java:160) 
>     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5464) 
>     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4689) 
>     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599) 
>     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988) 
>     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384) 
>     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347) 
>     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1174) 
>     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031) 
>     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4043) 
>     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858) 
>     at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
>     at android.view.Choreographer.doFrame(Choreographer.java:603) 
>     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
>     at android.os.Handler.handleCallback(Handler.java:739) 
>     at android.os.Handler.dispatchMessage(Handler.java:95) 
>     at android.os.Looper.loop(Looper.java:148) 
>     at android.app.ActivityThread.main(ActivityThread.java:5417) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
>  Caused by: java.lang.ClassNotFoundException: Didn't find class "im.ene.lab.toro.player.widget.ToroVideoView" on path: DexPathList[[zip file "/data/app/twitcher.twitcherurlconnect-1/base.apk"],nativeLibraryDirectories=[/data/app/twitcher.twitcherurlconnect-1/lib/x86, /vendor/lib, /system/lib]]
>     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>     at android.view.LayoutInflater.createView(LayoutInflater.java:583)
>     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
>     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
>     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
>     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
>     at twitcher.twitcherurlconnect.StatusesAdapter.onCreateViewHolder(StatusesAdapter.java:160) 
>     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5464) 
>     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4689) 
>     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599) 
>     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988) 
>     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384) 
>     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347) 
>     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1174) 
>     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031) 
>     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4043) 
>     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858) 
>     at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
>     at android.view.Choreographer.doFrame(Choreographer.java:603) 
>     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
>     at android.os.Handler.handleCallback(Handler.java:739) 
>     at android.os.Handler.dispatchMessage(Handler.java:95) 
>     at android.os.Looper.loop(Looper.java:148) 
>     at android.app.ActivityThread.main(ActivityThread.java:5417) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
>   Suppressed: java.lang.ClassNotFoundException: Didn't find class "im.ene.lab.toro.player.widget.ToroVideoView" on path: DexPathList[[dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-support-annotations-23.2.1_cc3ada849a687348dbc9a6080b8f35b918a42c4f-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/twitcher.twitcherurlconnect
> 
> 
```

**Comment by langrenfengzi** [comment]
I had the same issue when I used the item layout of 'vh_toro_video_average_1.xml' in the demo.
I found 2 ToroVideoView. In the sample demo,  it was **im.ene.lab.toro.player.widget.ToroVideoView** and used with the **ExoPlayer**. But when I used with the **compile 'com.github.eneim:Toro:1.2.0'**, it became the **im.ene.lab.toro.widget.ToroVideoView**.

**Comment by eneim** [comment]
Sorry for the late reply, the correct dependency definition for 2.0 is: ```im.ene.lab:toro```. Let's try again with this. The current change log is the closest documentation right now, check it out too:

> https://github.com/eneim/Toro/blob/develop/CHANGELOG.md

I'm working on the final draft, so stay tune.

**Comment by langrenfengzi** [comment]
Thanks for replying. 
In 2.0-RC5, I found the widget of playing the video was **im.ene.lab.toro.player.widget.VideoPlayerView**, and in the latest demo you renamed it to **ToroVideoView** again.

**Comment by eneim** [comment]
@langrenfengzi That's right, final release will have kind of many changes with RC5, so sorry for the inconvenient, but I would like to prevent future conflict with normal naming. For now, the spec is almost done (in me), I'm testing and reviewing to make sure everything works well.

**Comment by adventurist** [comment]
I have updated my code to use 2.0.0-RC4, which has fixed the multidex issue, but now I have a new issue when trying to inflate the VideoPlayerView.

In my viewholder's layout resource I am using:

`<im.ene.lab.toro.player.widget.VideoPlayerView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="192dp"
        android:layout_centerInParent="true"
        android:layout_gravity="center"
        />`

Inflating this from onCreateViewHolder causes:

>                                                                              java.lang.NullPointerException: A valid VideoPlayerView is required.
                                                                                 at im.ene.lab.toro.ext.ToroVideoViewHolder.<init>(ToroVideoViewHolder.java:40)
                                                                                 at twitcher.twitcherurlconnect.StatusesAdapter$StVolder.<init>(StatusesAdapter.java:0)
                                                                                 at twitcher.twitcherurlconnect.StatusesAdapter.onCreateViewHolder(StatusesAdapter.java:159)

> 

My older still extends the ToroVideoViewHolder class. Should this be different?

**Comment by eneim** [comment]
Hm, I will investigate your issue carefully this weekend. Please wait a little bit more :D

**Comment by adventurist** [comment]
No problem. Hopefully I'll have more time to play with it tonight. If I learn anything, I will post updates here. Thanks!

**Comment by adventurist** [comment]
Would you recommend this file as a good ToroViewViewHolder example?

**Comment by eneim** [comment]
For short, the sample class extends this: > https://github.com/eneim/Toro/blob/develop/toro-ext/src/main/java/im/ene/lab/toro/ext/ToroVideoViewHolder.java

So hope you got the idea. I will take further look later today (i'm at GMT +9:00).

**Comment by eneim** [comment]
Please refer the latest master branch though.

**Comment by adventurist** [comment]
Strangely enough, though I tried basing my viewholder off of that example, the following always returns null in spite of accurately referencing the view in my layout file:

`(im.ene.lab.toro.player.widget.VideoPlayerView) mView.findViewById(R.id.video_view);`

**Comment by eneim** [comment]
@adventurist Did you remove old dependency from your gradle.build? the ```com.github.eneim``` one. Just use only one dependency.

**Comment by adventurist** [comment]
That worked, findViewById no longer returns null. Thank you. 

I am still a bit confused about the implementation. Am I correct in understanding that videos play when scrolled to? Do I still need to implement a player or set the viewholder's "isPlayable" to "true"? I have been trying to do that, but it remains false. Any tips on troubleshooting?

**Comment by eneim** [comment]
@adventurist Good to hear that. That's my bad actually. I think I will update some new on current 2.0 soon. But for now, [this](https://github.com/eneim/Toro/blob/develop/toro-sample/src/main/java/im/ene/lab/toro/sample/presentation/basic1/Basic1VideoViewHolder.java) is the least you need to do to make it works. At first time opening the list, it may not work due to another issue, so just scroll a bit to see the effect :(. I'm fixing that issue now ... Basically current sample source code is working pretty well, please take a look.

**Comment by adventurist** [comment]
Thanks a lot for the direction! I have switched to trying to use an implementation similar to that of Basic1VideoViewHolder. I have been using the 2.0.0-RC4 version of your library. In the development repo, I see that ToroPlayer has the following method:

```
    @Override public void onPlaybackCompleted() {
        this.isPlayable = false;
    }
```

Is there an equivalent class to override in the 2.0.0-RC4 library?

**Comment by eneim** [comment]
@adventurist I think it is safe to use it now. I don't want to provide more methods to prevent the 65K issue. I think it will make more sense to use something provided by ExoPlayer, but since I need to keep track of the ViewHolder's life-cycle, it is a bit more complicated. Right now controlling the playability is set to second highest priority in my list after the Activity Lifecycle issue, please wait a bit more.

**Comment by adventurist** [comment]
@eneim Okay! I was going to try and work from the develop branch. May I ask for the correct method of importing it?

```
ext {
    toro_latest_version = 'develop';
}
```

**Comment by eneim** [comment]
@adventurist Sorry for the late reply. I have push latest snapshot to sonatype, you can use it by as follow:

```groovy
// Choose the suitable one
compile "im.ene.lab:toro:2.0.0-SNAPSHOT"
compile "im.ene.lab:toro-player:2.0.0-SNAPSHOT"
compile "im.ene.lab:toro-ext:2.0.0-SNAPSHOT"
```

**Comment by adventurist** [comment]
Hello! No problem.

I tried adding im.ene.lab:toro:2.0.0-SNAPSHOT to my gradle dependencies. Here's the error message I'm getting:

```
Error:Failed to resolve: im.ene.lab:toro:2.0.0-SNAPSHOT
<a href="openFile:/home/logicp/AndroidStudioProjects/myApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

**Comment by eneim** [comment]
@adventurist You need to add corresponding repository. Please refer to README again, I have just updated it.

**Comment by adventurist** [comment]
Thank you! 

Is the ToroViewHolder going to be part of the SNAPSHOT package?

**Comment by adventurist** [comment]
Thank you! I have it added into my project and will now begin trying to develop a working implementation.

You have been very helpful, and I appreciate it.

**Comment by adventurist** [comment]
Does 2.0.0-SNAPSHOT's ToroVideoViewHolder use something in place of "bind" to set the media URL on a ToroVideoView?

**Comment by eneim** [comment]
@adventurist It's safe to call ```setMedia``` from bind method of ToroVideoViewHolder. You should to that actually.

**Comment by adventurist** [comment]
Ah yes, I was hoping to do that. Have the method parameters changed? I can't seem to override the superclass when extending ToroVideoViewHolder.

In 2.0.0-RC4 I was using:

`@Override public void bind(@Nullable Object object) {
            Log.d("STAdapt", "attempting to bind");
            if (object != null && object instanceof StatusItem) {
                Log.d("STAdapt", "Setting media");
                twitVideo.setMedia(Uri.parse(((StatusItem) object).getVideo()));
            }
        }`

In SNAPSHOT, however, it doesn't override. 

Also, is there a way of cloning the files from Sonatype, so I can use grep to search through the parent classes?

Sorry for all the questions :)

**Comment by adventurist** [comment]
Ahh, yes, answer for above: It just needed to be passed a RecyclerView.Adapter

**Comment by adventurist** [comment]
Should have closed this 7 years ago :)
