### ISSUE TITLE
Gradle 'Toro-develop' project refresh failed

### ISSUE THREAD

**Issue by shikha7763** [eneim/Toro#83]
Error:Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@14f98d6. I am getting this error on gradle build.

**Comment by eneim** [comment]
Thanks for the interest. What gradle command did you use?

**Comment by eneim** [comment]
I added placeholder for those account in gradle.properties, please try again.

**Comment by shikha7763** [comment]
Error:Failed to resolve: com.github.eneim:Toro:1.2.0
<a href="openFile:E:/VideoListPlayer-master/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

IllegalArgumentException: Multiple entries with same key: Google Inc.:Google APIs:15=Google APIs (API 15) and Google Inc.:Google APIs:15=Google APIs (API 15) (moments ago)

now i am getting these error while gradle build and i am using  **classpath 'com.android.tools.build:gradle:2.1.2'** gradle.

**Comment by vigneshr87** [comment]
Help me! i am getting following error when i import the project in to Android Studio
Gradle 'Toro-dev-v2' project refresh failed
Error:Could not get unknown property 'bintray_user' for object of type com.jfrog.bintray.gradle.BintrayExtension.

**Comment by eneim** [comment]
Hi @vigneshr87 what do you want to do? Just use the library or you want to contribute by modifying the code too?

**Comment by vigneshr87** [comment]
i just want to use the library

**Comment by eneim** [comment]
@vigneshr87 if so, please see here (change the latest version to 2.3.0) for your setup.

https://github.com/eneim/Toro/tree/release/v2.3.0#3-how-to-use

**Comment by vigneshr87** [comment]
Thanks for your help...
