### ISSUE TITLE
How to play two videos in single holder ?

### ISSUE THREAD

**Issue by chetanurmaliya** [eneim/Toro#89]
I am using com.github.eneim:Toro:1.2.0
I want to auto play two videos in one holder.

**Comment by eneim** [comment]
@chetanurmaliya This is not a good practice I suppose, so I won't support this.

**Comment by chetanurmaliya** [comment]
In one holder I have two ToroVideoView views but at a time one video will play.
video_player_view1
video_player_view2
Inside bind() only I can identify which view has to used. 

@Override
    protected ToroVideoView findVideoView(View itemView) {
        return (ToroVideoView) itemView.findViewById(R.id.video_player_view1);
    }
But findVideoView() calls before bind().

What will be the best approach for this requirement ?

**Comment by eneim** [comment]
I don't support it. What is your use case?
