### ISSUE TITLE
im.ene.toro.exoplayer2.ExoVideoView is not visible

### ISSUE THREAD

**Issue by Nominalista** [eneim/Toro#99]
What I should add to dependencies to see im.ene.toro.exoplayer2.ExoVideoView class like in toro-sample?

**Comment by Nominalista** [comment]
It is impossible to first use your library, because wiki and read.me are inconsistent. Also it's sample is inconsistent with wiki, and read.me both.

**Comment by eneim** [comment]
@Nominalista Yes that's right. As you can see I push a lot last weekend, which means that Ver 2 is on the go. I have no time to update Wiki right now so please pardon. Right now looking at toro-sapmle and follow it is the best way. Please just ask question here I will response as much as possible. Ver 2 will be out soon.

**Comment by eneim** [comment]
@Nominalista About the first question, I didn't push the whole thing to neither maven nor jcenter yet. Right now forking the repo and use it as sub module or embed code is the only way. I don't want to mess up current SNAPSHOT since I made a big change on package name as well as project structure.

**Comment by Nominalista** [comment]
Thank you for response, I will use it as sub module.

**Comment by eneim** [comment]
@Nominalista I have pushed my latest code base to sonatype SNAPSHOT repo, you can include it as follow:

```
// Only Toro core implementation
compile "im.ene.toro2:toro:2.1.0-SNAPSHOT"
// Toro extension that contains Components based on ExoPlayer v2
compile "im.ene.toro2:extension-exoplayer2:2.1.0-SNAPSHOT"
// Extended of Toro, based on Toro Extension for ExoPlayer v2, with some new fun features
compile "im.ene.toro2:toro-extended:2.1.0-SNAPSHOT"

// The following dependencies are obsolete, but I put it together for your interest
// Simple extension for Legacy MediaPlayer API
compile "im.ene.toro2:extension-mediaplayer:2.1.0-SNAPSHOT"
// Fined tuned extension for ExoPlayer v1 (not too bad, but v2 is preferred and recommended)
compile "im.ene.toro2:extension-exoplayer:2.1.0-SNAPSHOT"
```

Note 1: version name is ```2.1.0-SNAPSHOT``` but not 2.0.0.

Note 2: SNAPSHOT requires sonatype repository which you can find at my latest README.

Note 3: that I drop the 2.0.0 due to some internal changes which may make current users Unhappy, and I move directly to 2.1.0 instead. Some final implementation is done, I'm preparing the final release soon. Hope this helps you.

**Comment by Nominalista** [comment]
Excellent, can we expect updated wiki and read.me in near future?

**Comment by eneim** [comment]
@Nominalista Of course. I need to update it for next release.
